"use client";
import {useState,useEffect,useCallback,useRef} from "react";
import {Cable,ClipboardCheck,Truck,ArrowUpRight,Plus,Check,Download,History,Settings,Layers,CalendarDays,ArrowLeft,RefreshCw,Mic,Square,ChevronRight} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Checkbox} from "@/components/ui/checkbox";
import {Progress} from "@/components/ui/progress";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import {Toaster,toast} from "sonner";
import {type Doc,type Command,type Role,type WoundMeasurement,roleNames,today,weightList,decimal,summary,sum,balances,prepareCommand,prepareWoundMeasurement,woundLength,windingTotals} from "@/lib/domain";
type AppState={demo:boolean;actor:{id:string;name:string;roles:Role[]};date:string;docs:Doc[];balances:ReturnType<typeof balances>;summary:ReturnType<typeof summary>;expected:any[];reviewIds:string[]};
type Editor=Command&{title:string};
declare global {interface Window{Telegram?:{WebApp:any}}}
const fmt=(n:number,unit=1)=>new Intl.NumberFormat("ru-RU",{maximumFractionDigits:3}).format(n/unit);
const newId=()=>crypto.randomUUID();
const measurementInput=(m?:WoundMeasurement)=>({metres:m?.directMm==null?"":String(m.directMm/1000),kg:m?.grams==null?"":String(m.grams/1000),weighedOn:m?.weighedOn||today()});
const measurementText=(m?:WoundMeasurement)=>[m?.directMm==null?"Измеренная длина ещё не указана":"Измерено: "+fmt(m.directMm,1000)+" м",m?.grams!=null?"По весу: "+fmt(m.calculatedMm!,1000)+" м · "+fmt(m.grams,1000)+" кг без тары · взвешено "+m.weighedOn:"Вес ещё не указан"].join(". ");
const statusText:Record<string,string>={work:"Работа",dayoff:"Выходной",idle:"Простой"};
const kindText:Record<string,string>={report:"Суточный отчёт",trip:"Рейс",adjustment:"Корректировка",coefficient:"Контрольный замер",opening:"Начальные остатки",pid:"ПИД",user:"Сотрудник",assignment:"Закрепление",cable:"Тип кабеля",export:"Выгрузка"};
function Picker({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label?:string}){return <Select value={value||undefined} onValueChange={onChange}><SelectTrigger aria-label={label||"Выбор"}><SelectValue placeholder="Выберите"/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
function Field({label,value,onChange,type="text",hint,required=false,readOnly=false}:{label:string;value:any;onChange:(v:string)=>void;type?:string;hint?:string;required?:boolean;readOnly?:boolean}){return <label className="field">{label}<input required={required} readOnly={readOnly} value={value??""} onChange={e=>onChange(e.target.value)} type={["decimal","integer"].includes(type)?"text":type} inputMode={type==="decimal"?"decimal":type==="integer"?"numeric":undefined}/>{hint&&<small>{hint}</small>}</label>;}
function DataTable({headers,children}:{headers:string[];children:React.ReactNode}){return <Table className="data-table"><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{children}</TableBody></Table>;}
export default function CableApp(){
 const [s,setS]=useState<AppState|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState("today"),[date,setDate]=useState(()=>{if(typeof window!=="undefined"){const d=new URLSearchParams(window.location.search).get("date");if(d&&/^\d{4}-\d{2}-\d{2}$/.test(d))return d;}return today();}),[demoUser,setDemoUser]=useState("demo-admin"),[selectedPid,setSelectedPid]=useState(""),[form,setForm]=useState<Editor|null>(null),[review,setReview]=useState(false),[formError,setFormError]=useState(""),[log,setLog]=useState<any[]>([]),[exportFrom,setExportFrom]=useState(today().slice(0,8)+"01"),[exportTo,setExportTo]=useState(today()),[resume,setResume]=useState<Editor|null>(null),[recording,setRecording]=useState(false);
 const [telegramReady,setTelegramReady]=useState(false);
 const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),initialized=useRef(false);
 const formScroll=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{if(formError)formScroll.current?.scrollTo({top:0});},[formError]);
 const headers=useCallback(()=>({"Content-Type":"application/json","x-demo-user":demoUser,"x-telegram-init-data":window.Telegram?.WebApp?.initData||""}),[demoUser]);
 const api=useCallback(async(path:string,options:RequestInit={})=>{const r=await fetch(path,{...options,headers:{...headers(),...options.headers}});const data=await r.json();if(!r.ok)throw new Error(data.error||"Не удалось выполнить действие");return data;},[headers]);
 const load=useCallback(async()=>{try{const data=await api("/api/state?date="+date);setS(data);setError("");}catch(e){setError((e as Error).message);}},[api,date]);
 useEffect(()=>{
  let disposed=false;
  const ready=()=>{if(disposed)return;const app=window.Telegram?.WebApp;app?.ready();app?.expand();setTelegramReady(true);};
  if(window.Telegram?.WebApp){ready();return;}
  const script=document.createElement("script");script.src="https://telegram.org/js/telegram-web-app.js";script.async=true;script.onload=ready;script.onerror=ready;document.head.appendChild(script);
  const timeout=setTimeout(ready,8000);
  return()=>{disposed=true;clearTimeout(timeout);script.remove();};
 },[]);
 useEffect(()=>{if(telegramReady)void load();},[load,telegramReady]);
 useEffect(()=>{if(!s)return;const saved=localStorage.getItem("pid-draft:"+s.actor.id);try{setResume(saved?JSON.parse(saved):null);}catch{setResume(null);}},[s?.actor.id]);
 useEffect(()=>{if(form&&s){localStorage.setItem("pid-draft:"+s.actor.id,JSON.stringify(form));setResume(form);}},[form,s?.actor.id]);
 useEffect(()=>{if(s&&!initialized.current){initialized.current=true;const p=new URLSearchParams(window.location.search);const pid=p.get("pid"),category=p.get("category"),requested=p.get("date");if(pid&&category&&s.docs.some(d=>d.id===pid)){openReport(pid,category,requested||date);}}},[s]);
 const docs=s?.docs||[],pids=docs.filter(d=>d.kind==="pid"),cables=docs.filter(d=>d.kind==="cable"),users=docs.filter(d=>d.kind==="user"),actor=s?.actor;
 const admin=actor?.roles.includes("admin"),has=(r:Role)=>admin||actor?.roles.includes(r);
 const pidName=(id:string|null)=>"ПИД"+(docs.find(d=>d.id===id)?.data.code||"?");
 const cableName=(id:string)=>docs.find(d=>d.id===id)?.data.name||"Тип не найден";
 const userName=(id:string)=>docs.find(d=>d.id===id)?.data.name||id;
 const pidOptions=pids.map(d=>({value:d.id,label:pidName(d.id)})),cableOptions=cables.map(d=>({value:d.id,label:d.data.name}));
 const edit=(title:string,action:string,data:any,old?:Doc)=>{setForm({title,action,data,id:old?.id,expectedVersion:old?.version,requestId:newId()});setReview(false);setFormError("");};
 const change=(key:string,value:any)=>{setForm(f=>f?{...f,requestId:newId(),data:{...f.data,[key]:value}}:null);setFormError("");};
 function openReport(pid:string,category:string,reportDate=date,old?:Doc){
  old=old||docs.find(d=>d.kind==="report"&&d.author===actor?.id&&d.pid===pid&&d.date===reportDate&&d.data.category===category);
  const prev=old||docs.filter(d=>d.kind==="report"&&d.author===actor?.id&&d.pid===pid&&d.data.category===category&&d.data.status==="work"&&d.date<=reportDate).sort((a,b)=>b.date.localeCompare(a.date))[0];
  edit(category==="excavation"?"Копка и извлечение":"Намотка","report",{pid,date:reportDate,category,status:old?.data.status||"work",cableId:old?.data.cableId||prev?.data.cableId||cables[0]?.id,trench:old?.data.trenchMm==null?"":String(old.data.trenchMm/1000),cable:old?.data.cableMm==null?"":String(old.data.cableMm/1000),lines:old?.data.lines?.map((l:any)=>({...l,count:String(l.count),measurement:measurementInput(l.measurement)}))||prev?.data.lines?.map((l:any)=>({cableId:l.cableId,count:"",measurement:measurementInput()}))||[{cableId:cables[0]?.id,count:"",measurement:measurementInput()}],note:old?.data.note||"",audioId:old?.data.audioId||null},old);
 }
 function openTrip(old?:Doc){
  const groups:Record<string,string[]>={};for(const c of old?.data.coils||[])(groups[c.cableId]??=[]).push(String(c.grams/1000).replace(".",","));
  edit(old?"Исправление отправки":"Новая отправка","trip",{pid:old?.pid||selectedPid||pids[0]?.id,date:old?.date||date,groups:old?Object.entries(groups).map(([cableId,masses])=>({cableId,masses:masses.join(" ")})):[{cableId:cables[0]?.id,masses:""}]},old);
 }
 function openReceipt(trip:Doc){edit(trip.data.receipt?"Исправление приёмки":"Приёмка рейса","receipt",{date:trip.data.receipt?.date||date,weights:Object.fromEntries(trip.data.coils.map((c:any)=>[c.id,trip.data.receipt?.weights[c.id]?String(trip.data.receipt.weights[c.id]/1000):""]))},trip);}
 async function submit(){if(!form)return;setBusy(true);setFormError("");try{const {title,...cmd}=form;await api("/api/command",{method:"POST",body:JSON.stringify(cmd)});localStorage.removeItem("pid-draft:"+actor!.id);setResume(null);setForm(null);setReview(false);toast.success("Сохранено");await load();}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 function verify(){
  if(!form)return;formScroll.current?.scrollTo({top:0});try{prepareCommand(docs,actor!,form);const d=form.data;
   if(form.action==="report"&&d.status==="work"){if(d.category==="excavation"){decimal(d.trench);decimal(d.cable);}else d.lines.forEach((l:any)=>decimal(l.count,0));}
   if(form.action==="trip")d.groups.forEach((g:any)=>weightList(g.masses));
   if(form.action==="receipt")Object.values(d.weights).forEach(w=>{if(decimal(w)<=0)throw new Error("Взвесьте все катушки");});
   setReview(true);setFormError("");
  }catch(e){setFormError((e as Error).message);}
 }
 async function getHistory(id?:string){try{const r=await api("/api/history"+(id?"?id="+encodeURIComponent(id):""));setLog(r.history);setTab("history");}catch(e){toast.error((e as Error).message);}}
 async function exportFile(){setBusy(true);try{const r=await fetch("/api/export",{method:"POST",headers:headers(),body:JSON.stringify({from:exportFrom,to:exportTo,requestId:newId()})});if(!r.ok){const d=await r.json();throw new Error(d.error);}const blob=await r.blob();const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="PID_"+exportFrom+"_"+exportTo+".xlsx";a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast.success("Файл сформирован. Загрузка в 1С не подтверждена.");await load();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function audioUpload(blob:Blob){setBusy(true);try{const fd=new FormData();fd.append("file",blob,"idle.webm");const h:any=headers();delete h["Content-Type"];const r=await fetch("/api/audio",{method:"POST",headers:h,body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error);change("audioId",d.id);toast.success("Аудио добавлено");}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 async function toggleAudio(){if(recording){recorder.current?.stop();return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);recorder.current=r;chunks.current=[];r.ondataavailable=e=>chunks.current.push(e.data);r.onstop=()=>{stream.getTracks().forEach(t=>t.stop());setRecording(false);void audioUpload(new Blob(chunks.current,{type:r.mimeType}));};r.start();setRecording(true);}catch{setFormError("Микрофон недоступен. Можно прикрепить аудиофайл.");}}
 function renderReport(d:Doc){return <article className="task-card" key={d.id}><ClipboardCheck/><div><h3>{pidName(d.pid)} · {d.data.category==="excavation"?"Извлечение":"Намотка"}</h3><p>{userName(d.author)} · {d.date}</p><p>{d.data.status==="work"?(d.data.category==="excavation"?fmt(d.data.trenchMm,1000)+" / "+fmt(d.data.cableMm,1000)+" м · "+cableName(d.data.cableId):d.data.lines.map((l:any)=>cableName(l.cableId)+": "+(woundLength(l.measurement)==null?"длина уточняется":fmt(woundLength(l.measurement)!,1000)+" м")+" · "+l.count+" шт.").join("; ")):statusText[d.data.status]}</p>{d.data.note&&<p>{d.data.note}</p>}</div><div className="stack compact">{d.author===actor?.id&&<button className="action quiet" onClick={()=>openReport(d.pid!,d.data.category,d.date,d)}>Исправить / уточнить</button>}<button className="action quiet" onClick={()=>getHistory(d.id)}>История</button></div></article>;}
 const formTrip=form?.id?docs.find(d=>d.id===form.id&&d.kind==="trip"):undefined;
 return <main className="workspace"><Toaster position="top-center" richColors/><header className="masthead"><div className="brand"><Cable/><span>ПИД<small>Учёт кабеля</small></span></div><div className="row">{s?.demo&&<span className="pill">Тестовые данные</span>}<button className="icon-button" aria-label="Обновить" onClick={()=>load()}><RefreshCw size={19}/></button></div></header>
 {s?.demo&&<div className="demo-toolbar"><span>Проверить как</span><Picker value={demoUser} onChange={v=>{setDemoUser(v);setForm(null);setSelectedPid("");setTab("today");}} options={users.map(u=>({value:u.id,label:u.data.name+" · "+u.data.roles.map((r:Role)=>roleNames[r]).join(", ")}))} label="Проверочная роль"/></div>}
 {error&&<div className="notice error section-gap" role="alert">{error}<button className="action quiet" onClick={()=>load()}>Повторить</button></div>}
 {!s&&!error&&<div className="empty">Загружаем рабочий день…</div>}
 {s&&<Tabs value={tab} onValueChange={v=>{setTab(v);if(v==="history")void getHistory();}}>
 <TabsList className="tabs-bar" aria-label="Разделы приложения"><TabsTrigger value="today"><CalendarDays/><span>Сегодня</span></TabsTrigger><TabsTrigger value="pids"><Layers/><span>Все ПИД</span></TabsTrigger><TabsTrigger value="trips"><Truck/><span>Рейсы</span></TabsTrigger><TabsTrigger value="history"><History/><span>История</span></TabsTrigger>{admin&&<TabsTrigger value="admin" aria-label="Управление"><Settings/><span>Управ&shy;ление</span></TabsTrigger>}</TabsList>
 <TabsContent value="today">
  <section className="page-heading"><div><p className="eyebrow">{actor?.name}</p><h1>Рабочий день</h1><p className="muted">Копка, намотка и движение кабеля</p></div><label className="date-picker"><CalendarDays size={18}/><input aria-label="Дата отчётов" type="date" value={date} max={today()} onChange={e=>setDate(e.target.value)}/></label></section>
  <div className="metric-grid"><Metric label="Трасса за день" value={fmt(s.summary.trenchMm,1000)} unit="м"/><Metric label="Извлечено" value={fmt(s.summary.cableMm,1000)} unit="м"/><WindingMetric label="Намотано за день" totals={windingTotals(docs,date,undefined,true)}/></div>
  {resume&&!form&&<div className="notice section-gap row spread"><span>Есть незавершённая форма на этом устройстве</span><button className="action quiet" onClick={()=>{setForm(resume);setReview(false);}}>Продолжить</button></div>}
  <div className="section-title"><h2>{admin||has("observer")?"Сдача отчётов":"Мои отчёты"}</h2><span className="muted">Запрос 19:00 · сводка 21:00</span></div>
  {s.expected.filter(x=>admin||has("observer")||x.userId===actor?.id).map((x:any)=>{const report=docs.find(d=>d.kind==="report"&&d.author===x.userId&&d.pid===x.pid&&d.date===date&&d.data.category===x.category);return <article className="task-card" key={x.userId+x.pid+x.category}><ClipboardCheck/><div><h3>{pidName(x.pid)} · {x.category==="excavation"?"Копка и извлечение":"Намотка"}</h3><p>{userName(x.userId)}</p></div>{x.userId===actor?.id?<button className="action" onClick={()=>openReport(x.pid,x.category)}>{report?"Открыть":"Заполнить"}</button>:<span className={"badge "+(report?"done":"pending")}>{report?statusText[report.data.status]:"Не сдан"}</span>}</article>;})}
  {!s.expected.length&&<div className="empty">На эту дату нет закреплений</div>}
  <div className="row section-gap">{has("shipper")&&<button className="action" onClick={()=>openTrip()}><Plus/>Новая отправка</button>}{has("warehouse")&&<button className="action secondary" onClick={()=>setTab("trips")}><Truck/>Ожидающие рейсы</button>}</div>
  <div className="section-title"><h2>Подтверждённые отчёты</h2><span className="muted">{date}</span></div>
  {docs.filter(d=>d.kind==="report"&&d.date===date).map(renderReport)}
  {!docs.some(d=>d.kind==="report"&&d.date===date)&&<div className="empty panel">За этот день отчётов пока нет</div>}
 </TabsContent>
 <TabsContent value="pids">
  <section className="page-heading"><div><p className="eyebrow">СКВОЗНОЙ УЧЁТ</p><h1>{selectedPid?pidName(selectedPid):"Все ПИД"}</h1><p className="muted">Расчётные метры · катушки · фактический вес</p></div>{selectedPid&&<button className="action secondary" onClick={()=>setSelectedPid("")}><ArrowLeft/>Все ПИД</button>}</section>
  {!selectedPid?pids.map(p=>{const rows=s.balances.filter(b=>b.pid===p.id),trips=docs.filter(d=>d.kind==="trip"&&d.pid===p.id&&!d.data.receipt).length;return <button className="task-card pid-card" key={p.id} onClick={()=>setSelectedPid(p.id)}><Layers/><div><h3>{pidName(p.id)}</h3><p>{rows.length} типа · {trips} рейсов в пути</p></div><div className="pid-numbers"><strong className={sum(rows.map(r=>r.mm))<0?"negative":""}>{fmt(sum(rows.map(r=>r.mm)),1000)} м</strong><span>{sum(rows.map(r=>r.coils))} катушек</span></div><ChevronRight/></button>}):<>
   <div className="panel"><h2>Остатки на {date}</h2><DataTable headers={["Тип","На ПИД, м","На ПИД, шт."]}>{s.balances.filter(b=>b.pid===selectedPid).map(b=><TableRow key={b.cableId}><TableCell>{cableName(b.cableId)}</TableCell><TableCell className={b.mm<0?"negative":""}>{fmt(b.mm,1000)}</TableCell><TableCell className={b.coils<0?"negative":""}>{b.coils}</TableCell></TableRow>)}</DataTable><p className="footer-note">В поле и на временной площадке ПИД, ещё не отправлено на склад. Метры включают намотанный и ненамотанный кабель; катушки — дополнительная единица той же части кабеля.</p></div>
   <div className="section-title"><h2>Накопленные объёмы</h2></div><div className="metric-grid production-grid"><Metric label="Пройдено трассы" value={fmt((docs.find(d=>d.id===selectedPid)?.data.accumulatedTrenchMm||0)+sum(docs.filter(d=>d.kind==="report"&&d.pid===selectedPid&&d.data.category==="excavation"&&d.data.status==="work"&&d.date<=date).map(d=>d.data.trenchMm)),1000)} unit="м"/><Metric label="Извлечено" value={fmt(sum(s.balances.filter(b=>b.pid===selectedPid).map(b=>b.extractedMm)),1000)} unit="м"/><Metric label="Принято на склад" value={fmt(sum(s.balances.filter(b=>b.pid===selectedPid).map(b=>b.receivedGrams)),1000000)} unit="т накопленно"/><WindingMetric label="Намотано за всё время" totals={windingTotals(docs,date,selectedPid)}/></div>
   <div className="section-title"><h2>Движение по типам</h2></div><div className="panel"><DataTable headers={["Тип","Отправлено, кг","В пути, кг","Разница, кг"]}>{s.balances.filter(b=>b.pid===selectedPid).map(b=><TableRow key={b.cableId}><TableCell>{cableName(b.cableId)}</TableCell><TableCell>{fmt(b.sentGrams,1000)}</TableCell><TableCell>{fmt(b.transitGrams,1000)}</TableCell><TableCell>{fmt(b.differenceGrams,1000)}</TableCell></TableRow>)}</DataTable></div>
   <div className="section-title"><h2>Первичные отчёты</h2></div>{docs.filter(d=>d.kind==="report"&&d.pid===selectedPid).sort((a,b)=>b.date.localeCompare(a.date)).map(renderReport)}
  </>}
 </TabsContent>
 <TabsContent value="trips">
  <section className="page-heading"><div><p className="eyebrow">ДВИЖЕНИЕ КАБЕЛЯ</p><h1>Рейсы</h1><p className="muted">Одна отправка — один ПИД</p></div>{has("shipper")&&<button className="action" onClick={()=>openTrip()}><Plus/>Отправить</button>}</section>
  {docs.filter(d=>d.kind==="trip").sort((a,b)=>b.date.localeCompare(a.date)).map(t=><article className="panel section-gap" key={t.id}><div className="row spread"><div><h2>{pidName(t.pid)} <span className={"badge "+(t.data.receipt?"done":"pending")}>{t.data.receipt?"Принят":"В пути"}</span></h2><p className="muted">{t.date} · {userName(t.author)}</p></div><strong>{fmt(sum(t.data.coils.map((c:any)=>c.grams)),1000)} кг</strong></div><p className="section-gap">{t.data.coils.length} катушек · {[...new Set<string>(t.data.coils.map((c:any)=>c.cableId))].map(cableName).join(", ")}</p>
   {t.data.receipt&&<div className="notice section-gap">Принято {fmt(sum(Object.values(t.data.receipt.weights) as number[]),1000)} кг · разница {fmt(sum(Object.values(t.data.receipt.weights) as number[])-sum(t.data.coils.map((c:any)=>c.grams)),1000)} кг</div>}
   <div className="row section-gap">{has("warehouse")&&(!t.data.receipt||t.data.receipt.author===actor?.id)&&<button className="action" onClick={()=>openReceipt(t)}>{t.data.receipt?"Исправить приёмку":"Принять рейс"}</button>}{(t.author===actor?.id||admin)&&<button className="action secondary" onClick={()=>openTrip(t)}>Исправить отправку</button>}<button className="action quiet" onClick={()=>getHistory(t.id)}>Ведомость и история</button></div>
  </article>)}
  {!docs.some(d=>d.kind==="trip")&&<div className="empty panel">Отправок пока нет</div>}
 </TabsContent>
 <TabsContent value="history">
  <section className="page-heading"><div><p className="eyebrow">ПЕРВИЧНЫЕ ДАННЫЕ</p><h1>История</h1><p className="muted">Авторы, версии и исходные ведомости</p></div><button className="action secondary" onClick={()=>getHistory()}><RefreshCw/>Все записи</button></section>
  <div className="panel">{log.filter(d=>!["audio"].includes(d.kind)).map(d=><article className="journal" key={d.id+":"+d.version}><div className="row spread"><strong>{kindText[d.kind]||d.kind}{d.pid?" · "+pidName(d.pid):""}</strong><span className="badge">Версия {d.version}</span></div><p className="muted">{d.date} · {userName(d.editor||d.author)} · {new Date(d.createdAt).toLocaleString("ru-RU",{timeZone:"Asia/Krasnoyarsk"})}</p>
   <HistoryDetail d={d} cableName={cableName}/>
   {d.kind==="report"&&d.data.audioId&&<button className="action quiet" onClick={async()=>{const r=await fetch("/api/audio?id="+d.data.audioId,{headers:headers()});if(!r.ok){toast.error("Аудио недоступно");return;}const url=URL.createObjectURL(await r.blob());const audio=new Audio(url);audio.onended=()=>URL.revokeObjectURL(url);await audio.play();}}>Прослушать пояснение</button>}
  </article>)}{!log.length&&<div className="empty">История пока пуста</div>}</div>
 </TabsContent>
 {admin&&<TabsContent value="admin">
  <section className="page-heading"><div><p className="eyebrow">АДМИНИСТРАТОР</p><h1>Управление</h1><p className="muted">Справочники, закрепления и контроль учёта</p></div></section>
  {s.reviewIds.length>0&&<div className="notice section-gap">После поздних записей требуется повторно проверить корректировки: {s.reviewIds.length}. Автоматического изменения остатков нет.</div>}
  <div className="split"><div className="panel stack"><h2>Справочники</h2>
   <button className="action secondary" onClick={()=>edit("Новый ПИД","pid",{code:"",cutoff:today(),accumulatedTrench:"0",active:true})}><Plus/>Добавить ПИД</button>
   <button className="action secondary" onClick={()=>edit("Новый тип кабеля","cable",{name:""})}><Plus/>Добавить тип кабеля</button>
   <button className="action secondary" onClick={()=>edit("Сотрудник","user",{name:"",telegramId:"",roles:["foreman"],active:true})}><Plus/>Добавить сотрудника</button>
   <button className="action secondary" onClick={()=>edit("Закрепление за ПИД","assignment",{pid:pids[0]?.id,userId:users.find(u=>u.data.roles.includes("foreman"))?.id,role:"foreman",from:today(),until:""})}><Plus/>Закрепить сотрудника</button>
   <button className="action secondary" onClick={()=>edit("Контрольное взвешивание","coefficient",{pid:pids[0]?.id,cableId:cables[0]?.id,date:today(),sampleMetres:"",sampleKg:""})}><Plus/>Контрольный замер</button>
   <button className="action secondary" onClick={()=>edit("Кабель на ПИД к началу учёта","opening",{pid:pids[0]?.id,cableId:cables[0]?.id,metres:"",coils:"",woundMeasurement:measurementInput(),accumulatedExtracted:"0",accumulatedWound:"0",accumulatedWoundMetres:""})}><Plus/>Начальные данные</button>
   <button className="action secondary" onClick={()=>edit("Корректировка по проверке","adjustment",{pid:pids[0]?.id,cableId:cables[0]?.id,date:today(),actualMetres:"",actualCoils:"",reason:""})}><Plus/>Корректировка остатка</button>
  </div><div className="panel stack"><h2>Файл для 1С</h2><p className="muted">Отправки, приёмки и исправления. Excel собственного формата.</p><div className="field-grid"><Field label="С" type="date" value={exportFrom} onChange={setExportFrom}/><Field label="По" type="date" value={exportTo} onChange={setExportTo}/></div><button className="action" disabled={busy} onClick={exportFile}><Download/>Выгрузить Excel</button><p className="draft-note">Изменения ранее выгруженных операций попадут в файл независимо от выбранного периода. Выгрузка не означает загрузку в 1С.</p>
   <h3>Последние выгрузки</h3>{docs.filter(d=>d.kind==="export").slice(-5).reverse().map(d=><p key={d.id} className="muted">{d.data.from} — {d.data.to}<br/>{d.data.importedAt?"Загружено в 1С":"Выгружено · загрузка не подтверждена"} {d.data.importedAt?null:<button className="action quiet" onClick={async()=>{try{await api("/api/export",{method:"PATCH",body:JSON.stringify({id:d.id,expectedVersion:d.version,requestId:newId()})});await load();}catch(e){toast.error((e as Error).message);}}}>Подтвердить загрузку в 1С</button>}</p>)}
  </div></div>
  <div className="section-title"><h2>Сотрудники</h2></div><div className="panel">{users.map(u=><div className="row spread list-row" key={u.id}><div><strong>{u.data.name}</strong><p className="muted">{u.data.roles.map((r:Role)=>roleNames[r]).join(", ")}{u.data.active===false?" · отключён":""}</p></div><button className="action quiet" onClick={()=>edit("Сотрудник","user",{...u.data},u)}>Изменить</button></div>)}</div>
  <div className="section-title"><h2>Закрепления</h2></div><div className="panel">{docs.filter(d=>d.kind==="assignment").map(d=><div className="row spread list-row" key={d.id}><div><strong>{userName(d.data.userId)} · {pidName(d.pid)}</strong><p className="muted">{roleNames[d.data.role as Role]} · {d.data.from} — {d.data.until||"по настоящее время"}</p></div><button className="action quiet" onClick={()=>edit("Изменить срок закрепления","assignment",{...d.data,until:d.data.until||""},d)}>Изменить</button></div>)}</div>
  <div className="section-title"><h2>Контрольные замеры</h2></div><div className="panel"><DataTable headers={["ПИД / тип","Дата","Кг/м"]}>{docs.filter(d=>d.kind==="coefficient").map(d=><TableRow key={d.id}><TableCell>{pidName(d.pid)}<br/>{cableName(d.data.cableId)}</TableCell><TableCell>{d.date}</TableCell><TableCell>{fmt(d.data.sampleGrams/d.data.sampleMm)}</TableCell></TableRow>)}</DataTable></div>
  <div className="section-title"><h2>Кабель на ПИД к началу учёта</h2></div><div className="panel">{docs.filter(d=>d.kind==="opening").map(d=><div className="row spread list-row" key={d.id}><div><strong>{pidName(d.pid)} · {cableName(d.data.cableId)}</strong><p className="muted">На начало {d.date}: на ПИД {fmt(d.data.mm,1000)} м, из них {d.data.coils} катушек. Не отправлено на склад.</p><p className="muted">В этих катушках: {woundLength(d.data.woundMeasurement)==null?"длина уточняется":fmt(woundLength(d.data.woundMeasurement)!,1000)+" м"}.</p></div><button className="action quiet" onClick={()=>edit("Уточнение кабеля на начало учёта","opening",{pid:d.pid,cableId:d.data.cableId,metres:String(d.data.mm/1000),coils:String(d.data.coils),woundMeasurement:measurementInput(d.data.woundMeasurement),accumulatedExtracted:String((d.data.accumulatedExtractedMm||0)/1000),accumulatedWound:String(d.data.accumulatedWound||0),accumulatedWoundMetres:d.data.accumulatedWoundMm==null?"":String(d.data.accumulatedWoundMm/1000)},d)}>Исправить / уточнить</button></div>)}</div>
  <div className="section-title"><h2>Корректировки</h2></div><div className="panel">{docs.filter(d=>d.kind==="adjustment").map(d=><div className="list-row" key={d.id}><strong>{pidName(d.pid)} · {cableName(d.data.cableId)}</strong><p>{d.data.reason}</p><p className="muted">{fmt(d.data.deltaMm,1000)} м · {d.data.deltaCoils} катушек{s.reviewIds.includes(d.id)?" · нужна повторная проверка":""}</p><button className="action quiet" onClick={()=>edit("Повторная проверка корректировки","adjustment",{pid:d.pid,cableId:d.data.cableId,date:d.date,actualMetres:d.data.actualMm==null?"":String(d.data.actualMm/1000),actualCoils:d.data.actualCoils??"",reason:d.data.reason},d)}>Проверить</button></div>)}{!docs.some(d=>d.kind==="adjustment")&&<p className="muted">Корректировок нет</p>}</div>
 </TabsContent>}
 </Tabs>}
 <Dialog open={!!form} onOpenChange={open=>{if(!open&&!busy&&!recording){setForm(null);setReview(false);}}}><DialogContent className="dialog-body" showCloseButton={false}><DialogHeader><span className="form-step">{review?"02 · Подтверждение":"01 · Ввод данных"}</span><DialogTitle>{review?"Проверьте данные":form?.title}</DialogTitle><DialogDescription>{form?.data.pid?pidName(form.data.pid)+" · ":formTrip?pidName(formTrip.pid)+" · ":""}{form?.data.date||"Данные сохранятся после подтверждения"}</DialogDescription></DialogHeader>
 {form&&<><div key={review?"review":"edit"} ref={formScroll} className="form-scroll stack">
  {formError&&<div className="notice error" role="alert">{formError}</div>}
  {review?<Review form={form} docs={docs} pidName={pidName} cableName={cableName}/>:<>
   {["trip","adjustment","coefficient","opening","assignment"].includes(form.action)&&!(form.id&&["trip","opening","assignment"].includes(form.action))&&<label className="field">ПИД<Picker value={form.data.pid} onChange={v=>change("pid",v)} options={pidOptions}/></label>}
   {["report","trip","receipt","adjustment","coefficient"].includes(form.action)&&<Field label="Дата" value={form.data.date} type="date" readOnly={!!form.id&&["report","trip"].includes(form.action)} onChange={v=>change("date",v)}/>}
   {form.action==="report"&&<>
    <Tabs value={form.data.status} onValueChange={v=>change("status",v)}><TabsList className="status-tabs"><TabsTrigger value="work">Работа</TabsTrigger><TabsTrigger value="dayoff">Выходной</TabsTrigger><TabsTrigger value="idle">Простой</TabsTrigger></TabsList></Tabs>
    {form.data.status==="work"&&form.data.category==="excavation"&&<><label className="field">Тип кабеля<Picker value={form.data.cableId} onChange={v=>change("cableId",v)} options={cableOptions}/></label><div className="field-grid report-quantities"><Field label="Трасса, м" type="decimal" value={form.data.trench} onChange={v=>change("trench",v)}/><Field label="Извлечено, м" type="decimal" value={form.data.cable} onChange={v=>change("cable",v)}/></div></>}
    {form.data.status==="work"&&form.data.category==="winding"&&<><div className="notice">Намотка переводит извлечённый кабель в катушки на том же ПИД. Метры — основной объём работы, катушки — дополнительный. Взвешивание можно внести позднее, уточнив этот отчёт.</div>{form.data.lines.map((l:any,i:number)=><div className="group-box" key={i}><label className="field">Тип кабеля<Picker value={l.cableId} onChange={v=>change("lines",form.data.lines.map((x:any,j:number)=>j===i?{...x,cableId:v,measurement:measurementInput()}:x))} options={cableOptions}/></label><Field label="Катушек намотано за день, шт." type="integer" value={l.count} onChange={v=>change("lines",form.data.lines.map((x:any,j:number)=>j===i?{...x,count:v}:x))}/><WoundMeasurementFields docs={docs} pid={form.data.pid} cableId={l.cableId} count={l.count} value={l.measurement} previous={docs.find(d=>d.id===form.id)?.data.lines?.find((x:any)=>x.cableId===l.cableId)?.measurement} onChange={v=>change("lines",form.data.lines.map((x:any,j:number)=>j===i?{...x,measurement:v}:x))}/>{form.data.lines.length>1&&<button className="action quiet" onClick={()=>change("lines",form.data.lines.filter((_:any,j:number)=>j!==i))}>Убрать строку</button>}</div>)}<button className="action secondary" onClick={()=>change("lines",[...form.data.lines,{cableId:cables.find(c=>!form.data.lines.some((l:any)=>l.cableId===c.id))?.id||cables[0]?.id,count:"",measurement:measurementInput()}])}><Plus/>Ещё тип</button></>}
    {form.data.status==="idle"&&<><label className="field">Пояснение — необязательно<textarea value={form.data.note} onChange={e=>change("note",e.target.value)} placeholder="Причина простоя"/></label><div className="row"><button className="action secondary" onClick={toggleAudio} disabled={busy}>{recording?<Square/>:<Mic/>}{recording?"Остановить":"Записать голосом"}</button><label className="action secondary">Аудиофайл<input type="file" accept="audio/*" className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(f)void audioUpload(f);}}/></label></div>{form.data.audioId&&<span className="badge done">Аудио добавлено</span>}</>}
   </>}
   {form.action==="trip"&&<>{form.data.groups.map((g:any,i:number)=><div className="group-box" key={i}><label className="field">Тип кабеля<Picker value={g.cableId} onChange={v=>change("groups",form.data.groups.map((x:any,j:number)=>j===i?{...x,cableId:v}:x))} options={cableOptions}/></label><label className="field">Массы катушек, кг<textarea inputMode="decimal" placeholder="123 234 345 456" value={g.masses} onChange={e=>change("groups",form.data.groups.map((x:any,j:number)=>j===i?{...x,masses:e.target.value}:x))}/><small>Только кабель, без тары. Дробные значения — через запятую.</small></label><MassPreview value={g.masses}/>{form.data.groups.length>1&&<button className="action quiet" onClick={()=>change("groups",form.data.groups.filter((_:any,j:number)=>j!==i))}>Убрать тип</button>}</div>)}<button className="action secondary" onClick={()=>change("groups",[...form.data.groups,{cableId:cables.find(c=>!form.data.groups.some((g:any)=>g.cableId===c.id))?.id||cables[0]?.id,masses:""}])}><Plus/>Добавить тип</button></>}
   {form.action==="receipt"&&formTrip&&<ReceiptFields coils={formTrip.data.coils} weights={form.data.weights} cableName={cableName} onChange={weights=>change("weights",weights)}/>}
   {["adjustment","coefficient","opening"].includes(form.action)&&(form.action==="opening"&&form.id?<Field label="Тип кабеля" value={cableName(form.data.cableId)} readOnly onChange={()=>{}}/>:<label className="field">Тип кабеля<Picker value={form.data.cableId} onChange={v=>{change("cableId",v);if(form.action==="opening")change("woundMeasurement",measurementInput());}} options={cableOptions}/></label>)}
   {form.action==="adjustment"&&<><div className="notice">Введите проверенный фактический остаток. Поправка сохранится отдельно от выполненных работ.</div><div className="field-grid"><Field label="Фактически, м" value={form.data.actualMetres} onChange={v=>change("actualMetres",v)} type="decimal" hint="Оставьте пустым, если не проверяли"/><Field label="Фактически, катушек" value={form.data.actualCoils} onChange={v=>change("actualCoils",v)} type="decimal" hint="Оставьте пустым, если не проверяли"/></div><label className="field">Основание проверки<textarea value={form.data.reason} onChange={e=>change("reason",e.target.value)} placeholder="Что проверено и почему отличается остаток"/></label></>}
   {form.action==="coefficient"&&<><div className="field-grid"><Field label="Длина отрезка, м" value={form.data.sampleMetres} type="decimal" onChange={v=>change("sampleMetres",v)}/><Field label="Масса отрезка, кг" value={form.data.sampleKg} type="decimal" onChange={v=>change("sampleKg",v)}/></div><p className="muted">Новый замер применяется к новым отправкам. Прошлые расчёты сохраняются.</p></>}
   {form.action==="pid"&&<><Field label="Номер ПИД" value={form.data.code} onChange={v=>change("code",v)}/><Field label="Дата начала учёта" type="date" value={form.data.cutoff} onChange={v=>change("cutoff",v)}/><Field label="Пройдено трассы до запуска, м" type="decimal" value={form.data.accumulatedTrench} onChange={v=>change("accumulatedTrench",v)}/></>}
   {form.action==="cable"&&<Field label="Название типа кабеля" value={form.data.name} onChange={v=>change("name",v)}/>}
   {form.action==="opening"&&<>
    <div className="notice">Состояние на начало {docs.find(d=>d.id===form.data.pid)?.data.cutoff||"даты начала учёта ПИД"}. Позднее можно уточнить измерения именно этого начального кабеля.</div>
    <section className="opening-section stack"><div><h3>Кабель на ПИД — ещё не отправлен на склад</h3><p className="muted">В поле и на временной площадке этого ПИД. Кабель в пути и уже принятый на склад сюда не входит.</p></div>
     <Field label="Весь извлечённый кабель на ПИД, м" type="decimal" value={form.data.metres} onChange={v=>change("metres",v)} hint="Общая длина: намотанный и ненамотанный кабель вместе. Это основной остаток в метрах."/>
     <div className="group-box"><div><h3>Из этого кабеля — уже намотано</h3><p className="muted">Метры и катушки описывают одну и ту же часть общего остатка.</p></div>
      <Field label="Катушки с кабелем, остающиеся на ПИД, шт." type="integer" value={form.data.coils} onChange={v=>change("coils",v)} hint="Готовые катушки с кабелем, не пустая тара. Количество дополняет метры, но не заменяет их."/>
      <WoundMeasurementFields docs={docs} pid={form.data.pid} cableId={form.data.cableId} count={form.data.coils} value={form.data.woundMeasurement} previous={docs.find(d=>d.id===form.id)?.data.woundMeasurement} onChange={v=>change("woundMeasurement",v)}/>
      <p className="muted">Длина в катушках уже входит во «Весь извлечённый кабель на ПИД». Повторно к остатку не прибавляется.</p>
     </div>
    </section>
    <section className="opening-section stack"><div><h3>Работы, выполненные до начала учёта</h3><p className="muted">Весь выполненный объём, независимо от того, где кабель сейчас: на ПИД, в пути или на складе. Эти показатели не задают складской остаток и не прибавляются к кабелю на ПИД.</p></div>
     <Field label="Всего извлечено до начала учёта, м" type="decimal" value={form.data.accumulatedExtracted} onChange={v=>change("accumulatedExtracted",v)}/>
     <Field label="Всего намотано до начала учёта, м" type="decimal" value={form.data.accumulatedWoundMetres} onChange={v=>change("accumulatedWoundMetres",v)} hint="Длина всего ранее намотанного кабеля, включая уже отправленный. Если ещё не определена — оставьте пустым."/>
     <Field label="Катушек намотано до начала учёта, шт." type="integer" value={form.data.accumulatedWound} onChange={v=>change("accumulatedWound",v)} hint="Общий объём намотки в катушках, включая уже отправленные. Дополнительный показатель производительности."/>
    </section>
   </>}
   {form.action==="user"&&<><Field label="Имя сотрудника" value={form.data.name} onChange={v=>change("name",v)}/><Field label="Telegram ID" value={form.data.telegramId} onChange={v=>change("telegramId",v)} hint="Числовой ID, не @имя"/><div className="stack compact">{Object.entries(roleNames).map(([key,name])=><label className="row" key={key}><Checkbox checked={form.data.roles.includes(key)} onCheckedChange={v=>change("roles",v?[...form.data.roles,key]:form.data.roles.filter((r:string)=>r!==key))}/>{name}</label>)}<label className="row"><Checkbox checked={form.data.active} onCheckedChange={v=>change("active",!!v)}/>Доступ включён</label></div></>}
   {form.action==="assignment"&&<><label className="field">Сотрудник<Picker value={form.data.userId} onChange={v=>change("userId",v)} options={users.map(u=>({value:u.id,label:u.data.name}))}/></label><label className="field">Роль на ПИД<Picker value={form.data.role} onChange={v=>change("role",v)} options={["foreman","winder","shipper"].map(r=>({value:r,label:roleNames[r as Role]}))}/></label><div className="field-grid"><Field label="С даты" type="date" value={form.data.from} onChange={v=>change("from",v)}/><Field label="По дату включительно" type="date" value={form.data.until} onChange={v=>change("until",v)} hint="Пусто — без срока"/></div></>}
  </>}
  {!review&&<p className="draft-note">Можно закрыть и продолжить позже. В учёт попадут только подтверждённые данные.</p>}
 </div><div className="bottom-actions"><button className="action secondary" disabled={busy||recording} onClick={()=>{if(review)setReview(false);else setForm(null);}}>{review?"Назад":"Закрыть"}</button><button className="action" disabled={busy||recording} onClick={review?submit:verify}>{busy?"Сохраняем…":review?<><Check/>Подтвердить</>:<>Проверить<ArrowUpRight/></>}</button></div>
 </>}
 </DialogContent></Dialog>
 <p className="footer-note">Время — Красноярск · Один ПИД, одна история движения{s?.demo?" · Проверочные данные не относятся к рабочему учёту":""}</p></main>;
}
function Metric({label,value,unit}:{label:string;value:string;unit:string}){return <article className="metric"><span>{label}</span><strong>{value} <small>{unit}</small></strong></article>;}
function WindingMetric({label,totals}:{label:string;totals:ReturnType<typeof windingTotals>}){return <article className="metric"><span>{label}</span><strong>{totals.unknownCoils&&totals.knownMm===0?"—":fmt(totals.knownMm,1000)} <small>{totals.unknownCoils?"м с указанной длиной":"м"}</small></strong><p className="muted">{totals.coils} катушек</p>{totals.unknownCoils>0&&<p className="measurement-note">У {totals.unknownCoils} катушек длина уточняется</p>}</article>;}
function WoundMeasurementFields({docs,pid,cableId,count,value,previous,onChange}:{docs:Doc[];pid:string;cableId:string;count:string;value:any;previous?:WoundMeasurement;onChange:(v:any)=>void}){
 const input=value??measurementInput(previous);let result:WoundMeasurement|undefined,error="";
 if(String(input.kg||"").trim())try{result=prepareWoundMeasurement(docs,pid,cableId,decimal(count,0),input,previous,new Date().toISOString());}catch(e){error=(e as Error).message;}
 return <div className="stack measurement-fields">
  <Field label="Измеренная длина кабеля в этих катушках, м" type="decimal" value={input.metres} onChange={v=>onChange({...input,metres:v})} hint="Основная единица — метры. Если длина ещё неизвестна, оставьте пустым: это «уточняется», а не ноль. Взвешивать для ввода количества катушек не требуется."/>
  <details className="measurement-details" open={String(input.kg||"").trim()?true:undefined}>
   <summary>Добавить вес и расчётную длину</summary>
   <div className="stack"><p className="muted">Взвесьте именно указанные здесь катушки целиком. Масса без тары и контрольный замер дадут дополнительную расчётную длину; измеренные метры сохранятся отдельно.</p>
    <Field label="Масса кабеля во всех этих катушках, кг" type="decimal" value={input.kg} onChange={v=>onChange({...input,kg:v})} hint="Если взвешена только часть катушек, не указывайте её массу как вес всей партии."/>
    <Field label="Дата взвешивания" type="date" value={input.weighedOn} onChange={v=>onChange({...input,weighedOn:v})}/>
    {error&&<p className="negative">{error}</p>}
    {result&&<div className="notice"><strong>Расчёт по весу: {fmt(result.calculatedMm!,1000)} м</strong><p>Контрольный отрезок: {fmt(result.coefficient!.sampleMm,1000)} м / {fmt(result.coefficient!.sampleGrams,1000)} кг.</p>{result.directMm!==null&&<p>Измерено отдельно: {fmt(result.directMm,1000)} м. Разница расчёта и измерения: {fmt(result.calculatedMm!-result.directMm,1000)} м. Исходное измерение не заменяется.</p>}</div>}
   </div>
  </details>
 </div>;
}
function MassPreview({value}:{value:string}){try{const weights=weightList(value);return <div><div className="num-chips">{weights.map((w,i)=><span key={i}>{fmt(w,1000)} кг</span>)}</div><p className="muted section-gap">{weights.length} катушек · {fmt(sum(weights),1000)} кг</p></div>;}catch{return value.trim()?<p className="negative">Проверьте список масс</p>:null;}}
function Review({form,docs,pidName,cableName}:{form:Editor;docs:Doc[];pidName:(id:string|null)=>string;cableName:(id:string)=>string}){
 const d=form.data;let lines:string[]=[];if(d.pid)lines.push(pidName(d.pid));if(d.date)lines.push(d.date);
 if(form.action==="report"){lines.push(statusText[d.status]);if(d.status==="work")lines.push(...(d.category==="excavation"?[cableName(d.cableId),"Трасса: "+d.trench+" м","Извлечено: "+d.cable+" м"]:d.lines.map((l:any)=>{const old=docs.find(x=>x.id===form.id)?.data.lines?.find((x:any)=>x.cableId===l.cableId)?.measurement;const m=l.measurement===undefined?old:prepareWoundMeasurement(docs,d.pid,l.cableId,decimal(l.count,0),l.measurement,old,new Date().toISOString());return cableName(l.cableId)+": "+l.count+" катушек. "+measurementText(m);})));if(d.note)lines.push(d.note);if(d.audioId)lines.push("Голосовое пояснение добавлено");}
 else if(form.action==="trip")for(const g of d.groups){const w=weightList(g.masses);lines.push(cableName(g.cableId)+": "+w.map(x=>fmt(x,1000)).join("; ")+" кг",w.length+" катушек · "+fmt(sum(w),1000)+" кг");}
 else if(form.action==="receipt"){const trip=docs.find(x=>x.id===form.id)!;const total=sum(Object.values(d.weights).map(x=>decimal(x)));lines.push("Принято "+trip.data.coils.length+" катушек",...trip.data.coils.map((c:any)=>"№ "+c.number+": "+d.weights[c.id]+" кг"),"Всего: "+fmt(total,1000)+" кг","Разница: "+fmt(total-sum(trip.data.coils.map((c:any)=>c.grams)),1000)+" кг");}
 else if(form.action==="adjustment"){const r=balances(docs.filter(x=>x.id!==form.id),d.date).find(x=>x.pid===d.pid&&x.cableId===d.cableId);lines.push(cableName(d.cableId));if(d.actualMetres!=="")lines.push("Метры: "+fmt(r?.mm||0,1000)+" → "+d.actualMetres+" м; поправка "+fmt(decimal(d.actualMetres)-(r?.mm||0),1000)+" м");if(d.actualCoils!=="")lines.push("Катушки: "+(r?.coils||0)+" → "+d.actualCoils+" шт.");lines.push(d.reason);}
 else if(form.action==="coefficient")lines.push(cableName(d.cableId),d.sampleMetres+" м / "+d.sampleKg+" кг",fmt(decimal(d.sampleKg)/decimal(d.sampleMetres))+" кг/м");
 else if(form.action==="user")lines.push(d.name,...d.roles.map((r:Role)=>roleNames[r]),d.active?"Доступ включён":"Доступ отключён");
 else if(form.action==="cable")lines.push(d.name);
 else if(form.action==="pid")lines.push("ПИД"+d.code,"Начало учёта: "+d.cutoff,"Пройдено ранее: "+d.accumulatedTrench+" м");
 else if(form.action==="opening"){
  const old=docs.find(x=>x.id===form.id)?.data;const m=d.woundMeasurement===undefined?old?.woundMeasurement:prepareWoundMeasurement(docs,d.pid,d.cableId,decimal(d.coils,0),d.woundMeasurement,old?.woundMeasurement,new Date().toISOString());
  lines.push(cableName(d.cableId),"На начало "+docs.find(x=>x.id===d.pid)?.data.cutoff,"В поле и на временной площадке ПИД, ещё не отправлено на склад: "+d.metres+" м всего.","Из этого кабеля: "+d.coils+" катушек. "+measurementText(m),"Работы до начала учёта, включая уже отправленный кабель:","Извлечено всего: "+d.accumulatedExtracted+" м","Намотано всего: "+(d.accumulatedWoundMetres?d.accumulatedWoundMetres+" м":"длина уточняется")+" · "+d.accumulatedWound+" катушек.","Работы до начала учёта и длина в катушках повторно не прибавляются к остатку на ПИД.");
  if(m?.calculatedMm!=null&&m.calculatedMm>decimal(d.metres))lines.push("Проверьте расхождение: расчётная длина в катушках превышает весь указанный кабель на ПИД. Общий остаток автоматически не изменяется.");
 }
 else if(form.action==="assignment")lines.push(docs.find(x=>x.id===d.userId)?.data.name||"",roleNames[d.role as Role],d.from+" — "+(d.until||"без срока"));
 return <div className="review">{lines.map((x,i)=><p key={i}>{x}</p>)}</div>;
}
function HistoryDetail({d,cableName}:{d:Doc;cableName:(id:string)=>string}){
 if(d.kind==="report")return <p>{statusText[d.data.status]}{d.data.status==="work"?(d.data.category==="excavation"?" · "+fmt(d.data.trenchMm,1000)+" / "+fmt(d.data.cableMm,1000)+" м · "+cableName(d.data.cableId):" · "+d.data.lines.map((l:any)=>cableName(l.cableId)+": "+l.count+" катушек. "+measurementText(l.measurement)).join("; ")):""}{d.data.note?" · "+d.data.note:""}</p>;
 if(d.kind==="trip")return <DataTable headers={["№ / тип","Отправлено, кг","Принято, кг"]}>{d.data.coils.map((c:any)=><TableRow key={c.id}><TableCell>{c.number} · {cableName(c.cableId)}</TableCell><TableCell>{fmt(c.grams,1000)}</TableCell><TableCell>{d.data.receipt?fmt(d.data.receipt.weights[c.id],1000):"В пути"}</TableCell></TableRow>)}</DataTable>;
 if(d.kind==="adjustment")return <p>{cableName(d.data.cableId)} · поправка {fmt(d.data.deltaMm,1000)} м / {d.data.deltaCoils} шт. · {d.data.reason}</p>;
 if(d.kind==="coefficient")return <p>{cableName(d.data.cableId)} · {fmt(d.data.sampleMm,1000)} м / {fmt(d.data.sampleGrams,1000)} кг</p>;
 if(d.kind==="opening")return <div className="stack compact"><p>{cableName(d.data.cableId)}. На начало {d.date} в поле и на временной площадке ПИД: {fmt(d.data.mm,1000)} м, ещё не отправлено на склад.</p><p>Из этого кабеля — {d.data.coils} катушек. {measurementText(d.data.woundMeasurement)}</p><p>Работы до начала учёта, независимо от текущего места кабеля: извлечено {fmt(d.data.accumulatedExtractedMm||0,1000)} м; намотано {d.data.accumulatedWoundMm==null?"длина уточняется":fmt(d.data.accumulatedWoundMm,1000)+" м"} · {d.data.accumulatedWound||0} катушек.</p></div>;
 if(d.kind==="user")return <p>{d.data.name} · {d.data.roles.map((r:Role)=>roleNames[r]).join(", ")}</p>;
 if(d.kind==="cable")return <p>{d.data.name}</p>;
 if(d.kind==="assignment")return <p>{roleNames[d.data.role as Role]} · {d.data.from} — {d.data.until||"без срока"}</p>;
 return null;
}

function ReceiptFields({coils,weights,cableName,onChange}:{coils:any[];weights:Record<string,string>;cableName:(id:string)=>string;onChange:(weights:Record<string,string>)=>void}){
 const inputs=useRef<Record<string,HTMLInputElement|null>>({});
 const measured=(id:string)=>{try{return decimal(weights[id])>0;}catch{return false;}};
 const count=coils.filter(c=>measured(c.id)).length;
 const total=sum(coils.map(c=>measured(c.id)?decimal(weights[c.id]):0));
 const jumpNext=()=>{const next=coils.find(c=>!measured(c.id));if(next){inputs.current[next.id]?.focus();inputs.current[next.id]?.scrollIntoView({block:"center",behavior:"smooth"});}};
 return <div className="stack receipt-fields">
  <div className="receipt-progress"><div className="row spread"><strong>Взвешено {count} из {coils.length}</strong><span>{fmt(total,1000)} кг</span></div><Progress value={coils.length?count/coils.length*100:0} aria-label="Взвешенные катушки"/><button className="action quiet" type="button" onClick={jumpNext} disabled={count===coils.length}>{count===coils.length?"Все катушки взвешены":"К следующей без веса"}{count===coils.length?<Check/>:<ChevronRight/>}</button></div>
  <p className="muted">Взвешивайте в любом порядке. Указывайте массу кабеля без тары.</p>
  {coils.map(c=><article className={"receipt-card"+(measured(c.id)?" measured":"")} key={c.id}>
   <div className="row spread"><div className="row"><span className="coil-number">{c.number}</span><div><h3>Катушка № {c.number}</h3><p className="muted">{cableName(c.cableId)}</p></div></div>{measured(c.id)&&<Check className="measured-icon" aria-label="Вес введён"/>}</div>
   <div className="receipt-weight"><div><span className="muted">Отправлено</span><strong>{fmt(c.grams,1000)} <small>кг</small></strong></div><label className="field">Принято, кг<input ref={el=>{inputs.current[c.id]=el;}} aria-label={"Принято, кг, катушка "+c.number} inputMode="decimal" enterKeyHint="next" placeholder="Введите вес" value={weights[c.id]||""} onChange={e=>onChange({...weights,[c.id]:e.target.value})} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();jumpNext();}}}/></label></div>
  </article>)}
 </div>;
}
