"use client";
import {useState,useEffect,useCallback,useRef} from "react";
import {Cable,ClipboardCheck,Truck,ArrowUpRight,Plus,Check,Download,History,Settings,Layers,CalendarDays,ArrowLeft,RefreshCw,Mic,Square,ChevronRight} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Checkbox} from "@/components/ui/checkbox";
import {Progress} from "@/components/ui/progress";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import {Toaster,toast} from "sonner";
import {type Doc,type Command,type Role,type WoundMeasurement,roleNames,today,weightList,decimal,summary,sum,balances,prepareCommand,woundLength,windingTotals,dispatchTotals} from "@/lib/domain";
import {prepareInitialization} from "@/lib/initialization";
import {InitializationFields,InitializationReview} from "./initialization-fields";
import {AdminOverview} from "./admin-overview";
import {useFormDraft} from "./use-form-draft";
type AppState={dataEpoch:string;draftScope:string;demo:boolean;actor:{id:string;name:string;roles:Role[]};date:string;docs:Doc[];balances:ReturnType<typeof balances>;summary:ReturnType<typeof summary>;expected:any[];reviewIds:string[]};
type Editor=Command&{title:string};
declare global {interface Window{Telegram?:{WebApp:any}}}
const fmt=(n:number,unit=1)=>new Intl.NumberFormat("ru-RU",{maximumFractionDigits:3}).format(n/unit);
const newId=()=>crypto.randomUUID();
const measurementText=(m?:WoundMeasurement)=>m?["Прежние измерения (сохранено):",m?.directMm==null?"Измеренная длина ещё не указана":"Измерено: "+fmt(m.directMm,1000)+" м",m?.grams!=null?"По весу: "+fmt(m.calculatedMm!,1000)+" м · "+fmt(m.grams,1000)+" кг без тары · взвешено "+m.weighedOn:"Вес ещё не указан"].join(". "):"Длина определяется по массе при отгрузке.";
const statusText:Record<string,string>={work:"Работа",dayoff:"Выходной",idle:"Простой"};
const kindText:Record<string,string>={report:"Суточный отчёт",trip:"Рейс",adjustment:"Корректировка",coefficient:"Контрольный замер",opening:"Прежний начальный остаток",initialization:"Начальные остатки",pid:"ПИД",user:"Сотрудник",assignment:"Закрепление",cable:"Тип кабеля",export:"Выгрузка"};
function Picker({value,onChange,options,label,disabled=false}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label?:string;disabled?:boolean}){return <Select value={value||undefined} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label||"Выбор"}><SelectValue placeholder="Выберите"/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
function Field({label,value,onChange,type="text",hint,required=false,readOnly=false}:{label:string;value:any;onChange:(v:string)=>void;type?:string;hint?:string;required?:boolean;readOnly?:boolean}){return <label className="field">{label}<input required={required} readOnly={readOnly} value={value??""} onChange={e=>onChange(e.target.value)} type={["decimal","integer"].includes(type)?"text":type} inputMode={type==="decimal"?"decimal":type==="integer"?"numeric":undefined}/>{hint&&<small>{hint}</small>}</label>;}
function DataTable({headers,children}:{headers:string[];children:React.ReactNode}){return <Table className="data-table"><TableHeader><TableRow>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{children}</TableBody></Table>;}
export default function CableApp(){
 const [s,setS]=useState<AppState|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState("today"),[date,setDate]=useState(()=>{if(typeof window!=="undefined"){const d=new URLSearchParams(window.location.search).get("date");if(d&&/^\d{4}-\d{2}-\d{2}$/.test(d))return d;}return today();}),[demoUser,setDemoUser]=useState("demo-admin"),[selectedPid,setSelectedPid]=useState(""),[review,setReview]=useState(false),[formError,setFormError]=useState(""),[log,setLog]=useState<any[]>([]),[exportFrom,setExportFrom]=useState(today().slice(0,8)+"01"),[exportTo,setExportTo]=useState(today()),[recording,setRecording]=useState(false);
 const {form,draft,storageUnavailable,open:openForm,setForm,close:closeForm,resume:resumeDraft,discard:discardDraft,submitted:formSubmitted,syncSession}=useFormDraft<Editor>();
 const [telegramReady,setTelegramReady]=useState(false);
 const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),initialized=useRef(false);
 const formScroll=useRef<HTMLDivElement|null>(null);
 const loadSequence=useRef(0),loadedSession=useRef("");
 useEffect(()=>{if(formError)formScroll.current?.scrollTo({top:0});},[formError]);
 const headers=useCallback(()=>({"Content-Type":"application/json","x-demo-user":demoUser,"x-telegram-init-data":window.Telegram?.WebApp?.initData||""}),[demoUser]);
 const api=useCallback(async(path:string,options:RequestInit={})=>{const r=await fetch(path,{...options,headers:{...headers(),...options.headers}});const data=await r.json();if(!r.ok)throw new Error(data.error||"Не удалось выполнить действие");return data;},[headers]);
 const load=useCallback(async()=>{const sequence=++loadSequence.current;try{const data:AppState=await api("/api/state?date="+date);if(sequence!==loadSequence.current)return;const sessionKey=data.draftScope+":"+data.actor.id+":"+data.dataEpoch;if(loadedSession.current&&loadedSession.current!==sessionKey){setLog([]);setSelectedPid("");setReview(false);setFormError("");}loadedSession.current=sessionKey;const {invalidated}=syncSession({actorId:data.actor.id,scope:data.draftScope,dataEpoch:data.dataEpoch});if(invalidated){setReview(false);setFormError("");toast.info("После обнуления учёта прежний черновик удалён");}setSelectedPid(pid=>data.docs.some(d=>d.id===pid&&d.kind==="pid")?pid:"");setS(data);setError("");}catch(e){if(sequence===loadSequence.current)setError((e as Error).message);}},[api,date,syncSession]);
 useEffect(()=>{
  let disposed=false;
  const ready=()=>{if(disposed)return;const app=window.Telegram?.WebApp;app?.ready();app?.expand();setTelegramReady(true);};
  if(window.Telegram?.WebApp){ready();return;}
  const script=document.createElement("script");script.src="https://telegram.org/js/telegram-web-app.js";script.async=true;script.onload=ready;script.onerror=ready;document.head.appendChild(script);
  const timeout=setTimeout(ready,8000);
  return()=>{disposed=true;clearTimeout(timeout);script.remove();};
 },[]);
 useEffect(()=>{if(telegramReady)void load();},[load,telegramReady]);
 useEffect(()=>{if(s&&!initialized.current){initialized.current=true;const p=new URLSearchParams(window.location.search);const pid=p.get("pid"),category=p.get("category"),requested=p.get("date");if(pid&&category&&s.docs.some(d=>d.id===pid)){openReport(pid,category,requested||date);}}},[s]);
 const docs=s?.docs||[],pids=docs.filter(d=>d.kind==="pid"),cables=docs.filter(d=>d.kind==="cable"),users=docs.filter(d=>d.kind==="user"),actor=s?.actor;
 const tripPids=pids.filter(p=>!p.data.initializationRequired||docs.some(d=>d.kind==="initialization"&&d.pid===p.id));
 const tripReason=!pids.length?"Для отправки сначала добавьте ПИД в «Управлении».":!cables.length?"Для отправки сначала добавьте тип кабеля в «Управлении».":!tripPids.length?"Для отправки сначала подтвердите начальные остатки ПИД.":"";
 const admin=actor?.roles.includes("admin"),has=(r:Role)=>admin||actor?.roles.includes(r);
 const pidName=(id:string|null)=>"ПИД"+(docs.find(d=>d.id===id)?.data.code||"?");
 const cableName=(id:string)=>docs.find(d=>d.id===id)?.data.name||"Тип не найден";
 const userName=(id:string)=>docs.find(d=>d.id===id)?.data.name||id;
 const pidOptions=pids.map(d=>({value:d.id,label:pidName(d.id)})),cableOptions=cables.map(d=>({value:d.id,label:d.data.name}));
 const edit=(title:string,action:string,data:any,old?:Doc)=>{openForm({title,action,data:old&&["report","trip","receipt"].includes(action)?{...data,reason:""}:data,id:old?.id,expectedVersion:old?.version,requestId:newId()});setReview(false);setFormError("");};
 const change=(key:string,value:any)=>{setForm(f=>f?{...f,requestId:newId(),data:{...f.data,[key]:value}}:null);setFormError("");};
 function openReport(pid:string,category:string,reportDate=date,old?:Doc){
  old=old||docs.find(d=>d.kind==="report"&&d.author===actor?.id&&d.pid===pid&&d.date===reportDate&&d.data.category===category);
  const prev=old||docs.filter(d=>d.kind==="report"&&d.author===actor?.id&&d.pid===pid&&d.data.category===category&&d.data.status==="work"&&d.date<=reportDate).sort((a,b)=>b.date.localeCompare(a.date))[0];
  edit(category==="excavation"?"Копка и извлечение":"Намотка","report",{pid,date:reportDate,category,status:old?.data.status||"work",cableId:old?.data.cableId||prev?.data.cableId||cables[0]?.id,trench:old?.data.trenchMm==null?"":String(old.data.trenchMm/1000),cable:old?.data.cableMm==null?"":String(old.data.cableMm/1000),lines:old?.data.lines?.map((l:any)=>({cableId:l.cableId,count:String(l.count)}))||prev?.data.lines?.map((l:any)=>({cableId:l.cableId,count:""}))||[{cableId:cables[0]?.id,count:""}],note:old?.data.note||"",audioId:old?.data.audioId||null},old);
 }
 function openTrip(old?:Doc){
  const groups:Record<string,string[]>={};for(const c of old?.data.coils||[])(groups[c.cableId]??=[]).push(String(c.grams/1000).replace(".",","));
  edit(old?"Исправление отправки":"Новая отправка","trip",{pid:old?.pid||tripPids.find(p=>p.id===selectedPid)?.id||tripPids[0]?.id,date:old?.date||date,groups:old?Object.entries(groups).map(([cableId,masses])=>({cableId,masses:masses.join(" ")})):[{cableId:cables[0]?.id,masses:""}]},old);
 }
 function openReceipt(trip:Doc){edit(trip.data.receipt?"Исправление приёмки":"Приёмка рейса","receipt",{date:trip.data.receipt?.date||date,weights:Object.fromEntries(trip.data.coils.map((c:any)=>[c.id,trip.data.receipt?.weights[c.id]?String(trip.data.receipt.weights[c.id]/1000):""]))},trip);}
 async function submit(){if(!form)return;setBusy(true);setFormError("");try{const {title,...cmd}=form;await api("/api/command",{method:"POST",body:JSON.stringify(cmd)});formSubmitted();setReview(false);toast.success("Сохранено");await load();}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 function verify(){
  if(!form)return;formScroll.current?.scrollTo({top:0});try{if(form.action==="initialize"){prepareInitialization(docs,actor!,form);setReview(true);setFormError("");return;}prepareCommand(docs,actor!,form);const d=form.data;
   if(form.action==="report"&&d.status==="work"){if(d.category==="excavation"){decimal(d.trench);decimal(d.cable);}else d.lines.forEach((l:any)=>decimal(l.count,0));}
   if(form.action==="trip")d.groups.forEach((g:any)=>weightList(g.masses));
   if(form.action==="receipt")Object.values(d.weights).forEach(w=>{if(decimal(w)<=0)throw new Error("Взвесьте все катушки");});
   setReview(true);setFormError("");
  }catch(e){setFormError((e as Error).message);}
 }
 async function getHistory(id?:string){const sessionKey=loadedSession.current;try{const r=await api("/api/history"+(id?"?id="+encodeURIComponent(id):""));if(sessionKey!==loadedSession.current)return;setLog(r.history);setTab("history");}catch(e){toast.error((e as Error).message);}}
 async function exportFile(){setBusy(true);try{const r=await fetch("/api/export",{method:"POST",headers:headers(),body:JSON.stringify({from:exportFrom,to:exportTo,requestId:newId()})});if(!r.ok){const d=await r.json();throw new Error(d.error);}const blob=await r.blob();const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="PID_"+exportFrom+"_"+exportTo+".xlsx";a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);toast.success("Файл сформирован. Загрузка в 1С не подтверждена.");await load();}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function audioUpload(blob:Blob){setBusy(true);try{const fd=new FormData();fd.append("file",blob,"idle.webm");const h:any=headers();delete h["Content-Type"];const r=await fetch("/api/audio",{method:"POST",headers:h,body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error);change("audioId",d.id);toast.success("Аудио добавлено");}catch(e){setFormError((e as Error).message);}finally{setBusy(false);}}
 async function toggleAudio(){if(recording){recorder.current?.stop();return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);recorder.current=r;chunks.current=[];r.ondataavailable=e=>chunks.current.push(e.data);r.onstop=()=>{stream.getTracks().forEach(t=>t.stop());setRecording(false);void audioUpload(new Blob(chunks.current,{type:r.mimeType}));};r.start();setRecording(true);}catch{setFormError("Микрофон недоступен. Можно прикрепить аудиофайл.");}}
 function renderReport(d:Doc){return <article className="task-card" key={d.id}><ClipboardCheck/><div><h3>{pidName(d.pid)} · {d.data.category==="excavation"?"Извлечение":"Намотка"}</h3><p>{userName(d.author)} · {d.date}</p><p>{d.data.status==="work"?(d.data.category==="excavation"?"Трасса: "+fmt(d.data.trenchMm,1000)+" м · извлечено: "+fmt(d.data.cableMm,1000)+" м · "+cableName(d.data.cableId):d.data.lines.map((l:any)=>cableName(l.cableId)+": "+l.count+" катушек"+(woundLength(l.measurement)==null?"":" · прежний замер "+fmt(woundLength(l.measurement)!,1000)+" м")).join("; ")):statusText[d.data.status]}</p>{d.data.source&&<p>Первичный документ: {d.data.source}</p>}{d.data.note&&<p>{d.data.note}</p>}</div><div className="stack compact">{d.author===actor?.id&&!d.data.initializationId&&<button className="action quiet" onClick={()=>openReport(d.pid!,d.data.category,d.date,d)}>Исправить</button>}<button className="action quiet" onClick={()=>getHistory(d.id)}>История</button></div></article>;}
 const formTrip=form?.id?docs.find(d=>d.id===form.id&&d.kind==="trip"):undefined;
 return <main className="workspace"><Toaster position="top-center" richColors/><header className="masthead"><div className="brand"><Cable/><span>ПИД<small>Учёт кабеля</small></span></div><div className="row">{s?.demo&&<span className="pill">Тестовые данные</span>}<button className="icon-button" aria-label="Обновить" onClick={()=>load()}><RefreshCw size={19}/></button></div></header>
 {s?.demo&&<div className="demo-toolbar"><span>Проверить как</span><Picker value={demoUser} onChange={v=>{loadSequence.current++;setS(null);setDemoUser(v);closeForm();setSelectedPid("");setTab("today");}} options={users.map(u=>({value:u.id,label:u.data.name+" · "+u.data.roles.map((r:Role)=>roleNames[r]).join(", ")}))} label="Проверочная роль"/></div>}
 {error&&<div className="notice error section-gap" role="alert">{error}<button className="action quiet" onClick={()=>load()}>Повторить</button></div>}
 {!s&&!error&&<div className="empty">Загружаем рабочий день…</div>}
 {s&&<Tabs value={tab} onValueChange={v=>{setTab(v);if(v==="history")void getHistory();}}>
 <TabsList className="tabs-bar" aria-label="Разделы приложения"><TabsTrigger value="today"><CalendarDays/><span>Сегодня</span></TabsTrigger><TabsTrigger value="pids"><Layers/><span>Все ПИД</span></TabsTrigger><TabsTrigger value="trips"><Truck/><span>Рейсы</span></TabsTrigger><TabsTrigger value="history"><History/><span>История</span></TabsTrigger>{admin&&<TabsTrigger value="admin" aria-label="Управление"><Settings/><span>Управ&shy;ление</span></TabsTrigger>}</TabsList>
 <TabsContent value="today">
  <section className="page-heading"><div><p className="eyebrow">{actor?.name}</p><h1>Рабочий день</h1><p className="muted">Копка, намотка и движение кабеля</p></div><label className="date-picker"><CalendarDays size={18}/><input aria-label="Дата отчётов" type="date" value={date} max={today()} onChange={e=>setDate(e.target.value)}/></label></section>
  <div className="metric-grid"><Metric label="Трасса за день" value={fmt(s.summary.trenchMm,1000)} unit="м"/><Metric label="Извлечено" value={fmt(s.summary.cableMm,1000)} unit="м"/><WindingMetric label="Намотано за день" totals={windingTotals(docs,date,undefined,true)}/></div>
  {draft&&!form&&<div className="notice section-gap draft-banner"><div><strong>Черновик: {draft.editor.title}{draft.editor.data.pid?" · "+pidName(draft.editor.data.pid):""}</strong><p className="draft-note">{new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"long",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Krasnoyarsk"}).format(new Date(draft.savedAt))} · на этом устройстве. Изменения ещё не подтверждены.</p></div><div className="draft-actions"><button className="action secondary" onClick={()=>{resumeDraft();setReview(false);setFormError("");}}>Продолжить</button><button className="action quiet" onClick={()=>{const result=discardDraft();if(result.persistent)toast.success("Черновик удалён");else toast.warning("Черновик убран с экрана. Хранилище устройства недоступно; после перезапуска он может появиться снова.");}}>Удалить черновик</button></div></div>}
  <div className="section-title"><h2>{admin||has("observer")?"Сдача отчётов":"Мои отчёты"}</h2><span className="muted">Запрос 19:00 · сводка 21:00</span></div>
  {s.expected.filter(x=>admin||has("observer")||x.userId===actor?.id).map((x:any)=>{const report=docs.find(d=>d.kind==="report"&&d.author===x.userId&&d.pid===x.pid&&d.date===date&&d.data.category===x.category);return <article className="task-card" key={x.userId+x.pid+x.category}><ClipboardCheck/><div><h3>{pidName(x.pid)} · {x.category==="excavation"?"Копка и извлечение":"Намотка"}</h3><p>{userName(x.userId)}</p></div>{x.userId===actor?.id?<button className="action" onClick={()=>openReport(x.pid,x.category)}>{report?"Открыть":"Заполнить"}</button>:<span className={"badge "+(report?"done":"pending")}>{report?statusText[report.data.status]:"Не сдан"}</span>}</article>;})}
  {!s.expected.length&&<div className="empty">На эту дату нет закреплений</div>}
  <div className="row section-gap">{has("shipper")&&<div className="management-action"><button className="action" disabled={!!tripReason} aria-describedby={tripReason?"trip-prerequisite":undefined} onClick={()=>openTrip()}><Plus/>Новая отправка</button>{tripReason&&<p id="trip-prerequisite" className="draft-note">{tripReason}</p>}</div>}{has("warehouse")&&<button className="action secondary" onClick={()=>setTab("trips")}><Truck/>Ожидающие рейсы</button>}</div>
  <div className="section-title"><h2>Подтверждённые отчёты</h2><span className="muted">{date}</span></div>
  {docs.filter(d=>d.kind==="report"&&d.date===date).map(renderReport)}
  {!docs.some(d=>d.kind==="report"&&d.date===date)&&<div className="empty panel">За этот день отчётов пока нет</div>}
 </TabsContent>
 <TabsContent value="pids">
  <section className="page-heading"><div><p className="eyebrow">МЕСТА ХРАНЕНИЯ</p><h1>{selectedPid?pidName(selectedPid):"Все ПИД"}</h1><p className="muted">На ПИД — метры · на основном складе — килограммы</p></div>{selectedPid&&<button className="action secondary" onClick={()=>setSelectedPid("")}><ArrowLeft/>Все ПИД</button>}</section>
  {!selectedPid?pids.map(p=>{const rows=s.balances.filter(b=>b.pid===p.id),trips=docs.filter(d=>d.kind==="trip"&&d.pid===p.id&&d.date<=date&&(!d.data.receipt||d.data.receipt.date>date)).length;return <button className="task-card pid-card" key={p.id} onClick={()=>setSelectedPid(p.id)}><Layers/><div><h3>{pidName(p.id)}</h3><p>{rows.length} типа · {trips} рейсов в пути</p></div><div className="pid-numbers"><strong className={sum(rows.map(r=>r.mm))<0?"negative":""}>{fmt(sum(rows.map(r=>r.mm)),1000)} м на ПИД</strong><span>{fmt(sum(rows.map(r=>r.warehouseGrams||0)),1000)} кг на складе</span></div><ChevronRight/></button>}):<>
   <div className="panel"><h2>Остатки на {date}</h2><DataTable headers={["Тип кабеля","На ПИД, м","На основном складе, кг"]}>{s.balances.filter(b=>b.pid===selectedPid).map(b=><TableRow key={b.cableId}><TableCell>{cableName(b.cableId)}</TableCell><TableCell className={b.mm<0?"negative":""}>{fmt(b.mm,1000)}</TableCell><TableCell className={b.warehouseGrams<0?"negative":""}>{fmt(b.warehouseGrams||0,1000)}</TableCell></TableRow>)}</DataTable><p className="footer-note">На ПИД: начальный остаток + извлечено − расчётная длина отправленного кабеля ± корректировки. На основном складе: начальная масса + фактически принято ± корректировки. Кабель в пути показан отдельно.</p></div>
   <div className="section-title"><h2>Работы и поступления</h2></div><div className="metric-grid production-grid"><Metric label="Пройдено трассы" value={fmt((docs.find(d=>d.id===selectedPid)?.data.accumulatedTrenchMm||0)+sum(docs.filter(d=>d.kind==="report"&&d.pid===selectedPid&&d.data.category==="excavation"&&d.data.status==="work"&&d.date<=date).map(d=>d.data.trenchMm)),1000)} unit="м"/><Metric label="Извлечено по отчётам" value={fmt(sum(s.balances.filter(b=>b.pid===selectedPid).map(b=>b.extractedMm)),1000)} unit="м"/><Metric label="Принято по рейсам" value={fmt(sum(s.balances.filter(b=>b.pid===selectedPid).map(b=>b.receivedGrams)),1000000)} unit="т за период учёта"/><WindingMetric label="Намотано по отчётам" totals={windingTotals(docs,date,selectedPid)} dispatch={dispatchTotals(docs,date,selectedPid)}/></div>
   <div className="section-title"><h2>Движение по типам</h2></div><div className="panel"><DataTable headers={["Тип","Отправлено, кг","В пути, кг","Разница при приёмке, кг"]}>{s.balances.filter(b=>b.pid===selectedPid).map(b=><TableRow key={b.cableId}><TableCell>{cableName(b.cableId)}</TableCell><TableCell>{fmt(b.sentGrams,1000)}</TableCell><TableCell>{fmt(b.transitGrams,1000)}</TableCell><TableCell>{fmt(b.differenceGrams,1000)}</TableCell></TableRow>)}</DataTable><p className="draft-note section-gap">Разница = принято − отправлено. Минус означает меньшую массу при приёмке. Причина расхождения требует проверки.</p></div>
   <div className="section-title"><h2>Катушки · вспомогательный учёт</h2></div><div className="panel"><DataTable headers={["Тип кабеля","Намотано","Отправлено","На ПИД"]}>{s.balances.filter(b=>b.pid===selectedPid).map(b=><TableRow key={b.cableId}><TableCell>{cableName(b.cableId)}</TableCell><TableCell>{b.wound}</TableCell><TableCell>{docs.filter(d=>d.kind==="trip"&&d.pid===selectedPid&&d.date<=date).reduce((n,d)=>n+d.data.coils.filter((c:any)=>c.cableId===b.cableId).length,0)}</TableCell><TableCell>{b.coils}</TableCell></TableRow>)}</DataTable><p className="draft-note section-gap">Намотка показывает работу сотрудников и дополняет сведения о кабеле. Она не меняет метры или килограммы. Отрицательное количество указывает на неполноту записей и не блокирует отправку.</p></div>
   <div className="section-title"><h2>Первичные отчёты</h2></div>{docs.filter(d=>d.kind==="report"&&d.pid===selectedPid).sort((a,b)=>b.date.localeCompare(a.date)).map(renderReport)}
  </>}
 </TabsContent>
 <TabsContent value="trips">
  <section className="page-heading"><div><p className="eyebrow">ДВИЖЕНИЕ КАБЕЛЯ</p><h1>Рейсы</h1><p className="muted">Одна отправка — один ПИД</p></div>{has("shipper")&&<button className="action" onClick={()=>openTrip()}><Plus/>Отправить</button>}</section>
   {docs.filter(d=>d.kind==="trip").sort((a,b)=>b.date.localeCompare(a.date)).map(t=><article className="panel section-gap" key={t.id}><div className="row spread"><div><h2>{pidName(t.pid)} <span className={"badge "+(t.data.receipt?"done":"pending")}>{t.data.receipt?"Принят":"В пути"}</span></h2><p className="muted">{t.date} · {userName(t.author)}</p></div><strong>{fmt(sum(t.data.coils.map((c:any)=>c.grams)),1000)} кг · {fmt(sum(t.data.coils.map((c:any)=>c.grams)),1000000)} т</strong></div><p className="section-gap">{t.data.coils.length} катушек · {[...new Set<string>(t.data.coils.map((c:any)=>c.cableId))].map(cableName).join(", ")}</p><p className="muted">С ПИД списано {fmt(sum(t.data.coils.map((c:any)=>c.sentMm)),1000)} м по массе и контрольному замеру.</p>
   {t.data.receipt&&<div className="notice section-gap">Принято {fmt(sum(Object.values(t.data.receipt.weights) as number[]),1000)} кг · разница {fmt(sum(Object.values(t.data.receipt.weights) as number[])-sum(t.data.coils.map((c:any)=>c.grams)),1000)} кг</div>}
   <div className="row section-gap">{has("warehouse")&&(!t.data.receipt||t.data.receipt.author===actor?.id)&&<button className="action" onClick={()=>openReceipt(t)}>{t.data.receipt?"Исправить приёмку":"Принять рейс"}</button>}{(t.author===actor?.id||admin)&&!t.data.initializationId&&<button className="action secondary" onClick={()=>openTrip(t)}>Исправить отправку</button>}<button className="action quiet" onClick={()=>getHistory(t.id)}>Ведомость и история</button></div>
  </article>)}
  {!docs.some(d=>d.kind==="trip")&&<div className="empty panel">Отправок пока нет</div>}
 </TabsContent>
 <TabsContent value="history">
  <section className="page-heading"><div><p className="eyebrow">ПЕРВИЧНЫЕ ДАННЫЕ</p><h1>История</h1><p className="muted">Авторы, версии и исходные ведомости</p></div><button className="action secondary" onClick={()=>getHistory()}><RefreshCw/>Все записи</button></section>
  <div className="panel">{log.filter(d=>!["audio"].includes(d.kind)).map(d=><article className="journal" key={d.id+":"+d.version}><div className="row spread"><strong>{kindText[d.kind]||d.kind}{d.pid?" · "+pidName(d.pid):""}</strong><span className="badge">Версия {d.version}</span></div><p className="muted">{d.date} · {userName(d.editor||d.author)} · {new Date(d.createdAt).toLocaleString("ru-RU",{timeZone:"Asia/Krasnoyarsk"})}</p>
   {d.data.source&&<p>Первичный документ: {d.data.source}</p>}<HistoryDetail d={d} cableName={cableName}/>{(d.data.correctionReason||d.data.reason)&&d.kind!=="adjustment"&&<p>Причина исправления: {d.data.correctionReason||d.data.reason}</p>}
   {d.kind==="report"&&d.data.audioId&&<button className="action quiet" onClick={async()=>{const r=await fetch("/api/audio?id="+d.data.audioId,{headers:headers()});if(!r.ok){toast.error("Аудио недоступно");return;}const url=URL.createObjectURL(await r.blob());const audio=new Audio(url);audio.onended=()=>URL.revokeObjectURL(url);await audio.play();}}>Прослушать пояснение</button>}
  </article>)}{!log.length&&<div className="empty">История пока пуста</div>}</div>
 </TabsContent>
 {admin&&<TabsContent value="admin">
  <AdminOverview docs={docs} reviewIds={s.reviewIds} onEdit={edit} onHistory={getHistory} exportPanel={<div className="panel stack"><p className="muted">Отправки, приёмки и исправления. Excel собственного формата.</p><div className="field-grid"><Field label="С" type="date" value={exportFrom} onChange={setExportFrom}/><Field label="По" type="date" value={exportTo} onChange={setExportTo}/></div><button className="action" disabled={busy} onClick={exportFile}><Download/>Выгрузить Excel</button><p className="draft-note">Изменения ранее выгруженных операций попадут в файл независимо от выбранного периода. Выгрузка не означает загрузку в 1С.</p>
   <h3>Последние выгрузки</h3>{docs.filter(d=>d.kind==="export").slice(-5).reverse().map(d=><p key={d.id} className="muted">{d.data.from} — {d.data.to}<br/>{d.data.importedAt?"Загружено в 1С":"Выгружено · загрузка не подтверждена"} {d.data.importedAt?null:<button className="action quiet" onClick={async()=>{try{await api("/api/export",{method:"PATCH",body:JSON.stringify({id:d.id,expectedVersion:d.version,requestId:newId()})});await load();}catch(e){toast.error((e as Error).message);}}}>Подтвердить загрузку в 1С</button>}</p>)}
</div>}/>
 </TabsContent>}
 </Tabs>}
  <Dialog open={!!form} onOpenChange={open=>{if(!open&&!busy&&!recording){closeForm();setReview(false);}}}><DialogContent className={"dialog-body"+(form?.action==="initialize"?" initial-dialog":"")} showCloseButton={false}><DialogHeader><span className="form-step">{review?"02 · Подтверждение":"01 · Ввод данных"}</span><DialogTitle>{review?"Проверьте данные":form?.title}</DialogTitle><DialogDescription>{form?.data.pid?pidName(form.data.pid)+" · ":formTrip?pidName(formTrip.pid)+" · ":""}{form?.data.date||"Данные сохранятся после подтверждения"}</DialogDescription></DialogHeader>
 {form&&<><div key={review?"review":"edit"} ref={formScroll} className="form-scroll stack">
  {formError&&<div className="notice error" role="alert">{formError}</div>}
   {review?(form.action==="initialize"?<InitializationReview docs={docs} actor={actor!} form={form}/>:<Review form={form} docs={docs} actor={actor!} pidName={pidName} cableName={cableName}/>):<>
   {form.action==="initialize"&&<InitializationFields docs={docs} data={form.data} onChange={data=>{setForm({...form,data,requestId:newId()});setFormError("");}}/>}
    {form.action==="opening"&&<div className="notice">Прежняя форма закрыта. В управлении доступен однократный ввод начальных остатков по двум местам хранения. Уже введённые остатки доступны в истории.</div>}
    {["trip","adjustment","coefficient","assignment"].includes(form.action)&&!(form.id&&["trip","opening","assignment"].includes(form.action))&&<label className="field">ПИД<Picker value={form.data.pid} onChange={v=>change("pid",v)} options={pidOptions} disabled={form.action==="adjustment"&&!!form.id}/></label>}
   {["report","trip","receipt","adjustment","coefficient"].includes(form.action)&&<Field label="Дата" value={form.data.date} type="date" readOnly={!!form.id&&["report","trip","adjustment"].includes(form.action)} onChange={v=>change("date",v)}/>}
   {form.action==="report"&&<>
    <Tabs value={form.data.status} onValueChange={v=>change("status",v)}><TabsList className="status-tabs"><TabsTrigger value="work">Работа</TabsTrigger><TabsTrigger value="dayoff">Выходной</TabsTrigger><TabsTrigger value="idle">Простой</TabsTrigger></TabsList></Tabs>
     {form.data.status==="work"&&form.data.category==="excavation"&&<><label className="field">Тип кабеля<Picker value={form.data.cableId} onChange={v=>change("cableId",v)} options={cableOptions}/></label><div className="field-grid report-quantities"><Field label="Пройдено трассы, м" type="decimal" value={form.data.trench} onChange={v=>change("trench",v)}/><Field label="Извлечено кабеля, м" type="decimal" value={form.data.cable} onChange={v=>change("cable",v)}/></div><p className="draft-note">На остаток ПИД поступит только извлечённый кабель. Оцените его длину отдельно: часть кабеля на пройденной трассе могла остаться в земле.</p></>}
    {form.data.status==="work"&&form.data.category==="winding"&&<><div className="notice">Укажите количество намотанных катушек. Длину на катушке напрямую не измеряют. При отгрузке по массе кабеля без тары будет рассчитана длина; она отразится в движении кабеля.</div>{form.data.lines.map((l:any,i:number)=><div className="group-box" key={i}><label className="field">Тип кабеля<Picker value={l.cableId} onChange={v=>change("lines",form.data.lines.map((x:any,j:number)=>j===i?{...x,cableId:v}:x))} options={cableOptions}/></label><Field label="Катушек намотано за день, шт." type="integer" value={l.count} onChange={v=>change("lines",form.data.lines.map((x:any,j:number)=>j===i?{...x,count:v}:x))}/>{form.data.lines.length>1&&<button className="action quiet" onClick={()=>change("lines",form.data.lines.filter((_:any,j:number)=>j!==i))}>Убрать строку</button>}</div>)}<button className="action secondary" onClick={()=>change("lines",[...form.data.lines,{cableId:cables.find(c=>!form.data.lines.some((l:any)=>l.cableId===c.id))?.id||cables[0]?.id,count:""}])}><Plus/>Ещё тип</button></>}
    {form.data.status==="idle"&&<><label className="field">Пояснение — необязательно<textarea value={form.data.note} onChange={e=>change("note",e.target.value)} placeholder="Причина простоя"/></label><div className="row"><button className="action secondary" onClick={toggleAudio} disabled={busy}>{recording?<Square/>:<Mic/>}{recording?"Остановить":"Записать голосом"}</button><label className="action secondary">Аудиофайл<input type="file" accept="audio/*" className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(f)void audioUpload(f);}}/></label></div>{form.data.audioId&&<span className="badge done">Аудио добавлено</span>}</>}
   </>}
    {form.action==="trip"&&<><div className="notice">Введите результат взвешивания каждой катушки при погрузке. Масса кабеля — без тары. Общая масса и число катушек считаются автоматически.</div>{form.data.groups.map((g:any,i:number)=><div className="group-box" key={i}><label className="field">Тип кабеля<Picker value={g.cableId} onChange={v=>change("groups",form.data.groups.map((x:any,j:number)=>j===i?{...x,cableId:v}:x))} options={cableOptions}/></label><label className="field">Масса кабеля в каждой катушке, кг<textarea inputMode="decimal" placeholder="801 803 806 900" value={g.masses} onChange={e=>change("groups",form.data.groups.map((x:any,j:number)=>j===i?{...x,masses:e.target.value}:x))}/><small>Одно число — одна катушка. Разделяйте числа пробелом или новой строкой, дробную часть — запятой.</small></label><MassPreview value={g.masses}/>{form.data.groups.length>1&&<button className="action quiet" onClick={()=>change("groups",form.data.groups.filter((_:any,j:number)=>j!==i))}>Убрать тип</button>}</div>)}<button className="action secondary" onClick={()=>change("groups",[...form.data.groups,{cableId:cables.find(c=>!form.data.groups.some((g:any)=>g.cableId===c.id))?.id||cables[0]?.id,masses:""}])}><Plus/>Добавить тип</button><TripPreview form={form} docs={docs} actor={actor!}/></>}
   {form.action==="receipt"&&formTrip&&<ReceiptFields coils={formTrip.data.coils} weights={form.data.weights} cableName={cableName} onChange={weights=>change("weights",weights)}/>}
    {["adjustment","coefficient"].includes(form.action)&&<label className="field">Тип кабеля<Picker value={form.data.cableId} onChange={v=>change("cableId",v)} options={cableOptions} disabled={form.action==="adjustment"&&!!form.id}/></label>}
    {form.action==="adjustment"&&<><label className="field">Где проверили остаток<Picker disabled={!!form.id} value={form.data.location||"pid"} onChange={location=>setForm({...form,requestId:newId(),data:{...form.data,location,actualMetres:"",actualKg:"",actualCoils:""}})} options={[{value:"pid",label:"На ПИД · поле и временная площадка"},{value:"warehouse",label:"На основном складе"}]}/></label><div className="notice">{form.data.location==="warehouse"?"Введите проверенную массу кабеля с выбранного ПИД на основном складе. Поправка изменит только складской остаток в килограммах.":"Введите проверенный остаток кабеля в поле и на временной площадке этого ПИД. Кабель в пути и на основном складе сюда не включайте."}</div>{form.data.location==="warehouse"?<Field label="Фактическая масса кабеля без тары, кг" value={form.data.actualKg} onChange={v=>change("actualKg",v)} type="decimal"/>:<><Field label="Проверенная оценка длины остатка, м" value={form.data.actualMetres} onChange={v=>change("actualMetres",v)} type="decimal" hint="Оставьте пустым, если проверяли только катушки"/><details className="measurement-details"><summary>Дополнительно: проверка количества катушек</summary><div><Field label="Катушек на ПИД, шт." value={form.data.actualCoils} onChange={v=>change("actualCoils",v)} type="integer" hint="Необязательно. Исправляет только вспомогательный учёт катушек."/></div></details></>}<label className="field">Основание корректировки<textarea value={form.data.reason} onChange={e=>change("reason",e.target.value)} placeholder="Что проверено и почему отличается остаток"/></label></>}
   {form.action==="coefficient"&&<><div className="field-grid"><Field label="Длина отрезка, м" value={form.data.sampleMetres} type="decimal" onChange={v=>change("sampleMetres",v)}/><Field label="Масса отрезка, кг" value={form.data.sampleKg} type="decimal" onChange={v=>change("sampleKg",v)}/></div><p className="muted">Новый замер применяется к новым отправкам. Прошлые расчёты сохраняются.</p></>}
    {form.action==="pid"&&<><Field label="Номер ПИД" value={form.data.code} onChange={v=>change("code",v)}/><Field label="Дата начала учёта" type="date" value={form.data.cutoff} onChange={v=>change("cutoff",v)}/><p className="muted">После создания ПИД однократно введите остатки на начало этой даты: на ПИД в метрах, на основном складе в килограммах. Отсутствие остатков подтвердите отдельно для каждого места.</p></>}
   {form.action==="cable"&&<Field label="Название типа кабеля" value={form.data.name} onChange={v=>change("name",v)}/>}
   {form.action==="user"&&<><Field label="Имя сотрудника" value={form.data.name} onChange={v=>change("name",v)}/><Field label="Telegram ID" value={form.data.telegramId} onChange={v=>change("telegramId",v)} hint="Числовой ID, не @имя"/><div className="stack compact">{Object.entries(roleNames).map(([key,name])=><label className="row" key={key}><Checkbox checked={form.data.roles.includes(key)} onCheckedChange={v=>change("roles",v?[...form.data.roles,key]:form.data.roles.filter((r:string)=>r!==key))}/>{name}</label>)}<label className="row"><Checkbox checked={form.data.active} onCheckedChange={v=>change("active",!!v)}/>Доступ включён</label></div></>}
   {form.action==="assignment"&&<>{!!form.id&&<p className="notice">У сохранённого закрепления можно изменить дату окончания. Для другого ПИД, сотрудника или роли создайте новое закрепление.</p>}<label className="field">Сотрудник<Picker disabled={!!form.id} value={form.data.userId} onChange={v=>{const roles=users.find(u=>u.id===v)?.data.roles||[];setForm({...form,requestId:newId(),data:{...form.data,userId:v,role:roles.includes(form.data.role)?form.data.role:["foreman","winder","shipper"].find(r=>roles.includes(r))}});setFormError("");}} options={users.filter(u=>u.id===form.data.userId||(u.data.active!==false&&["foreman","winder","shipper"].some(r=>u.data.roles.includes(r)))).map(u=>({value:u.id,label:u.data.name}))}/></label><label className="field">Роль на ПИД<Picker disabled={!!form.id} value={form.data.role} onChange={v=>change("role",v)} options={["foreman","winder","shipper"].filter(r=>r===form.data.role||users.find(u=>u.id===form.data.userId)?.data.roles.includes(r)).map(r=>({value:r,label:roleNames[r as Role]}))}/></label><div className="field-grid"><Field label="С даты" type="date" readOnly={!!form.id} value={form.data.from} onChange={v=>change("from",v)}/><Field label="По дату включительно" type="date" value={form.data.until} onChange={v=>change("until",v)} hint="Пусто — без срока"/></div></>}
    {form.id&&(["report","trip"].includes(form.action)||(form.action==="receipt"&&formTrip?.data.receipt))&&<label className="field">Причина исправления<textarea value={form.data.reason||""} onChange={e=>change("reason",e.target.value)} placeholder="Что изменилось и на каком основании"/><small>Предыдущая версия и причина сохранятся в истории.</small></label>}
   </>}
  {!review&&<p className="draft-note">{storageUnavailable?"Черновик не сохраняется на этом устройстве. Не закрывайте приложение до подтверждения данных.":"Изменённая форма сохраняется как черновик на этом устройстве. В учёт попадут только подтверждённые данные."}</p>}
 </div><div className="bottom-actions"><button className="action secondary" disabled={busy||recording} onClick={()=>{if(review)setReview(false);else closeForm();}}>{review?"Назад":"Закрыть"}</button><button className="action" disabled={busy||recording} onClick={review?submit:verify}>{busy?"Сохраняем…":review?<><Check/>Подтвердить</>:<>Проверить<ArrowUpRight/></>}</button></div>
 </>}
 </DialogContent></Dialog>
 <p className="footer-note">Время — Красноярск · Один ПИД, одна история движения{s?.demo?" · Проверочные данные не относятся к рабочему учёту":""}</p></main>;
}
function Metric({label,value,unit}:{label:string;value:string;unit:string}){return <article className="metric"><span>{label}</span><strong>{value} <small>{unit}</small></strong></article>;}
function WindingMetric({label,totals,dispatch}:{label:string;totals:ReturnType<typeof windingTotals>;dispatch?:ReturnType<typeof dispatchTotals>}){return <article className="metric"><span>{label}</span><strong>{totals.coils} <small>катушек</small></strong><p className="measurement-note">Показатель работы намотчиков. Остаток кабеля не меняет.</p>{dispatch&&<p className="measurement-note">Отправлено по рейсам: {dispatch.coils} катушек.</p>}</article>;}
function MassPreview({value}:{value:string}){try{const weights=weightList(value);return <div><div className="num-chips">{weights.map((w,i)=><span key={i}>№ {i+1}: {fmt(w,1000)} кг</span>)}</div><p className="muted section-gap">{weights.length} катушек · {fmt(sum(weights),1000)} кг · {fmt(sum(weights),1000000)} т</p></div>;}catch{return value.trim()?<p className="negative">Проверьте список масс</p>:null;}}
function TripPreview({form,docs,actor}:{form:Editor;docs:Doc[];actor:AppState["actor"]}){
 try{const prepared=prepareCommand(docs,actor,form),coils=prepared.data.coils,total=sum(coils.map((c:any)=>c.grams));return <div className="notice"><strong>Всего отправляется: {fmt(total,1000)} кг · {fmt(total,1000000)} т</strong><p>{coils.length} катушек. Расчётная длина к списанию с ПИД: {fmt(sum(coils.map((c:any)=>c.sentMm)),1000)} м.</p><p className="draft-note">Длина рассчитана по массе каждой катушки и контрольному замеру для её типа кабеля.</p></div>;}catch{return null;}
}
function Review({form,docs,actor,pidName,cableName}:{form:Editor;docs:Doc[];actor:AppState["actor"];pidName:(id:string|null)=>string;cableName:(id:string)=>string}){
 const d=form.data;let lines:string[]=[];if(d.pid)lines.push(pidName(d.pid));if(d.date)lines.push(d.date);
 if(form.action==="report"){lines.push(statusText[d.status]);if(d.status==="work")lines.push(...(d.category==="excavation"?[cableName(d.cableId),"Трасса: "+d.trench+" м","Извлечено: "+d.cable+" м"]:d.lines.map((l:any)=>cableName(l.cableId)+": "+l.count+" катушек. Длина будет рассчитана по массе при отгрузке.")));if(d.note)lines.push(d.note);if(d.audioId)lines.push("Голосовое пояснение добавлено");}
  else if(form.action==="trip"){const prepared=prepareCommand(docs,actor,form);for(const g of d.groups){const w=weightList(g.masses),mm=sum(prepared.data.coils.filter((c:any)=>c.cableId===g.cableId).map((c:any)=>c.sentMm));lines.push(cableName(g.cableId)+": "+w.map(x=>fmt(x,1000)).join("; ")+" кг",w.length+" катушек · "+fmt(sum(w),1000)+" кг · "+fmt(sum(w),1000000)+" т","Списать с ПИД по массе: "+fmt(mm,1000)+" м");}lines.push("Всего к отправке: "+fmt(sum(prepared.data.coils.map((c:any)=>c.grams)),1000)+" кг. На основной склад кабель поступит после отдельной приёмки.");}
  else if(form.action==="receipt"){const trip=docs.find(x=>x.id===form.id)!;const total=sum(Object.values(d.weights).map(x=>decimal(x)));lines.push("Результаты складского взвешивания",...trip.data.coils.map((c:any)=>"№ "+c.number+": "+d.weights[c.id]+" кг"),"Поступит на основной склад: "+fmt(total,1000)+" кг · "+fmt(total,1000000)+" т","При погрузке: "+fmt(sum(trip.data.coils.map((c:any)=>c.grams)),1000)+" кг","Разница (принято − отправлено): "+fmt(total-sum(trip.data.coils.map((c:any)=>c.grams)),1000)+" кг","Измерения при погрузке сохранятся. Разница фиксируется отдельно для проверки.");}
  else if(form.action==="adjustment"){const r=balances(docs.filter(x=>x.id!==form.id),d.date).find(x=>x.pid===d.pid&&x.cableId===d.cableId);lines.push(cableName(d.cableId),d.location==="warehouse"?"Основной склад":"На ПИД · поле и временная площадка");if(d.location==="warehouse")lines.push("Масса: "+fmt(r?.warehouseGrams||0,1000)+" → "+d.actualKg+" кг; поправка "+fmt(decimal(d.actualKg)-(r?.warehouseGrams||0),1000)+" кг");else{if(d.actualMetres!==""&&d.actualMetres!=null)lines.push("Метры: "+fmt(r?.mm||0,1000)+" → "+d.actualMetres+" м; поправка "+fmt(decimal(d.actualMetres)-(r?.mm||0),1000)+" м");if(d.actualCoils!==""&&d.actualCoils!=null)lines.push("Катушки (вспомогательный учёт): "+(r?.coils||0)+" → "+d.actualCoils+" шт.");}lines.push(d.reason);}
 else if(form.action==="coefficient")lines.push(cableName(d.cableId),d.sampleMetres+" м / "+d.sampleKg+" кг",fmt(decimal(d.sampleKg)/decimal(d.sampleMetres))+" кг/м");
 else if(form.action==="user")lines.push(d.name,...d.roles.map((r:Role)=>roleNames[r]),d.active?"Доступ включён":"Доступ отключён");
 else if(form.action==="cable")lines.push(d.name);
  else if(form.action==="pid")lines.push("ПИД"+d.code,"Начало учёта: "+d.cutoff,"Далее — однократный ввод начальных остатков на ПИД в метрах и на основном складе в килограммах.");
 else if(form.action==="assignment")lines.push(docs.find(x=>x.id===d.userId)?.data.name||"",roleNames[d.role as Role],d.from+" — "+(d.until||"без срока"));
  if(d.reason&&form.action!=="adjustment")lines.push("Причина исправления: "+d.reason);
  return <div className="review">{lines.map((x,i)=><p key={i}>{x}</p>)}</div>;
}
function HistoryDetail({d,cableName}:{d:Doc;cableName:(id:string)=>string}){
  if(d.kind==="initialization")return d.data.schemaVersion===2?<div className="stack compact"><p>Начальные остатки подтверждены один раз на начало {d.date}.</p>{d.data.lines.map((line:any)=><p key={line.id}>{cableName(line.cableId)} · {line.location==="pid"?"На ПИД: "+fmt(line.mm,1000)+" м (оценка)":"На основном складе: "+fmt(line.grams,1000)+" кг без тары"}</p>)}{!d.data.lines.length&&<p>Остатки в обоих местах подтверждены нулевыми.</p>}</div>:<p>Первоначальный перенос из прежней версии: {d.data.entryCount||0} записей. Начало учёта: {d.data.cutoff||d.date}.</p>;
 if(d.kind==="report")return <p>{statusText[d.data.status]}{d.data.status==="work"?(d.data.category==="excavation"?" · "+fmt(d.data.trenchMm,1000)+" / "+fmt(d.data.cableMm,1000)+" м · "+cableName(d.data.cableId):" · "+d.data.lines.map((l:any)=>cableName(l.cableId)+": "+l.count+" катушек. "+measurementText(l.measurement)).join("; ")):""}{d.data.note?" · "+d.data.note:""}</p>;
 if(d.kind==="trip")return <DataTable headers={["№ / тип","Отправлено, кг","Принято, кг"]}>{d.data.coils.map((c:any)=><TableRow key={c.id}><TableCell>{c.number} · {cableName(c.cableId)}</TableCell><TableCell>{fmt(c.grams,1000)}</TableCell><TableCell>{d.data.receipt?fmt(d.data.receipt.weights[c.id],1000):"В пути"}</TableCell></TableRow>)}</DataTable>;
  if(d.kind==="adjustment")return <p>{cableName(d.data.cableId)} · {d.data.location==="warehouse"?"Основной склад: поправка "+fmt(d.data.deltaGrams||0,1000)+" кг":"На ПИД: поправка "+fmt(d.data.deltaMm||0,1000)+" м"}{d.data.deltaCoils?" · катушки: "+d.data.deltaCoils+" шт.":""} · {d.data.reason}</p>;
 if(d.kind==="coefficient")return <p>{cableName(d.data.cableId)} · {fmt(d.data.sampleMm,1000)} м / {fmt(d.data.sampleGrams,1000)} кг</p>;
 if(d.kind==="opening")return <div className="stack compact"><p>{cableName(d.data.cableId)}. На начало {d.date} в поле и на временной площадке ПИД: {fmt(d.data.mm,1000)} м, ещё не отправлено на склад.</p><p>Из этого кабеля — {d.data.coils} катушек. {measurementText(d.data.woundMeasurement)}</p><p>Работы до начала учёта, независимо от текущего места кабеля: извлечено {fmt(d.data.accumulatedExtractedMm||0,1000)} м; намотано {d.data.accumulatedWoundMm==null?"длина уточняется":fmt(d.data.accumulatedWoundMm,1000)+" м"} · {d.data.accumulatedWound||0} катушек.</p></div>;
 if(d.kind==="user")return <p>{d.data.name} · {d.data.roles.map((r:Role)=>roleNames[r]).join(", ")}</p>;
 if(d.kind==="cable")return <p>{d.data.name}</p>;
 if(d.kind==="assignment")return <p>{roleNames[d.data.role as Role]} · {d.data.from} — {d.data.until||"без срока"}</p>;
 return null;
}

function ReceiptFields({coils,weights,cableName,onChange}:{coils:any[];weights:Record<string,string>;cableName:(id:string)=>string;onChange:(weights:Record<string,string>)=>void}){
 const inputs=useRef<Record<string,HTMLInputElement|null>>({});
 const measured=(id:string)=>{try{return decimal(weights[id])>0;}catch{return false;}};
 const count=coils.filter(c=>measured(c.id)).length;
 const total=sum(coils.map(c=>measured(c.id)?decimal(weights[c.id]):0));
 const jumpNext=()=>{const next=coils.find(c=>!measured(c.id));if(next){inputs.current[next.id]?.focus();inputs.current[next.id]?.scrollIntoView({block:"center",behavior:"smooth"});}};
 return <div className="stack receipt-fields">
   <div className="receipt-progress"><div className="row spread"><strong>Взвешено {count} из {coils.length}</strong><span>{fmt(total,1000)} кг · {fmt(total,1000000)} т</span></div><Progress value={coils.length?count/coils.length*100:0} aria-label="Взвешенные катушки"/><button className="action quiet" type="button" onClick={jumpNext} disabled={count===coils.length}>{count===coils.length?"Все катушки взвешены":"К следующей без веса"}{count===coils.length?<Check/>:<ChevronRight/>}</button></div>
   <p className="muted">Указывайте новое фактическое взвешивание на складе: только кабель, без тары. Не копируйте отправленные массы вместо измерения.</p>
  {coils.map(c=><article className={"receipt-card"+(measured(c.id)?" measured":"")} key={c.id}>
   <div className="row spread"><div className="row"><span className="coil-number">{c.number}</span><div><h3>Катушка № {c.number}</h3><p className="muted">{cableName(c.cableId)}</p></div></div>{measured(c.id)&&<Check className="measured-icon" aria-label="Вес введён"/>}</div>
   <div className="receipt-weight"><div><span className="muted">Отправлено</span><strong>{fmt(c.grams,1000)} <small>кг</small></strong></div><label className="field">Принято, кг<input ref={el=>{inputs.current[c.id]=el;}} aria-label={"Принято, кг, катушка "+c.number} inputMode="decimal" enterKeyHint="next" placeholder="Введите вес" value={weights[c.id]||""} onChange={e=>onChange({...weights,[c.id]:e.target.value})} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();jumpNext();}}}/></label></div>
  </article>)}
 </div>;
}
