'use client';
import {useEffect,useState,useRef} from 'react';
import {ClipboardCheck,ChartNoAxesCombined,Files,Settings2,ArrowLeft,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Update} from '@/components/concise-work';
import {DailyWorkPanel,DailyForm} from '@/components/daily-work';
import {documents as dailyDocuments,type DailySubmission} from '@/lib/daily-work';
import {StatsPanel,DocFilter} from '@/components/concise-stats';
import {SettingsWorkspace} from '@/components/settings-workspace';
import {DocumentList,DocumentDetail,TransferForm} from '@/components/concise-documents';
import {ExclusionForm} from '@/components/concise-pid';
import type {State} from '@/lib/concise-model';
import {changes} from '@/lib/production-domain';
import './production.css';
type Data={payload:State;revision:number;user:{employee:string;name:string;admin:boolean}};
type View='work'|'stats'|'documents'|'settings';
type Detail={kind:'daily';id:string}|{kind:'document';id:string}|{kind:'transfer';id?:string}|{kind:'exclusion'}|null;
export default function OperationalApp({web=false}:{web?:boolean}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[pane,setPane]=useState<View>(web?'stats':'work'),[detail,setDetail]=useState<Detail>(null),[filter,setFilter]=useState<DocFilter>(),[code,setCode]=useState(''),[approveCode,setApproveCode]=useState(''),[loginOpen,setLoginOpen]=useState(false),[loginStatus,setLoginStatus]=useState('');
 const lock=useRef(false),ref=useRef<Data|null>(null),retry=useRef<{signature:string;requestId:string}|null>(null);
 async function api(path:string,body?:unknown){const response=await fetch(path,{method:body?'POST':'GET',credentials:'same-origin',headers:{...(body?{'Content-Type':'application/json'}:{}),'x-telegram-init-data':window.Telegram?.WebApp.initData||''},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw Object.assign(Error(result.error||'Не удалось сохранить данные.'),{status:response.status});return result;}
 const accept=(d:Data)=>{ref.current=d;setData(d);setError('');};
 async function refresh(){try{accept(await api('/api/operational'));}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{const script=document.createElement('script');script.src='https://telegram.org/js/telegram-web-app.js';script.onload=()=>{window.Telegram?.WebApp.ready();window.Telegram?.WebApp.expand();void refresh()};script.onerror=()=>void refresh();document.head.appendChild(script);return()=>script.remove()},[]);
 useEffect(()=>{if(!code||data)return;const timer=setInterval(async()=>{try{const r=await api('/api/operational/auth',{action:'finish'});if(r.ok){setCode('');await refresh();}}catch(e){setError((e as Error).message);setCode('')}},2500);return()=>clearInterval(timer)},[code,!!data]);
 useEffect(()=>{if(!data)return;const t=setInterval(()=>{if(!lock.current)void refresh()},30000);return()=>clearInterval(t)},[!!data]);
 const update:Update=async f=>{if(lock.current)throw Error('Предыдущая операция ещё сохраняется.');const current=ref.current;if(!current)throw Error('Войдите в приложение.');const patches=changes(current.payload,f(current.payload));if(!patches.length)return;const signature=JSON.stringify(patches),requestId=retry.current?.signature===signature?retry.current.requestId:crypto.randomUUID();retry.current={signature,requestId};lock.current=true;setBusy(true);try{accept(await api('/api/operational',{revision:current.revision,requestId,patches}));retry.current=null;}catch(e){setError((e as Error).message);throw e;}finally{lock.current=false;setBusy(false)}};
 const submitDaily=async(v:DailySubmission)=>{if(lock.current)throw Error('Предыдущая операция ещё сохраняется.');const current=ref.current;if(!current)throw Error('Войдите в приложение.');const patches=[{key:'dailySubmission',rows:[v]}],signature=JSON.stringify(patches),requestId=retry.current?.signature===signature?retry.current.requestId:crypto.randomUUID();retry.current={signature,requestId};lock.current=true;setBusy(true);try{accept(await api('/api/operational',{revision:current.revision,requestId,patches}));retry.current=null;}catch(e){setError((e as Error).message);throw e;}finally{lock.current=false;setBusy(false)}};
 const navTo=(p:View)=>{setPane(p);setDetail(null);if(p==='documents')setFilter(undefined);window.scrollTo(0,0)};
 if(loading)return <main className="c-review production"><p className="c-empty">Загружаем рабочие данные…</p></main>;
 if(!data)return <main className="c-review production tg"><section className="c-card c-form" style={{margin:24}}><h1>Учёт кабеля</h1><p>Вход в рабочий кабинет</p>{error&&<p className="c-error">{error}</p>}{code?<><b style={{fontSize:32,letterSpacing:4}}>{code}</b><p>Откройте «Учёт» в Telegram → «Вход в WEB» и введите эти восемь цифр. Код действует пять минут.</p><p className="c-help">Подтверждайте только вход на своём компьютере.</p></>:<Button onClick={async()=>{try{const r=await api('/api/operational/auth',{action:'start'});setCode(r.code);setError('')}catch(e){setError((e as Error).message)}}}>Войти через Telegram</Button>}<a href="https://t.me/rsskablebot" target="_blank" rel="noreferrer">Открыть бота</a><Button variant="outline" onClick={()=>void refresh()}>Повторить загрузку</Button></section></main>;
 const s=data.payload,actor=data.user.admin?'admin':data.user.employee;
 const docDay=detail?.kind==='document'?s.dailyTasks?.find(t=>!t.restored&&dailyDocuments(s,t).some(d=>d.id===detail.id)):undefined;
 const editingDay=detail?.kind==='daily'?s.dailyTasks?.find(t=>t.id===detail.id):undefined;
 const nav=<nav className="c-main-nav">{([['work','Моя работа',ClipboardCheck],['stats','Показатели',ChartNoAxesCombined],['documents','Документы',Files]] as const).map(([key,label,Icon])=><button key={key} aria-current={pane===key?'page':undefined} onClick={()=>navTo(key)}><Icon size={20}/>{label}</button>)}</nav>;
 return <main className={'c-review production '+(web?'web':'tg')}><section className="c-app"><header className="c-app-header"><div className="c-avatar">{data.user.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><b>{data.user.name}</b><span>Учёт кабеля · {s.today}</span></div><button onClick={()=>void refresh()} aria-label="Обновить"><RefreshCw size={20}/></button>{web&&data.user.admin&&<button className="c-settings-button" onClick={()=>navTo('settings')}><Settings2 size={20}/>Настройки</button>}<button className="c-text-button" onClick={()=>setLoginOpen(!loginOpen)}>{web?'Сеанс':'Вход в WEB'}</button></header>{web&&nav}{error&&<p className="c-global-error" role="alert">{error} <button onClick={()=>void refresh()}>Обновить данные</button></p>}{busy&&<p role="status">Сохраняем на сервере…</p>}
 {loginOpen&&<section className="c-card c-form">{web?<Button onClick={async()=>{await api('/api/operational/auth',{action:'logout'});ref.current=null;setData(null)}}>Выйти на этом компьютере</Button>:<><p>Введите код со страницы WEB на своём компьютере. Подтверждение откроет там доступ от вашего имени.</p><Input aria-label="Код входа WEB" inputMode="numeric" maxLength={8} value={approveCode} onChange={e=>setApproveCode(e.target.value)}/><Button onClick={async()=>{try{await api('/api/operational/auth',{action:'approve',code:approveCode});setLoginStatus('Вход подтверждён. Вернитесь на компьютер.');setApproveCode('')}catch(e){setLoginStatus((e as Error).message)}}}>Подтвердить вход</Button><p>{loginStatus}</p></>}</section>}
 <div className="c-app-content" data-busy={busy}><div className="c-form">{detail?<><Button variant="ghost" onClick={()=>setDetail(null)}><ArrowLeft size={16}/>Назад</Button>{detail.kind==='daily'&&editingDay?<><h2>Исправление суточного задания · {editingDay.date}</h2><DailyForm s={s} t={editingDay} employee={data.user.employee} update={update} editing submit={async v=>{await submitDaily(v);setDetail(null)}}/></>:detail.kind==='document'?<DocumentDetail key={detail.id} s={s} id={detail.id} actor={actor} web={web} update={update} onEditDay={docDay?()=>setDetail({kind:'daily',id:docDay.id}):undefined} onClose={()=>setDetail(null)}/>:detail.kind==='transfer'?<TransferForm s={s} actor={data.user.employee} update={update} id={detail.id} onDone={()=>setDetail(null)}/>:<ExclusionForm s={s} actor={data.user.employee} update={update} onSaved={()=>setDetail(null)}/>}</>:pane==='work'?<DailyWorkPanel s={s} employee={data.user.employee} admin={data.user.admin} update={update} submit={submitDaily} onExclusion={()=>setDetail({kind:'exclusion'})} onTransfer={id=>setDetail({kind:'transfer',id})} onDocument={id=>setDetail({kind:'document',id})}/>:pane==='stats'?<StatsPanel s={s} actor={data.user.employee} admin={data.user.admin} compact={!web} initialQuery={filter?.balance} onDocs={f=>{setFilter(f);setPane('documents')}}/>:pane==='documents'?<><h1>Документы</h1>{filter&&<div className="c-actions"><Button variant="outline" onClick={()=>setPane('stats')}>К показателю</Button><Button variant="ghost" onClick={()=>setFilter(undefined)}>Все документы</Button></div>}<DocumentList key={JSON.stringify(filter)} s={s} filter={filter} onDocument={id=>setDetail({kind:'document',id})}/></>:web&&data.user.admin?<SettingsWorkspace s={s} update={update}/>:null}</div></div>{!web&&nav}</section></main>;
}
