 'use client';
import {useEffect,useState} from 'react';
import {Button} from './ui/button';
import {Choice,Field} from './review-common';
import {accessApi} from '@/lib/access-client';
import type {State} from '@/lib/concise-model';
type RequestRow={id:string;telegram_id:string;name:string;username:string};
type Identity={employee:string;is_admin?:boolean;is_observer?:boolean};
export function AccessRequests({s,identities,onChange}:{s:State;identities:Identity[];onChange:()=>Promise<unknown>}){
 const [requests,setRequests]=useState<RequestRow[]>([]),[links,setLinks]=useState<Record<string,string>>({}),[names,setNames]=useState<Record<string,string>>({}),[roles,setRoles]=useState<Record<string,string>>({}),[administrator,setAdministrator]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[status,setStatus]=useState('');
 const load=async()=>{const data=await accessApi(undefined,true);setRequests(data.requests);setAdministrator(data.administrator);setLoaded(true)};
 useEffect(()=>{void load().catch(e=>setStatus(e.message))},[]);
 return <section className="c-card c-form"><h3>Заявки на доступ</h3><p className="c-help">Представление заявителя — комментарий. Выберите сотрудника или самостоятельно введите имя новой записи, затем назначьте роль. Рабочие объекты сотрудника задаются в настройках складов и функций.</p><Choice label="Администратор, получающий заявки" value={administrator} onChange={setAdministrator} options={[["","Выберите администратора"],...identities.filter(i=>i.is_admin&&!i.is_observer&&s.employees.some(e=>e.id===i.employee&&e.active)).map(i=>[i.employee,s.employees.find(e=>e.id===i.employee)!.name] as [string,string])]}/><Button variant="outline" disabled={busy||!administrator} onClick={async()=>{setBusy(true);try{await accessApi({action:'administrator',employee:administrator},true);setStatus('Получатель заявок сохранён.')}catch(e){setStatus((e as Error).message)}finally{setBusy(false)}}}>Сохранить получателя</Button><Button variant="outline" disabled={busy} onClick={()=>void load().catch(e=>setStatus(e.message))}>Обновить заявки</Button>{loaded&&!requests.length&&<p>Новых заявок нет.</p>}{requests.map(r=><div key={r.id} id={'access-'+r.id} className="c-inset c-form"><b>Представился: {r.name}</b><p>Telegram ID: {r.telegram_id}{r.username?' · @'+r.username:''}</p><Choice label="Сотрудник" value={links[r.id]||''} onChange={v=>setLinks({...links,[r.id]:v})} options={[["","Создать новую запись"],...s.employees.filter(e=>e.active&&!identities.some(i=>i.employee===e.id)).map(e=>[e.id,e.name] as [string,string])]}/>{!links[r.id]&&<Field label="Имя и фамилия в справочнике" value={names[r.id]||''} onChange={v=>setNames({...names,[r.id]:v})}/>}<Choice label="Роль" value={roles[r.id]||''} onChange={v=>setRoles({...roles,[r.id]:v})} options={[["","Выберите роль"],["observer","Наблюдатель · только статистика"],["employee","Сотрудник · по складам и заданиям"],["admin","Администратор"]]}/><div className="c-actions">{(['approve','reject'] as const).map(action=><Button key={action} disabled={busy||(action==='approve'&&(!roles[r.id]||(!links[r.id]&&!names[r.id]?.trim())))} variant={action==='approve'?'default':'outline'} onClick={async()=>{setBusy(true);try{await accessApi({action,id:r.id,employee:links[r.id]||undefined,name:names[r.id],role:roles[r.id]},true);await load();await onChange();setStatus(action==='approve'?'Доступ предоставлен. Уведомление поставлено на отправку.':'Заявка отклонена.')}catch(e){setStatus((e as Error).message)}finally{setBusy(false)}}}>{action==='approve'?'Предоставить доступ':'Отказать'}</Button>)}</div></div>)}<p role="status">{status}</p></section>;
}
