 'use client';
import {useEffect,useState} from 'react';
import {Button} from './ui/button';
import {accessApi} from '@/lib/access-client';
import {accessMessages} from '@/lib/access-workflow';
export function AccessGate({onGranted}:{onGranted:()=>void}){
 const [status,setStatus]=useState('loading'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[cancelled,setCancelled]=useState(false);
 useEffect(()=>{let active=true,running=false;const load=async()=>{if(running)return;running=true;try{const r=await accessApi();if(!active)return;setStatus(r.status);setError('');if(r.status==='approved')onGranted();}catch{if(active)setError('Не удалось проверить доступ. Проверьте соединение и повторите попытку.')}finally{running=false}};void load();const timer=setInterval(load,15000);return()=>{active=false;clearInterval(timer)}},[]);
 return <main className="c-review production tg"><section className="c-card c-form"><h1>Учёт кабеля</h1>{error?<><p role="alert">{error}</p><Button onClick={()=>{setError('');void accessApi().then(r=>{setStatus(r.status);if(r.status==='approved')onGranted()}).catch(()=>setError('Не удалось проверить доступ. Повторите попытку.'))}}>Повторить</Button></>:status==='pending'?<p role="status">{accessMessages.pending}</p>:status==='disabled'?<p>{accessMessages.disabled}</p>:status==='loading'?<p>Проверяем доступ…</p>:status==='draft'?<><p>Чтобы завершить запрос, представьтесь в чате с ботом.</p><a href="https://t.me/rsskablebot?start=access">Перейти в чат</a></>:<>{status==='rejected'&&<p>{accessMessages.rejected}</p>}<p>{cancelled?'Запрос не отправлен.':'Нет доступа. Запросить?'}</p><div className="c-actions"><Button disabled={busy} onClick={async()=>{setBusy(true);try{const r=await accessApi({action:'begin'});setStatus(r.status);setCancelled(false);if(r.status==='approved')onGranted();}catch{setError('Не удалось завершить запрос. Проверьте состояние перед повторной отправкой.')}finally{setBusy(false)}}}>{status==='rejected'?'Запросить повторно':cancelled?'Запросить доступ':'Да'}</Button>{!cancelled&&<Button variant="outline" onClick={()=>setCancelled(true)}>Нет</Button>}</div></>}</section></main>;
}
