'use client';
import {EmployeeFunctions} from './employee-functions';
import {Fragment,useEffect,useRef,useState} from 'react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Choice,Field} from './review-common';
import {MeasurementSettings,CrewSettings} from './concise-reference-settings';
import {PidSettings,ReplacementSettings} from './concise-pid';
import type {Update} from './concise-work';
import * as M from '@/lib/concise-model';
import type {Section} from '@/lib/settings-filters';
export function SettingsPanel({s,update,section='functions',visible}:{s:M.State;update:Update;section?:Section;visible?:Set<string>}){
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[edit,setEdit]=useState<M.Assignment|null>(null),[employee,setEmployee]=useState('');
 const editorRef=useRef<HTMLDivElement>(null);
 const [editError,setEditError]=useState('');
 useEffect(()=>{if(edit){setEditError('');editorRef.current?.scrollIntoView({block:'nearest'});editorRef.current?.focus({preventScroll:true})}},[edit?.id]);
 const [standard,setStandard]=useState({material:s.materials.find(m=>m.kind==='cable')?.id||'',date:s.today,rate:String(s.standards.at(-1)?.rate||20000),norm:(s.standards.at(-1)?.norm||[15,15,10]).map(String)});
 const [opening,setOpening]=useState({warehouse:s.warehouses[0]?.id||'',material:s.materials.find(m=>m.kind==='cable')?.id||'',date:s.today,qty:''});
 const [catalog,setCatalog]=useState({kind:'warehouse',name:'',pid:'',owner:s.employees[0]?.id||'',warehouseKind:'field',materialKind:'cable'});
 useEffect(()=>{setCatalog(c=>({...c,kind:section==='materials'?'material':'warehouse'}))},[section]);
 const act=async(change:(s:M.State)=>M.State,text:string)=>{try{await update(change);setError('');setMessage(text)}catch(e){setError((e as Error).message);setMessage('')}};
 const employeeOptions=s.employees.filter(p=>p.active).map(p=>[p.id,p.name] as [string,string]);
 const addCatalog=()=>act(st=>{if(catalog.kind!=='warehouse'&&!catalog.name.trim())throw Error('Укажите название.');if(catalog.kind==='warehouse'){if(st.warehouses.some(w=>w.owner===catalog.owner&&w.pid===catalog.pid))throw Error('Этот склад ответственного уже существует.');return {...st,warehouses:[...st.warehouses,{id:'w-'+crypto.randomUUID().slice(0,8),name:M.person(st,catalog.owner)+(catalog.pid?' · ПИД'+catalog.pid:''),pid:catalog.pid.trim(),owner:catalog.owner,kind:catalog.pid?'field':'main'}]}}if(st.materials.some(m=>m.name.toLowerCase()===catalog.name.trim().toLowerCase()))throw Error('Материал с таким названием уже есть.');return {...st,materials:[...st.materials,{id:'m-'+crypto.randomUUID().slice(0,8),name:catalog.name.trim(),kind:catalog.materialKind as M.Material['kind']}]};},'Запись добавлена в справочник.');
 const assignmentEditor=edit&&<div ref={editorRef} tabIndex={-1} role="region" aria-label="Редактор назначения" className="c-form c-inset"><h3>{s.assignments.some(a=>a.id===edit.id)?"Изменение назначения":"Новое назначение"}</h3><p>{M.warehouse(s,edit.warehouse)} · {M.works[edit.work].name}{edit.material&&" · "+M.material(s,edit.material)}</p>{editError&&<p className="c-error" role="alert">{editError}</p>}<Choice label="Склад ответственного" value={edit.warehouse} onChange={warehouse=>setEdit({...edit,warehouse})} options={s.warehouses.map(w=>[w.id,w.name])}/><div className="c-grid-two"><Choice label="Функция" value={edit.work} onChange={work=>setEdit({...edit,work:work as M.Work,material:work==='dig'?'':edit.material||s.materials.find(m=>m.kind==='cable')?.id||''})} options={(Object.entries(M.works)).map(([id,v])=>[id,v.name])}/>{edit.work!=='dig'&&<Choice label="Кабель" value={edit.material} onChange={material=>setEdit({...edit,material})} options={s.materials.filter(m=>m.kind==='cable').map(m=>[m.id,m.name])}/>}</div><p className="c-help">Ответственный уже определён выбранным складом. Он и доверенные лица склада получают общее задание. Повторно выбирать сотрудника не нужно.</p><label className="c-check"><input type="checkbox" checked={edit.active} onChange={e=>setEdit({...edit,active:e.target.checked})}/>Создавать новые задания</label><div className="c-actions"><Button onClick={async()=>{try{await update(st=>M.saveAssignment(st,edit));setEdit(null);setError('');setMessage('Назначение сохранено. Уже созданные задания сохранены без изменений.')}catch(e){setEditError((e as Error).message)}}}>Сохранить назначение</Button><Button variant="ghost" onClick={()=>setEdit(null)}>Отмена</Button></div></div>;
 const show=(id:string)=>!visible||visible.has(id);
 return <>

  {error&&<p className="c-error" role="alert">{error}</p>}{message&&<p className="c-success" role="status">{message}</p>}
  {section==='pid'&&<PidSettings s={s} update={update} visible={visible}/>}
  {section==='trust'&&<ReplacementSettings s={s} update={update} visible={visible}/>}
  {section==='functions'&&s.dailyVersion===1&&<EmployeeFunctions s={s} update={update} visible={visible}/>}
  {section==='functions'&&!s.dailyVersion&&<details className="c-setting" open><summary>Функции складов <span>{s.assignments.filter(a=>a.active).length}</span></summary><p className="c-help">Каждый день в 09:00. Все дни рабочие. Изменения относятся только к ещё не созданным заданиям.</p>
   <div className="c-table-scroll"><table className="c-table"><thead><tr><th>Склад / ПИД</th><th>Функция</th><th>Назначение</th></tr></thead><tbody>{s.assignments.filter(a=>show(a.id)).map(a=><Fragment key={a.id}><tr><td>{M.warehouse(s,a.warehouse)}<small>{a.material&&M.material(s,a.material)}</small></td><td>{M.works[a.work].name}</td><td><button className="c-text-button" aria-expanded={edit?.id===a.id} onClick={()=>setEdit(structuredClone(a))}>{a.active?'Действует':'Выключено'} · Изменить</button></td></tr>{edit?.id===a.id&&<tr><td colSpan={3}>{assignmentEditor}</td></tr>}</Fragment>)}</tbody></table></div>
   <Button variant="outline" onClick={()=>setEdit({id:'a-'+crypto.randomUUID().slice(0,8),warehouse:s.warehouses[0].id,material:s.materials.find(m=>m.kind==='cable')?.id||'',work:'extract',active:true})}>＋ Назначение</Button>
   {edit&&!s.assignments.some(a=>a.id===edit.id)&&assignmentEditor}
  </details>}
  {section==='staff'&&<details className="c-setting" open><summary>Сотрудники <span>{s.employees.length}</span></summary><div className="c-inline-add"><Input aria-label="Имя нового сотрудника" placeholder="Имя Фамилия" value={employee} onChange={e=>setEmployee(e.target.value)}/><Button onClick={()=>act(st=>{if(employee.trim().length<3)throw Error('Укажите имя сотрудника.');return {...st,employees:[...st.employees,{id:'p-'+crypto.randomUUID().slice(0,8),name:employee.trim(),active:true}]}},'Сотрудник добавлен. Его можно назначить ответственным за склад или включить в бригаду.')}>Добавить</Button></div><div className="c-employee-list">{s.employees.filter(p=>show(p.id)).map(p=><div className="c-total-line" key={p.id}><span>{p.name}</span><label className="c-check"><input type="checkbox" checked={p.active} onChange={e=>act(st=>({...st,employees:st.employees.map(x=>x.id===p.id?{...x,active:e.target.checked}:x)}),'Статус сотрудника изменён. Исторические документы сохранены.')}/>{p.active?'Работает':'Не работает'}</label></div>)}</div></details>}
 {section==='crew'&&<CrewSettings s={s} update={update} visible={visible}/>}
  {(section==='warehouses'||section==='materials')&&<details className="c-setting" open><summary>{section==='warehouses'?'Склады':'Кабели и металлы'}</summary><div className="c-grid-two"><div>{section==='warehouses'&&s.warehouses.filter(w=>show(w.id)).map(w=><p key={w.id}>{w.name}<small className="c-help"> · {M.person(s,w.owner)}</small></p>)}</div><div>{section==='materials'&&s.materials.filter(m=>show(m.id)).map(m=><p key={m.id}>{m.name} · {m.kind==='metal'?'металл':'сырьё'}</p>)}</div></div><div className="c-inset c-form"><>{catalog.kind!=='warehouse'&&<Field label="Название материала" value={catalog.name} onChange={name=>setCatalog({...catalog,name})}/>}</>{catalog.kind==='warehouse'?<><Choice label="ПИД склада" value={catalog.pid} onChange={pid=>setCatalog({...catalog,pid})} options={[["","Без ПИД"],...M.pidCatalog(s).map(p=>[p.id,"ПИД"+p.id] as [string,string])]}/><Choice label="Материально ответственный" value={catalog.owner} onChange={owner=>setCatalog({...catalog,owner})} options={employeeOptions}/></>:<Choice label="Группа материала" value={catalog.materialKind} onChange={materialKind=>setCatalog({...catalog,materialKind})} options={[["cable","Кабель"],["metal","Металл"]]}/>}<Button onClick={addCatalog}>Добавить в справочник</Button></div></details>}
  {section==='mass'&&<MeasurementSettings s={s} update={update} visible={visible}/>}
  {section==='norms'&&<details className="c-setting" open><summary>Нормативы разделки и тариф</summary><p className="c-help">Мастер видит тариф и распределяет ФОТ через КТУ. Норматив — ориентир для фактического выхода металлов.</p><div className="c-table-scroll"><table className="c-table"><thead><tr><th>Кабель</th><th>Действует с</th><th>Тариф, ₽/т</th></tr></thead><tbody>{s.standards.filter(n=>show(n.material+'|'+n.date)).map(n=><tr key={n.material+'|'+n.date}><td>{M.material(s,n.material||'')}</td><td>{n.date}</td><td>{M.fmt(n.rate)} <button className="c-text-button" onClick={()=>setStandard({material:n.material||'',date:n.date,rate:String(n.rate),norm:n.norm.map(String)})}>Изменить</button></td></tr>)}</tbody></table></div><Choice label="Кабель норматива" value={standard.material} onChange={material=>setStandard({...standard,material})} options={s.materials.filter(m=>m.kind==='cable').map(m=>[m.id,m.name])}/><Field label="Действует с" type="date" value={standard.date} onChange={date=>setStandard({...standard,date})}/><Field label="Тариф разделки, ₽/т" value={standard.rate} onChange={rate=>setStandard({...standard,rate})}/><div className="c-grid-three">{['Медь, %','Свинец, %','Алюминий, %'].map((label,i)=><Field key={label} label={label} value={standard.norm[i]} onChange={v=>setStandard({...standard,norm:standard.norm.map((x,k)=>k===i?v:x)})}/>)}</div><Button onClick={()=>act(st=>{const rate=M.n(standard.rate),norm=standard.norm.map(M.n);if(!(rate>0)||norm.some(x=>!Number.isFinite(x)||x<0)||norm.reduce((a,b)=>a+b,0)>100||!standard.date)throw Error('Проверьте тариф и доли металлов. Их сумма не должна превышать 100%.');return {...st,standards:[...st.standards.filter(x=>x.date!==standard.date||x.material!==standard.material),{material:standard.material,date:standard.date,rate,norm}]};},'Правило сохранено. Тарифы и нормы в подтверждённых документах не изменились.')}>Сохранить правило</Button></details>}
  {section==='opening'&&<details className="c-setting" open><summary>Начальные остатки · однократно</summary><p className="c-help">Масса кабеля и металлов в тоннах, без катушек. Повторный ввод той же пары «склад + материал» заблокирован. Исправление — через документ.</p><div className="c-table-scroll"><table className="c-table"><thead><tr><th>Документ</th><th>Склад / материал</th><th>Масса, т</th></tr></thead><tbody>{s.documents.filter((d):d is M.Opening=>d.kind==='opening'&&show(d.id)).map(d=><tr key={d.id}><td>{d.id}<small>{d.date}</small></td><td>{M.warehouse(s,d.warehouse)}<small>{M.material(s,d.material)}</small></td><td>{M.fmt(d.qty,6)}</td></tr>)}</tbody></table></div><Choice label="Склад" value={opening.warehouse} onChange={warehouse=>setOpening({...opening,warehouse})} options={s.warehouses.map(w=>[w.id,w.name])}/><Choice label="Материал" value={opening.material} onChange={material=>setOpening({...opening,material})} options={s.materials.map(m=>[m.id,m.name])}/><div className="c-grid-two"><Field label="Дата начала учёта" type="date" value={opening.date} onChange={date=>setOpening({...opening,date})}/><Field label="Масса, т" value={opening.qty} onChange={qty=>setOpening({...opening,qty})}/></div><Button onClick={()=>act(st=>{if(st.documents.some(d=>d.kind==='opening'&&d.warehouse===opening.warehouse&&d.material===opening.material))throw Error('Начальный остаток уже введён. Найдите документ в «Документах».');const qty=M.n(opening.qty);if(!Number.isFinite(qty)||qty<0||opening.date>st.today)throw Error('Проверьте массу и дату.');const d:M.Opening={...opening,qty,id:'Н-'+crypto.randomUUID().slice(0,8),kind:'opening',actor:'admin'};return {...st,documents:[...st.documents,d]};},'Начальный остаток подтверждён.')}>Подтвердить начальный остаток</Button></details>}
 </>
}
