'use client';
import {useState} from 'react';
import {Button} from './ui/button';
import {Textarea} from './ui/textarea';
import {Choice,Field} from './review-common';
import type {Update} from './concise-work';
import type {DocFilter} from './concise-stats';
import * as M from '@/lib/concise-model';

export function PidProgress({s,from,to,pids,onDocs}:{s:M.State;from:string;to:string;pids:string[];onDocs:(f:DocFilter)=>void}){
 return <section className="c-pid-progress"><div className="c-section-title"><h2>Прогресс ПИД</h2><span>на {M.dateLabel(to)}</span></div><p className="c-help">Освоено = выкопано + участки без извлечения. Доля от полной длины трассы; суммарно по всем МОЛ этого ПИД.</p>{pids.map(pid=>{const p=M.pidProgress(s,pid,from,to);return <article key={pid} className="c-pid-row"><div className="c-total-line"><h3>ПИД{pid}</h3><b>{p.percent===null?'Длина не задана':M.fmt(p.percent,1)+'%'}</b></div><div className="c-pid-track" role="img" aria-label={`ПИД${pid}: выкопано ${M.fmt(p.dig)} м, без извлечения ${M.fmt(p.excluded)} м; ${p.length?'длина '+M.fmt(p.length)+' м':'длина не задана'}`}><span className="dug" style={{width:p.length?`${Math.min(100,p.dig/p.length*100)}%`:'0%'}}/><span className="excluded" style={{width:p.length?`${Math.min(Math.max(0,100-p.dig/p.length*100),p.excluded/p.length*100)}%`:'0%'}}/></div><div className="c-total-line"><span>Освоено <b>{M.fmt(p.total)} м</b>{p.length?' из '+M.fmt(p.length)+' м':''}</span><span>За период +{M.fmt(p.period)} м</span></div><div className="c-pid-parts"><button onClick={()=>onDocs({ids:p.docs.filter(d=>d.kind==='work').map(d=>d.id),title:'ПИД'+pid+' · копка по '+M.dateLabel(to)})}><i className="dug"/>Копка <b>{M.fmt(p.dig)} м</b></button><button onClick={()=>onDocs({ids:p.docs.filter(d=>d.kind==='exclusion').map(d=>d.id),title:'ПИД'+pid+' · неизвлекаемые участки по '+M.dateLabel(to)})}><i className="excluded"/>Без извлечения <b>{M.fmt(p.excluded)} м</b></button></div>{p.percent!==null&&p.percent>100&&<p className="c-warning">Превышение длины на {M.fmt(p.total-p.length!)} м. Проверьте длину ПИД и документы.</p>}{p.length===null&&<p className="c-help">Длину вводит администратор в WEB → Настройки → ПИД и длина трассы.</p>}</article>})}{!pids.length&&<p className="c-empty">В этой области нет ПИД.</p>}<p className="c-help">Нажмите копку или участок — откроются документы. Извлечение, намотка и перемещения не меняют процент освоения.</p></section>
}

export function ExclusionForm({s,actor,update,doc,onSaved}:{s:M.State;actor:string;update:Update;doc?:M.Exclusion;onSaved?:()=>void}){
 const options=s.warehouses.filter(w=>w.kind==='field'&&M.canManageWarehouse(s,w.id,actor)),v=doc?.versions.at(-1);
 const [warehouse,setWarehouse]=useState(doc?.warehouse||options[0]?.id||''),[date,setDate]=useState(doc?.date||s.today),[length,setLength]=useState(v?String(M.exclusionLength(v)):''),[reason,setReason]=useState(''),[checked,setChecked]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const submit=async()=>{try{if(!checked)throw Error('Подтвердите, что участок не включён в копку.');const id=doc?.id||'У-'+crypto.randomUUID().slice(0,8);await update(st=>M.saveExclusion(st,{id,date,warehouse,lengthM:M.n(length),reason,expected:v?.version||0},actor));setSaved('Участок записан. Прогресс ПИД обновлён; остатки материалов не изменились.');setError('');if(!doc){setLength('');setReason('');setChecked(false)}onSaved?.()}catch(e){setError((e as Error).message)}};
 return <div className="c-form"><p className="c-help">Решение не копать часть трассы. Участок учитывается в освоении ПИД отдельно от выполненной копки.</p>{doc?<p>{M.warehouse(s,warehouse)} · {M.dateLabel(date)}</p>:<><Choice label="ПИД и склад МОЛ" value={warehouse} onChange={setWarehouse} options={options.map(w=>[w.id,w.name])}/><Field label="Дата решения" type="date" value={date} onChange={setDate}/></>}<Field label="Длина неизвлекаемого участка, м" value={length} onChange={setLength}/><label className="c-field">{doc?'Причина решения и исправления':'Причина, по которой участок не извлекается'}<Textarea value={reason} onChange={e=>setReason(e.target.value)}/></label><label className="c-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>Участок не включён в копку и не зарегистрирован ранее</label><p className="c-help">Если ранее включили его в копку — сначала исправьте соответствующий документ. Повтор одного участка проверяет ответственный: по одной длине определить совпадение мест нельзя.</p>{error&&<p role="alert" className="c-error">{error}</p>}{saved&&<p role="status" className="c-success">{saved}</p>}<Button onClick={submit}>{doc?'Сохранить исправление участка':'Зафиксировать участок'}</Button></div>
}

export function PidSettings({s,update}:{s:M.State;update:Update}){
 const [id,setId]=useState(''),[length,setLength]=useState(''),[editing,setEditing]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const save=async()=>{try{if(!editing&&M.pidCatalog(s).some(p=>p.id===id.trim()))throw Error('ПИД уже есть. Нажмите «Изменить длину» в его строке.');await update(st=>M.savePid(st,{id,lengthM:length.trim()?M.n(length):null}));setMessage('Длина ПИД сохранена. Процент освоения пересчитан; первичные документы не изменились.');setError('');setId('');setLength('');setEditing(false)}catch(e){setError((e as Error).message)}};
 return <details className="c-setting" open><summary>ПИД и длина трассы <span>{M.pidCatalog(s).length}</span></summary><p className="c-help">Одна общая длина ПИД для всех складов и типов кабеля. Используется как знаменатель процента освоения, в метрах.</p>{M.pidCatalog(s).map(p=><div className="c-total-line" key={p.id}><span><b>ПИД{p.id}</b><small>{p.lengthM?M.fmt(p.lengthM)+' м':'Длина не задана'}</small></span><button className="c-text-button" onClick={()=>{setId(p.id);setLength(p.lengthM===null?'':String(p.lengthM));setEditing(true);setMessage('')}}>Изменить длину</button></div>)}<div className="c-inset c-form"><h3>{editing?'Длина ПИД'+id:'Добавить ПИД'}</h3><div className="c-grid-two"><Field label="Номер ПИД" disabled={editing} value={id} onChange={setId}/><Field label="Полная длина трассы, м" value={length} onChange={setLength}/></div><p className="c-help">Пустое поле означает «длина ещё не известна». Без неё процент не рассчитывается.</p>{error&&<p role="alert" className="c-error">{error}</p>}{message&&<p role="status" className="c-success">{message}</p>}<div className="c-actions"><Button onClick={save}>{editing?'Сохранить длину':'Добавить ПИД'}</Button>{editing&&<Button variant="ghost" onClick={()=>{setEditing(false);setId('');setLength('')}}>Отмена</Button>}</div></div></details>
}

export function ReplacementSettings({s,update}:{s:M.State;update:Update}){
 const [warehouse,setWarehouse]=useState(s.warehouses[0].id),[deputy,setDeputy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 const save=async(r:M.Replacement)=>{try{await update(st=>M.saveReplacement(st,r));setError('');setMessage('Доступ сохранён. Задания изменятся со следующего создания в 09:00. Передачи доступны по действующему разрешению.')}catch(e){setError((e as Error).message)}};
 return <details className="c-setting"><summary>Доверенные лица <span>{s.replacements.filter(r=>r.active).length}</span></summary><p className="c-help">Склад / сотрудник. Доверенное лицо получает все новые задания по функциям МОЛ на этом складе, может отправлять и принимать материалы. Склад и ответственность остаются у МОЛ; в документе фиксируется фактический автор.</p>{s.replacements.map(r=><div className="c-total-line" key={r.warehouse+r.deputy}><span>{M.warehouse(s,r.warehouse)}<small>Доверенное лицо: {M.person(s,r.deputy)}</small></span><button className="c-text-button" onClick={()=>save({...r,active:!r.active})}>{r.active?'Отключить':'Включить'}</button></div>)}<div className="c-inset c-form"><Choice label="Склад МОЛ / ПИД" value={warehouse} onChange={setWarehouse} options={s.warehouses.map(w=>[w.id,w.name+' · МОЛ '+M.person(s,w.owner)])}/><Choice label="Доверенное лицо" value={deputy} onChange={setDeputy} options={[["","Выберите сотрудника"],...s.employees.filter(e=>e.active&&e.id!==s.warehouses.find(w=>w.id===warehouse)?.owner).map(e=>[e.id,e.name] as [string,string])]}/>{error&&<p role="alert" className="c-error">{error}</p>}{message&&<p role="status" className="c-success">{message}</p>}<Button onClick={()=>save({warehouse,deputy,active:true})}>Предоставить доступ</Button></div><p className="c-help">Уже созданные задания сохраняют прежний состав допущенных сотрудников. Одно подтверждение закрывает общее задание у всех.</p></details>
}
