'use client';
import {useState} from 'react';
import {transferCoils} from '@/lib/concise-coils';
import {personalWarehouses,matchingPids,visibleBalance,workMatches} from '@/lib/stats-filters';
import {BalanceValue} from './concise-balance';
import {balanceCell,inBalanceQuery,type BalanceQuery,type BalanceColumn} from '@/lib/concise-balance';
import {PidProgress} from './concise-pid';
import {Choice,Field} from './review-common';
import {Button} from './ui/button';
import * as D from '@/lib/daily-work';
import * as M from '@/lib/concise-model';
export type DocFilter={ids?:string[];title?:string;balance?:BalanceQuery};
export function StatsPanel({s,actor,onDocs,compact=false,initialQuery,admin=false}:{admin?:boolean;s:M.State;actor:string;compact?:boolean;initialQuery?:BalanceQuery;onDocs:(f?:DocFilter)=>void}){
 const ownWarehouses=personalWarehouses(s,actor),hasPersonal=ownWarehouses.length>0;
 const initialWarehouse=s.warehouses.find(w=>w.id===initialQuery?.scope);
 const initialScope=initialWarehouse?'owners':initialQuery?.scope.startsWith('pid:')?'all':initialQuery?.scope||'all';
 const [view,setView]=useState('materials'),[cableUnit,setCableUnit]=useState(initialQuery?.unit||'tonnes'),[period,setPeriod]=useState(initialQuery?'custom':'month'),[from,setFrom]=useState(initialQuery?.from||s.today.slice(0,8)+'01'),[to,setTo]=useState(initialQuery?.to||s.today),[chosenScope,setScope]=useState(initialScope),[materials,setMaterials]=useState<string[]|null>(null),[owners,setOwners]=useState<string[]>(initialQuery?.owners||[...(initialWarehouse?[initialWarehouse.owner]:new Set(s.warehouses.map(w=>w.owner)))]),[pidSelection,setPids]=useState<string[]>(initialQuery?.pids||(initialWarehouse?.pid?[initialWarehouse.pid]:initialQuery?.scope.startsWith('pid:')?[initialQuery.scope.slice(4)]:[])),[withMotion,setMotion]=useState(false),[withStock,setStock]=useState(false);
 const scope=chosenScope==='mine'&&!hasPersonal?'all':chosenScope,activePids=compact?[]:pidSelection,chosenMaterials=compact||materials?.length===s.materials.length?null:materials;
 const baseQuery={scope,actor,...(scope==='owners'?{owners}:{}),...(activePids.length?{pids:activePids}:{})};
 const company=scope==='all'&&!activePids.length,materialMatches=(id:string)=>chosenMaterials===null||chosenMaterials.includes(id);
 const choosePeriod=(p:string)=>{setPeriod(p);setTo(s.today);if(p==='today')setFrom(s.today);if(p==='month')setFrom(s.today.slice(0,8)+'01');if(p==='week'){const d=new Date(s.today+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+6)%7));setFrom(d.toISOString().slice(0,10));}};
 const inScope=(w:string)=>inBalanceQuery(s,baseQuery,w);
 const balanceQuery=(material:string,column:BalanceColumn,unit:BalanceQuery['unit']='tonnes'):BalanceQuery=>({...baseQuery,material,column,from,to,unit});
 const inWorkScope=(a:M.Assignment)=>inScope(a.warehouse);
 const materialPids=matchingPids(s,chosenMaterials);
 const pids=M.pidCatalog(s).filter(p=>materialPids.includes(p.id)&&(!activePids.length||activePids.includes(p.id))&&(scope==='all'||s.warehouses.some(w=>w.pid===p.id&&inScope(w.id)))).map(p=>p.id);
 const docs=s.documents.filter((d):d is M.WorkDoc=>d.kind==='work'&&inWorkScope(d.assignment)&&workMatches(s,d,chosenMaterials,materialPids)&&d.date<=to);
 const tasks=s.tasks.filter(t=>t.source!=='restored'&&inWorkScope(t.assignment)&&t.date>=from&&t.date<=to);
 const discipline=s.dailyVersion?(s.dailyTasks||[]).filter(t=>!t.restored&&t.date>=from&&t.date<=to&&inScope(t.warehouse)).map(t=>({id:t.id,date:t.date,employee:t.employee,closed:D.completed(s,t),at:D.closedAt(s,t),overdue:D.overdue(s,t)})):tasks.map(t=>({id:t.id,date:t.date,employee:M.assignmentOwner(s,t.assignment),closed:!!M.taskDoc(s,t.id),at:M.taskDoc(s,t.id)?.versions[0].at,overdue:!M.taskDoc(s,t.id)&&(t.date<s.today||t.date===s.today&&s.hour>=21)}));
 const closed=discipline.filter(t=>t.closed),late=closed.filter(t=>t.at&&new Date(t.at)>new Date(t.date+'T21:00:00+07:00')),overdue=discipline.filter(t=>t.overdue);
 const selected=docs.filter(d=>d.date>=from),strips=selected.filter(d=>d.assignment.work==='strip'),pay:Record<string,number>={};
 strips.forEach(d=>{const v=M.current(d),parts=M.payout(v.qty*v.rate,v.crew);v.crew.forEach((c,i)=>pay[c.employee]=(pay[c.employee]||0)+parts[i]);});
 const kinds=(['metal','cable'] as const).filter(k=>s.materials.some(m=>m.kind===k&&materialMatches(m.id)));
 const hasWarehouses=scope==='transit'||s.warehouses.some(w=>inScope(w.id));
 const balanceRows=(kind:M.Material['kind'])=>s.materials.filter(m=>m.kind===kind&&materialMatches(m.id)&&!(kind==='metal'&&activePids.length)&&hasWarehouses).filter(m=>{const unit=kind==='cable'&&cableUnit==='coils'?'coils':'tonnes';return visibleBalance({plus:balanceCell(s,balanceQuery(m.id,'plus',unit)).value,minus:balanceCell(s,balanceQuery(m.id,'minus',unit)).value,after:balanceCell(s,balanceQuery(m.id,'after',unit)).value},withMotion,withStock);});
 const exportMaterials=view==='materials'?kinds.flatMap(kind=>balanceRows(kind).map(m=>m.id)):chosenMaterials;
 const unknownCoils=s.documents.filter((d):d is M.Transfer=>d.kind==='transfer'&&d.date<=to&&(inScope(d.from)||inScope(d.to)||inScope('transit'))&&d.items.some(i=>materialMatches(i.material)&&s.materials.some(m=>m.id===i.material&&m.kind==='cable')&&transferCoils(d,i)===null));
 const personalWorks=(Object.keys(M.works) as M.Work[]).filter(w=>scope!=='mine'||docs.some(d=>d.assignment.work===w)||tasks.some(t=>t.assignment.work===w)||(s.dailyVersion?(s.dailyTasks||[]).some(t=>D.canFill(s,t,actor)&&t.functions.includes(w)):s.assignments.some(a=>a.active&&a.work===w&&inWorkScope(a))));
 const showStrip=scope!=='mine'||personalWorks.includes('strip');
 const showPay=admin||actor==='admin'||(s.dailyTasks||[]).some(t=>t.functions.includes('strip')&&D.canFill(s,t,actor))||s.warehouses.some(w=>w.kind==='master'&&M.canManageWarehouse(s,w.id,actor));
 const cell=(value:number,ids:string[],title:string,unit='')=><button className="c-number-link" onClick={()=>onDocs({ids:[...new Set(ids)],title})}>{M.fmt(value)}{unit}</button>;
 return <>
  <div className="c-heading"><div><h1>Показатели работы</h1><p>{M.dateLabel(from)} — {M.dateLabel(to)}</p></div></div>
  <div className={compact?'stats-mobile-bar':'stats-periods'}>
   {compact?<Choice label="Период" value={period} onChange={choosePeriod} options={[["today","Сегодня"],["week","Неделя"],["month","Месяц"],["custom","Период"]]}/>:<div className="c-segments periods">{[['today','Сегодня'],['week','Неделя'],['month','Месяц'],['custom','Период']].map(([v,t])=><button key={v} aria-pressed={period===v} onClick={()=>choosePeriod(v)}>{t}</button>)}</div>}
   {compact&&hasPersonal&&<div className="c-segments" aria-label="Область наблюдения"><button aria-pressed={scope==='mine'} onClick={()=>setScope('mine')}>Я</button><button aria-pressed={scope==='all'} onClick={()=>setScope('all')}>Компания</button></div>}
  </div>
  {period==='custom'&&<div className="c-grid-two"><Field label="С" type="date" value={from} onChange={setFrom}/><Field label="По" type="date" value={to} onChange={setTo}/></div>}
  {!compact&&<section className="stats-filters" aria-label="Отборы показателей">
   <div className="stats-filter-row"><b>Область наблюдения</b><div className="stats-chips">{[...(hasPersonal?[["mine","Я"]]:[]),["all","Компания"],["owners","Склад / сотрудник"]].map(([v,label])=><button key={v} aria-pressed={scope===v} onClick={()=>setScope(v)}>{label}</button>)}</div></div>
   {scope==='owners'&&<div className="stats-filter-row"><b>Ответственный</b><div className="stats-chips"><button aria-pressed={owners.length===new Set(s.warehouses.map(w=>w.owner)).size} onClick={()=>setOwners(owners.length===new Set(s.warehouses.map(w=>w.owner)).size?[]:[...new Set(s.warehouses.map(w=>w.owner))])}>Все</button>{s.employees.filter(e=>s.warehouses.some(w=>w.owner===e.id)).map(e=><button key={e.id} aria-pressed={owners.includes(e.id)} onClick={()=>setOwners(owners.includes(e.id)?owners.filter(id=>id!==e.id):[...owners,e.id])}>{e.name}</button>)}</div></div>}
   {(['cable','metal'] as const).map(kind=>{const group=s.materials.filter(m=>m.kind===kind),selected=materials||s.materials.map(m=>m.id),all=group.every(m=>selected.includes(m.id));return <div className="stats-filter-row" key={kind}><b>{kind==='cable'?'Кабели':'Металлы'}</b><div className="stats-chips"><button aria-label={kind==='cable'?'Все кабели':'Все металлы'} aria-pressed={all} onClick={()=>setMaterials(all?selected.filter(id=>!group.some(m=>m.id===id)):[...new Set([...selected,...group.map(m=>m.id)])])}>Все</button>{group.map(m=><button key={m.id} aria-pressed={selected.includes(m.id)} onClick={()=>setMaterials(selected.includes(m.id)?selected.filter(id=>id!==m.id):[...selected,m.id])}>{m.name}</button>)}</div></div>})}
   <div className="stats-active"><span>{scope==='mine'?'Я':scope==='all'?'Компания':scope==='transit'?'В пути / расхождения':'Склады выбранных сотрудников'}{activePids.length?' · ПИД '+activePids.join(', '):''}</span><button className="c-text-button" onClick={()=>{setScope('all');setOwners([...new Set(s.warehouses.map(w=>w.owner))]);setMaterials(null);setPids([]);setMotion(false);setStock(false)}}>Сбросить отборы</button></div>
  </section>}
  {view==='materials'&&<div className="stats-visibility"><div className="stats-chips" aria-label="Строки материалов и ПИД"><button aria-pressed={withMotion} onClick={()=>setMotion(!withMotion)}>С оборотами</button><button aria-pressed={withStock} onClick={()=>setStock(!withStock)}>С остатком</button></div>{(withMotion||withStock)&&<small>{withMotion&&withStock?'Материалы и ПИД: обороты ИЛИ остаток.':withMotion?'Материалы: приход или расход. ПИД: продвижение за период.':'Материалы: остаток на конец периода. ПИД: неосвоенная трасса.'}</small>}</div>}
  {!!activePids.length&&<p className="c-help">Отбор ПИД ограничивает полевой учёт. Общие склады и металлы не имеют аналитики ПИД и исключены из этой выборки.</p>}
  {from>to?<p className="c-error">Начало периода должно быть раньше его окончания.</p>:<>
  <div className="c-segments"><button aria-pressed={view==='materials'} onClick={()=>setView('materials')}>Материалы</button><button aria-pressed={view==='work'} onClick={()=>setView('work')}>Работы и дисциплина</button></div>
  {view==='materials'?<>
   {kinds.map(kind=>{const unit=kind==='cable'&&cableUnit==='coils'?'coils':'tonnes',rows=balanceRows(kind);return <section className={'c-balance '+kind} key={kind}><div className="c-section-title"><h2>{kind==='metal'?'Металлы':'Кабель'}</h2><span>{unit==='coils'?'шт.':'тонны'}</span></div>
    {kind==='cable'&&<div className="c-segments" aria-label="Единица учёта кабеля"><button aria-pressed={cableUnit==='tonnes'} onClick={()=>setCableUnit('tonnes')}>Тонны</button><button aria-pressed={cableUnit==='coils'} onClick={()=>setCableUnit('coils')}>Катушки</button></div>}
    {rows.length?<div className="c-table-scroll"><table className="c-table balance"><thead><tr><th>Материал</th><th>Было</th><th>＋</th><th>−</th><th>Стало</th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><th>{m.name.replace('Кабель ','')}</th>{(['before','plus','minus','after'] as const).map(column=><td key={column} className={column==='plus'?'c-plus':column==='after'?'c-ending':''}><BalanceValue s={s} query={balanceQuery(m.id,column,unit)} onDocs={onDocs}/></td>)}</tr>)}</tbody></table></div>:<p className="c-empty">{activePids.length&&kind==='metal'?'У металлов нет аналитики ПИД. Снимите отбор ПИД.':!hasWarehouses?'Нет складов по выбранному сочетанию сотрудника и ПИД.':'Нет строк по выбранным условиям.'}</p>}
    <p className="c-help">{unit==='coils'?'Катушки — вспомогательный учёт: намотка и передачи. Начальные остатки и разделка ведутся без количества катушек; это не полный физический остаток после разделки.':kind==='metal'?'＋ Получено при разделке и поступило · − передано или выбыло.':'＋ Извлечено и поступило · − разделано, передано или выбыло.'} {company?'Внутренние передачи общий запас компании не меняют.':'Передачи внутри выбранной группы складов взаимно исключаются.'}</p>
    {unit==='coils'&&unknownCoils.length>0&&<p className="c-warning"><button className="c-text-button" onClick={()=>onDocs({ids:unknownCoils.map(d=>d.id),title:'Передачи без количества катушек'})}>В {unknownCoils.length} передачах количество катушек не указано.</button></p>}
    {unit==='coils'&&rows.some(m=>balanceCell(s,balanceQuery(m.id,'after','coils')).value<0)&&<p className="c-warning">Отрицательное количество катушек. Проверьте полноту намотки и передач.</p>}
   </section>})}
   {!kinds.length&&<p className="c-empty">Материалы не выбраны.</p>}
   <PidProgress s={s} from={from} to={to} pids={pids} inScope={inScope} materials={chosenMaterials} actor={actor} compact={compact} withMotion={withMotion} withStock={withStock} onDocs={onDocs} filters={!compact&&<div className="stats-pid-filter"><b>Отбор по ПИД</b><div className="stats-chips"><button aria-pressed={!pidSelection.length} onClick={()=>setPids([])}>Все ПИД</button>{M.pidCatalog(s).map(p=><button key={p.id} aria-pressed={pidSelection.includes(p.id)} onClick={()=>setPids(pidSelection.includes(p.id)?pidSelection.filter(id=>id!==p.id):[...pidSelection,p.id])}>{p.id}{p.locality?' · '+p.locality:''}</button>)}</div><p className="c-help">Отбор применяется также к полевым остаткам и движениям выше. Показаны ПИД, где есть выбранные кабели.</p></div>}/>
   <p className="c-help">Нажмите число — откроются документы. Приход из извлечения рассчитан по подтверждённому г/м; отгрузки и приёмки — по взвешиванию. В общей сумме компании учтены партии в пути и неурегулированные расхождения.</p>
   {showStrip&&<details className="c-details"><summary>Разделка: из кабеля в металлы</summary>{strips.length?<><div className="c-total-line"><span>Разделано кабеля</span>{cell(strips.reduce((a,d)=>a+M.current(d).qty,0),strips.map(d=>d.id),'Разделка',' т')}</div>{['copper','lead','aluminium'].map((m,i)=><div className="c-total-line" key={m}><span>Получено: {M.material(s,m)}</span><b>{M.fmt(strips.reduce((a,d)=>a+(M.current(d).metals?.[i]||0),0))} т</b></div>)}</>:<p>Разделки в выбранном периоде нет.</p>}<p className="c-help">Показан весь выпуск выбранных смен. Невзвешенный остаток не приходуется как материал.</p></details>}
  </>:<>
   <div className="c-table-scroll"><table className="c-table"><thead><tr><th>Работа</th><th>До периода</th><th>За период</th><th>Всего</th></tr></thead><tbody>{personalWorks.map(w=>{const before=docs.filter(d=>d.assignment.work===w&&d.date<from),within=selected.filter(d=>d.assignment.work===w),sum=(a:M.WorkDoc[])=>a.reduce((q,d)=>q+M.current(d).qty,0);return <tr key={w}><th>{M.works[w].name}<small>{M.works[w].unit}</small></th><td>{cell(sum(before),before.map(d=>d.id),M.works[w].name+' до периода')}</td><td>{cell(sum(within),within.map(d=>d.id),M.works[w].name+' за период')}</td><td>{cell(sum(before)+sum(within),[...before,...within].map(d=>d.id),M.works[w].name+' всего')}</td></tr>})}</tbody></table></div>
   <p className="c-help">Это выработка, не складской остаток. Копка и намотка не меняют массу кабеля.</p>
   <section className="c-card"><h2>Дисциплина сдачи заданий</h2><div className="c-discipline"><div><b>{closed.length}/{discipline.length}</b><span>заданий заполнено</span></div><div><b>{late.length}</b><span>с опозданием</span></div><div><b>{overdue.length}</b><span>просрочено</span></div></div><p className="c-help">Суточные задания по сотрудникам и областям работы за выбранный период. Отбор по материалу на дисциплину не влияет. Создание в 09:00, срок сдачи — 21:00, Красноярск.</p><details><summary>По ответственным за склады</summary>{[...new Set(discipline.map(t=>t.employee))].map(id=>{const own=discipline.filter(t=>t.employee===id),done=own.filter(t=>t.closed);return <div className="c-total-line" key={id}><span>{M.person(s,id)}</span><b>{done.length} / {own.length}</b></div>})}</details></section>
   {showPay&&showStrip&&<details className="c-details"><summary>Разделка и оплата бригады · {M.fmt(Object.values(pay).reduce((a,b)=>a+b,0),2)} ₽</summary><div className="c-total-line"><span>Разделано</span><b>{M.fmt(strips.reduce((a,d)=>a+M.current(d).qty,0))} т</b></div>{['copper','lead','aluminium'].map((m,i)=><div className="c-total-line" key={m}><span>{M.material(s,m)}</span><b>{M.fmt(strips.reduce((a,d)=>a+(M.current(d).metals?.[i]||0),0))} т</b></div>)}{Object.entries(pay).map(([id,sum])=><div className="c-total-line" key={id}><span>{M.person(s,id)}</span><b>{M.fmt(sum,2)} ₽</b></div>)}<Button variant="outline" onClick={()=>onDocs({ids:strips.map(d=>d.id),title:'Отчёты о разделке и ФОТ'})}>Открыть смены</Button></details>}
  </>}
  </>}
  {!compact&&<a className="c-text-button" href={'/api/operational/export?'+new URLSearchParams({from,to,scope,...(scope==='owners'?{owners:JSON.stringify(owners)}:{}),...(activePids.length?{pids:JSON.stringify(activePids)}:{}),...(exportMaterials!==null?{materials:JSON.stringify(exportMaterials)}:{})})} download>Выгрузить движения за выбранный период · CSV</a>}
  {compact&&scope==='mine'&&<p className="c-help c-scope-note">«Я» — мои задания и склады, за которые я отвечаю или действую как доверенное лицо. Прогресс учитывает мои склады и доверенные мне склады в выбранных ПИД.</p>}
 </>
}

