'use client';
import {useState} from 'react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Textarea} from './ui/textarea';
import {Choice,Field} from './review-common';
import {transferCoils} from '@/lib/concise-coils';
import {balanceCell,balanceDateLabel,balanceScopeLabel,balanceFormat,balanceUnit,columnLabels,type BalanceQuery} from '@/lib/concise-balance';
import {ExclusionForm} from './concise-pid';
import {DayCard,Update} from './concise-work';
import type {DocFilter} from './concise-stats';
import * as M from '@/lib/concise-model';
export function documentTitle(s:M.State,d:M.Document){return d.kind==='exclusion'?'Неизвлекаемый участок · '+M.warehouse(s,d.warehouse):d.kind==='work'?M.works[d.assignment.work].name+' · '+M.warehouse(s,d.assignment.warehouse):d.kind==='transfer'?'Передача · '+M.warehouse(s,d.from)+' → '+M.warehouse(s,d.to):d.kind==='opening'?'Начальный остаток · '+M.warehouse(s,d.warehouse):'Уточнение массы · '+M.warehouse(s,d.warehouse);}
export function TransferForm({s,actor,update,id,onDone}:{s:M.State;actor:string;update:Update;id?:string;onDone:()=>void}){
 const incoming=s.documents.find((d):d is M.Transfer=>d.id===id&&d.kind==='transfer');
 const startFrom=s.warehouses.find(w=>M.canManageWarehouse(s,w.id,actor))?.id||s.warehouses[0].id;
 const [from,setFrom]=useState(startFrom),[to,setTo]=useState(s.warehouses.find(w=>w.id!==startFrom&&w.kind!=='field')?.id||s.warehouses.find(w=>w.id!==startFrom)!.id),[items,setItems]=useState<{material:string;qty:string;weights:string;coils:string}[]>([{material:s.materials.find(m=>M.stock(s,startFrom,m.id)>0)?.id||s.materials.find(m=>m.kind==='cable')?.id||'',qty:'',weights:'',coils:''}]),[received,setReceived]=useState<string[]>(incoming?.items.map(()=>'')||[]),[reason,setReason]=useState(''),[error,setError]=useState('');
 const field=s.warehouses.find(w=>w.id===from)?.kind==='field';
 const allowed=s.materials.filter(m=>M.stock(s,from,m.id)>0);
 const weights=M.parseCoilWeights;
 const byCoils=(i:{material:string})=>field&&s.materials.find(m=>m.id===i.material)?.kind==='cable';
 const quantities=items.map(i=>byCoils(i)?M.round(weights(i.weights).reduce((a,b)=>a+b,0)/1000):M.n(i.qty));
 const validWeights=(text:string)=>weights(text).length>0&&weights(text).every(w=>Number.isFinite(w)&&w>0);
 const invalidCoils=items.some(i=>byCoils(i)&&!validWeights(i.weights));
 const validTotal=quantities.every(q=>Number.isFinite(q)&&q>0)&&!invalidCoils;
 const send=async()=>{try{if(incoming)await update(st=>M.receive(st,incoming.id,received.map(M.n),actor,reason));else{if(items.some(i=>byCoils(i)&&(!weights(i.weights).length||weights(i.weights).some(w=>!Number.isFinite(w)||w<=0))))throw Error('Введите положительные массы катушек в кг через пробел: 801 803 806. Дробная масса: 801,5.');const transfer:M.Transfer={id:'П-'+crypto.randomUUID().slice(0,8),kind:'transfer',date:s.today,from,to,actor,items:items.map((i,k)=>({material:i.material,sent:quantities[k],received:null,...(byCoils(i)?{weights:weights(i.weights)}:s.materials.find(m=>m.id===i.material)?.kind==='cable'&&i.coils.trim()?{coils:M.n(i.coils)}:{})})),weights:items.filter(byCoils).flatMap(i=>weights(i.weights)),reason};await update(st=>M.transfer(st,transfer));}onDone();}catch(e){setError((e as Error).message)}};
 return <div className="c-form">
  {incoming?<><p>{M.warehouse(s,incoming.from)} → {M.warehouse(s,incoming.to)}</p>{incoming.items.map((i,k)=><div className="c-card" key={i.material}><div className="c-total-line"><b>{M.material(s,i.material)}</b><span>Отправлено {M.fmt(i.sent)} т</span></div>{transferCoils(incoming,i)!==null&&<p className="c-help">Катушки по отправке: {transferCoils(incoming,i)} шт. Количество переносится при подтверждении приёмки.</p>}<Field label="Принято по взвешиванию, т" value={received[k]} onChange={v=>setReceived(a=>a.map((x,j)=>j===k?v:x))}/></div>)}</>:<>
   <Choice label="Откуда" value={from} onChange={v=>{setFrom(v);setItems([{material:s.materials.find(m=>M.stock(s,v,m.id)>0)?.id||s.materials.find(m=>m.kind==='cable')?.id||'',qty:'',weights:'',coils:''}]);if(v===to)setTo(s.warehouses.find(w=>w.id!==v)!.id)}} options={s.warehouses.filter(w=>M.canManageWarehouse(s,w.id,actor)).map(w=>[w.id,w.name])}/>
   <Choice label="Куда" value={to} onChange={setTo} options={s.warehouses.filter(w=>w.id!==from).map(w=>[w.id,w.name])}/>
   {items.map((i,k)=><div className="c-card" key={k}><Choice label="Материал" value={i.material} onChange={v=>setItems(items.map((x,j)=>j===k?{...x,material:v}:x))} options={allowed.filter(m=>!items.some((x,j)=>j!==k&&x.material===m.id)).map(m=>[m.id,m.name])}/><div className="c-total-line"><span>Доступно</span><b>{M.fmt(M.stock(s,from,i.material))} т</b></div>{byCoils(i)?<label className="c-field">Массы катушек, кг<Textarea aria-label="Массы катушек, кг" inputMode="text" placeholder="801 803 806 900" value={i.weights} onChange={e=>setItems(items.map((x,j)=>j===k?{...x,weights:e.target.value}:x))}/><span className="c-help">Массы через пробел. Дробная масса — 801,5 или 801.5 (до 3 знаков). Вес катушки — вес кабеля.</span><b aria-live="polite">{!i.weights.trim()?'Введите массы катушек':validWeights(i.weights)?weights(i.weights).length+' шт. · '+M.fmt(quantities[k]*1000)+' кг · '+M.fmt(quantities[k],6)+' т':'Проверьте массы: каждое число больше нуля, разделитель — пробел'}</b></label>:<><Field label="Измерено к отправке, т" value={i.qty} onChange={v=>setItems(items.map((x,j)=>j===k?{...x,qty:v}:x))}/>{s.materials.find(m=>m.id===i.material)?.kind==='cable'&&<Field label="Катушки, шт. (если известно)" value={i.coils} onChange={v=>setItems(items.map((x,j)=>j===k?{...x,coils:v}:x))}/>}</>} {items.length>1&&<Button variant="ghost" onClick={()=>setItems(items.filter((_,j)=>j!==k))}>Убрать позицию</Button>}</div>)}
   {allowed.length>items.length&&<Button variant="outline" onClick={()=>setItems([...items,{material:allowed.find(m=>!items.some(i=>i.material===m.id))!.id,qty:'',weights:'',coils:''}])}>＋ Материал в эту отправку</Button>}
   <div className="c-total-line"><span>Всего к отправке</span><b>{validTotal?M.fmt(quantities.reduce((a,b)=>a+b,0),6)+' т':'Заполните массы всех позиций'}</b></div>
  </>}
  <label className="c-field">{incoming?'Комментарий / причина расхождения':'Комментарий'}<Textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>
  {error&&<p className="c-error" role="alert">{error}</p>}
  <Button onClick={send} disabled={!incoming&&!validTotal}>{incoming?'Подтвердить приёмку':'Подтвердить отправку'}</Button>
 </div>
}
export function DocumentList({s,filter,onDocument}:{s:M.State;filter?:DocFilter;onDocument:(id:string)=>void}){
 const [query,setQuery]=useState(''),[kind,setKind]=useState('all'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[limit,setLimit]=useState(20);
 if(filter?.balance)return <BalanceDocuments s={s} query={filter.balance} onDocument={onDocument}/>;
 const terms=query.trim().toLowerCase().split(/\s+/);
 const list=s.documents.filter(d=>{
  if(filter?.ids&&!filter.ids.includes(d.id)||kind!=='all'&&d.kind!==kind||from&&d.date<from||to&&d.date>to)return false;
  const extra=d.kind==='exclusion'?d.versions.map(v=>M.person(s,v.actor)+' '+v.reason).join(' '):d.kind==='work'?[M.material(s,d.assignment.material),...d.versions.map(v=>M.person(s,v.actor))].join(' '):[M.person(s,d.actor),d.kind==='transfer'?d.items.map(i=>M.material(s,i.material)).join(' '):M.material(s,d.material)].join(' ');
  const text=[d.id,d.date,documentTitle(s,d),extra].join(' ').toLowerCase();return terms.every(term=>text.includes(term));
 }).sort((a,b)=>b.date.localeCompare(a.date));
 return <div className="c-form"><Input aria-label="Поиск документа" placeholder="Дата, ПИД, склад, автор или номер" value={query} onChange={e=>setQuery(e.target.value)}/><div className="c-grid-two"><Field label="С даты" type="date" value={from} onChange={setFrom}/><Field label="По дату" type="date" value={to} onChange={setTo}/></div><Choice label="Вид документа" value={kind} onChange={setKind} options={[["all","Все документы"],["work","Выполненная работа"],["transfer","Перемещение"],["opening","Начальный остаток"],["adjustment","Уточнение массы"],["exclusion","Неизвлекаемый участок ПИД"]]}/><p className="c-help">Найдено: {list.length}</p>{list.slice(0,limit).map(d=><button className="c-document-item" onClick={()=>onDocument(d.id)} key={d.id}><span><b>{documentTitle(s,d)}</b><small>{M.dateLabel(d.date)} · {d.id}</small></span><span>›</span></button>)}{!list.length&&<p className="c-empty">По этим условиям документов нет.</p>}{list.length>limit&&<Button variant="outline" onClick={()=>setLimit(limit+20)}>Показать ещё</Button>}</div>
}
function BalanceDocuments({s,query,onDocument}:{s:M.State;query:BalanceQuery;onDocument:(id:string)=>void}){
 const [limit,setLimit]=useState(20);
 const result=balanceCell(s,query),unit=balanceUnit(query);
 return <div className="c-form">
  <section className="c-card" aria-label="Расшифровка показателя">
   <p>{balanceScopeLabel(s,query)} · {M.material(s,query.material)}{query.unit==='coils'?' · катушки':''}</p>
   <p className="c-help">{balanceDateLabel(query)}</p>
   <div className="c-total-line"><span>{columnLabels[query.column]} · сумма документов</span><b>{balanceFormat(result.value,query)} {unit}</b></div>
   <p className="c-help">{query.column==='minus'?'Вклад каждого документа показан как количество расхода.':'Знак у документа показывает его вклад в выбранную цифру.'} Учтены действующие версии и даты движений. Документы с нулевым вкладом исключены.</p>
  </section>
  <p className="c-help">Документов в расчёте: {result.contributions.length}</p>
  {result.contributions.slice(0,limit).map(row=>{const d=s.documents.find(d=>d.id===row.docId)!;return <button className="c-document-item" onClick={()=>onDocument(d.id)} key={d.id}><span><b>{documentTitle(s,d)}</b><small>{M.dateLabel(d.date)} · {d.id}</small><small>Движение: {row.dates.map(M.dateLabel).join('; ')}</small><strong className="c-document-contribution">{query.column==='minus'?'Расход ':row.quantity>0?'+':''}{balanceFormat(row.quantity,query)} {unit}</strong></span><span>›</span></button>})}
  {!result.contributions.length&&<p className="c-empty">Документов с ненулевым вкладом нет. Значение показателя — 0 {unit}.</p>}
  {result.contributions.length>limit&&<Button variant="outline" onClick={()=>setLimit(limit+20)}>Показать ещё</Button>}
 </div>;
}
export function DocumentDetail({s,id,actor,web,update,onClose}:{s:M.State;id:string;actor:string;web:boolean;update:Update;onClose:()=>void}){
 const [editing,setEditing]=useState(false),[reason,setReason]=useState(''),[delta,setDelta]=useState(''),[error,setError]=useState('');
 const [loadedDocument]=useState(()=>JSON.stringify(s.documents.find(d=>d.id===id)));
 const doc=s.documents.find(d=>d.id===id)!;
 const [masses,setMasses]=useState(doc?.kind==='transfer'?doc.items.map(i=>({sent:String(i.sent),received:i.received===null?'':String(i.received)})):[]);
 if(!doc)return <p>Документ не найден.</p>;
 if(doc.kind==='exclusion'){
  const v=doc.versions.at(-1)!;
  if(editing)return <ExclusionForm s={s} actor={actor} update={update} doc={doc} onSaved={()=>setEditing(false)}/>;
  return <div className="c-form"><h3>{documentTitle(s,doc)}</h3><p>{M.dateLabel(doc.date)} · МОЛ {M.person(s,s.warehouses.find(w=>w.id===doc.warehouse)!.owner)}</p><div className="c-total-line"><span>Длина неизвлекаемого участка</span><b>{M.fmt(M.exclusionLength(v))} м</b></div><p>{v.reason}</p><p className="c-help">Увеличивает освоение ПИД. Не является копкой или поступлением кабеля.</p>{M.canManageWarehouse(s,doc.warehouse,actor)&&<Button onClick={()=>setEditing(true)}>Исправить документ</Button>}<details className="c-details"><summary>Авторство и история · {doc.versions.length} вер.</summary>{doc.versions.map(v=><div className="c-history" key={v.version}><b>Версия {v.version} · {M.fmt(M.exclusionLength(v))} м</b><span>Ввёл {M.person(s,v.actor)} · {new Date(v.at).toLocaleString('ru-RU',{timeZone:'Asia/Krasnoyarsk'})}</span><p>{v.reason}</p></div>)}</details></div>
 }
 if(doc.kind==='work'){
  const v=M.current(doc),a=doc.assignment,task=s.tasks.find(t=>t.id===doc.taskId)!,canEdit=M.canReport(s,a,actor)&&(web||a.work!=='strip');
  if(editing)return <DayCard s={s} actor={actor} update={update} tasks={[task]} editing onSaved={()=>setEditing(false)}/>;
  return <div className="c-form"><h3>{documentTitle(s,doc)}</h3><p>{M.dateLabel(doc.date)} · {M.person(s,doc.versions[0].actor)}</p>{doc.source==='restored'&&<p className="c-help">История восстановлена по согласованным данным. Суточное распределение работ условное; в дисциплине сдачи заданий не участвует.</p>}<div className="c-total-line"><span>{M.works[a.work].name}</span><b>{v.mode==='work'?M.fmt(v.qty)+' '+M.works[a.work].unit:v.mode==='off'?'Выходной':'Простой'}</b></div>{v.measure&&<div className="c-card"><b>{M.fmt(v.qty*v.measure.kgPerM/1000)} т · расчётная масса</b><p>{M.fmt(v.qty)} м × {M.fmt(v.measure.kgPerM*1000,3)} г/м</p><p className="c-help">{M.material(s,a.material)} · Удельная масса {v.measure.id} от {M.dateLabel(v.measure.date)} · подтвердил {M.person(s,v.measure.confirmedBy)}</p>{v.measure.reason&&<p className="c-help">Основание: {v.measure.reason}</p>}</div>}{a.work==='strip'&&<>{['copper','lead','aluminium'].map((m,i)=><div className="c-total-line" key={m}><span>Получено: {M.material(s,m)}</span><b>{M.fmt(v.metals?.[i]||0)} т</b></div>)}<div className="c-pay"><span>{M.fmt(v.rate,0)} ₽/т</span><b>Бригаде {M.fmt(v.qty*v.rate,2)} ₽</b></div>{v.crew.map((c,i)=><div className="c-total-line" key={c.employee}><span>{M.person(s,c.employee)} · КТУ {c.ktu}</span><b>{M.fmt(M.payout(v.qty*v.rate,v.crew)[i],2)} ₽</b></div>)}</>}{v.reason&&<p>{v.reason}</p>}{canEdit?<Button onClick={()=>setEditing(true)}>Исправить документ</Button>:!web&&a.work==='strip'?<p className="c-help">Исправление разделки с проверкой связанных операций доступно в <a href="/web">WEB</a>.</p>:null}<details className="c-details"><summary>Авторство и история · {v.version} вер.</summary><p>МОЛ: {M.person(s,M.assignmentOwner(s,a))}<br/>Склад: {M.warehouse(s,a.warehouse)}</p>{doc.versions.map(v=><div className="c-history" key={v.version}><b>Версия {v.version} · {M.fmt(v.qty)} {M.works[a.work].unit}</b><span>{M.person(s,v.actor)} · {new Date(v.at).toLocaleString('ru-RU',{timeZone:'Asia/Krasnoyarsk'})}</span>{v.measure&&<p>{M.fmt(v.measure.kgPerM*1000,3)} г/м → {M.fmt(v.qty*v.measure.kgPerM/1000)} т · коэффициент {v.measure.id}{v.measure.reason?' · '+v.measure.reason:''}</p>}<p>{v.reason||'Первичное подтверждение'}</p></div>)}</details></div>
 }
 if(doc.kind==='transfer'){
  const delta=doc.items.reduce((s,i)=>s+i.sent-(i.received??i.sent),0);
  const save=async()=>{try{if(reason.trim().length<3)throw Error('Укажите причину исправления.');const items=doc.items.map((i,k)=>({...i,sent:M.n(masses[k].sent),received:i.received===null?null:M.n(masses[k].received)}));if(items.some(i=>!Number.isFinite(i.sent)||i.sent<=0||i.received!==null&&(!Number.isFinite(i.received)||i.received<0)))throw Error('Проверьте массу.');if(items.some((i,k)=>(doc.weights.length||i.weights?.length)&&i.sent!==doc.items[k].sent))throw Error('Для изменения взвешенной отправки требуется исправление исходных масс катушек. Сохраните исходные массы катушек; для исправления отправки обратитесь к администратору.');await update(st=>{const original=st.documents.find(d=>d.id===doc.id);if(JSON.stringify(original)!==loadedDocument)throw Error('Документ уже изменён. Откройте его заново.');const next={...st,documents:st.documents.map(d=>d.id!==id?d:{...doc,items,history:[...(doc.history||[]),{at:new Date().toISOString(),actor,reason,items:doc.items}],reason})};M.assertStock(next);return next});setEditing(false);}catch(e){setError((e as Error).message)}};
  return <div className="c-form"><h3>{documentTitle(s,doc)}</h3><p>{M.dateLabel(doc.date)} · отправил {M.person(s,doc.actor)}</p>{doc.items.map((i,k)=><div className="c-card" key={i.material}><b>{M.material(s,i.material)}</b>{s.materials.find(m=>m.id===i.material)?.kind==='cable'&&<p className="c-help">{transferCoils(doc,i)===null?'Количество катушек не указано':'Катушки по отправке: '+transferCoils(doc,i)+' шт.'}</p>}{editing?<div className="c-grid-two"><Field label="Отправлено, т" disabled={!!(doc.weights.length||i.weights?.length)} value={masses[k].sent} onChange={v=>setMasses(masses.map((x,j)=>j===k?{...x,sent:v}:x))}/>{i.received!==null&&<Field label="Принято, т" value={masses[k].received} onChange={v=>setMasses(masses.map((x,j)=>j===k?{...x,received:v}:x))}/>}</div>:<div className="c-total-line"><span>Отправлено {M.fmt(i.sent)} т</span><b>{i.received===null?'Ожидает приёмки':'Принято '+M.fmt(i.received)+' т'}</b></div>}</div>)}{!!doc.weights.length&&<p className="c-help">Катушки: {doc.weights.map(x=>M.fmt(x)).join('; ')} кг · {doc.weights.length} шт.</p>}{Math.abs(delta)>.000001&&<p className="c-warning">Расхождение {M.fmt(delta)} т. Оно учтено отдельно до выяснения причины.</p>}<p>{doc.reason}</p>{editing?<><label className="c-field">Причина исправления<Textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p className="c-error">{error}</p>}<Button onClick={save}>Сохранить исправление</Button></>:web&&actor==='admin'?<Button onClick={()=>setEditing(true)}>Исправить документ</Button>:<p className="c-help">Связанные отправка и приёмка исправляются в WEB администратором.</p>}{!!doc.history?.length&&<details className="c-details"><summary>История исправлений</summary>{doc.history.map((h,k)=><div className="c-history" key={k}><b>{M.person(s,h.actor)} · {h.reason}</b>{h.items.map(i=><span key={i.material}>{M.material(s,i.material)}: было отправлено {M.fmt(i.sent)} т, принято {i.received===null?'—':M.fmt(i.received)+' т'}</span>)}</div>)}</details>}</div>
 }
 const adjust=async()=>{try{const qty=M.n(delta);if(!Number.isFinite(qty)||qty===0||reason.trim().length<3)throw Error('Укажите ненулевую разницу массы и основание.');const a:M.Adjustment={id:'К-'+crypto.randomUUID().slice(0,8),kind:'adjustment',date:s.today,warehouse:doc.warehouse,material:doc.material,qty,actor,reason,basis:doc.id};await update(st=>{const next={...st,documents:[...st.documents,a]};M.assertStock(next);return next});onClose();}catch(e){setError((e as Error).message)}};
 return <div className="c-form"><h3>{documentTitle(s,doc)}</h3><p>{M.dateLabel(doc.date)} · {M.material(s,doc.material)}</p><b>{M.fmt(doc.qty)} т</b>{doc.kind==='adjustment'&&<p>{doc.reason} · основание {doc.basis}</p>}{web&&actor==='admin'&&<details className="c-details"><summary>Уточнить массу отдельным документом</summary><Field label="Изменение остатка, т (со знаком)" value={delta} onChange={setDelta}/><label className="c-field">Основание<Textarea value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<p className="c-error">{error}</p>}<Button onClick={adjust}>Подтвердить уточнение</Button></details>}</div>
}


