'use client';
import * as M from '@/lib/concise-model';
import {coilBalance} from '@/lib/concise-coils';
import {BalanceValue} from './concise-balance';
import type {DocFilter} from './concise-stats';
export function CoilTable({s,from,to,inScope,company,material,scope,actor,onDocs}:{s:M.State;from:string;to:string;inScope:(w:string)=>boolean;company:boolean;material:string;scope:string;actor:string;onDocs:(f:DocFilter)=>void}){
 const {rows,unknown}=coilBalance(s,from,to,inScope,company,material);
 return <><div className="c-section-title"><h3>Учтённые катушки</h3><span>шт.</span></div><div className="c-table-scroll"><table className="c-table balance"><thead><tr><th>Кабель</th><th>Было</th><th>＋</th><th>−</th><th>Стало</th></tr></thead><tbody>{rows.map(r=><tr key={r.material.id}><th>{r.material.name.replace('Кабель ','')}</th>{(['before','plus','minus','after'] as const).map((k,i)=><td key={k} className={k==='plus'?'c-plus':k==='after'?'c-ending':''}><BalanceValue s={s} query={{scope,actor,material:r.material.id,unit:'coils',from,to,column:k}} onDocs={onDocs}/></td>)}</tr>)}</tbody></table></div><p className="c-help">{company?'＋ Намотано. Передачи между своими складами общее количество не меняют.':'＋ Намотано и принято · − передано. Приёмка переносит количество из отправки; расхождение массы не меняет число катушек.'}</p>{unknown.length>0&&<p className="c-warning"><button className="c-text-button" onClick={()=>onDocs({ids:unknown.map(d=>d.id),title:'Передачи без количества катушек'})}>В {unknown.length} передачах количество не указано.</button> Их движение в штуках не включено в таблицу.</p>}{rows.some(r=>r.after<0)&&<p className="c-warning">Отрицательное количество: отправок больше, чем зарегистрированной намотки и приёмки. Проверьте полноту документов.</p>}<p className="c-help">Катушки не меняют массу кабеля. Начальные остатки и разделка ведутся без их количества — таблица показывает учтённые катушки, а не полный физический остаток после разделки.</p></>
}
