'use client';
import {useState} from 'react';
import * as M from '@/lib/concise-model';
import * as D from '@/lib/daily-work';
import {Button} from './ui/button';
import {Choice,Field} from './review-common';
import {MeasurementField} from './concise-measurement';
import type {Update} from './concise-work';
type Submit=(v:D.DailySubmission)=>Promise<void>;
type Draft={key:string;work:M.Work;material:string;qty:string;measureId:string;confirmed:boolean;metals:string[];touched:boolean};

export function DailyForm({s,t,employee,update,submit,editing=false}:{editing?:boolean;s:M.State;t:D.DailyTask;employee:string;update:Update;submit:Submit}){
 const previous=D.documents(s,t),pending=editing?t.functions:D.remaining(s,t),available=(work:M.Work)=>s.materials.filter(m=>m.kind==='cable'&&(work==='strip'?(M.stock(s,t.warehouse,m.id,t.date)>0||editing&&previous.some(d=>d.assignment.material===m.id)):t.materials.includes(m.id)));
 const make=(work:M.Work,material=available(work)[0]?.id||''):Draft=>{const a=D.taskForLine(t,{work,material:work==='dig'?'':material});return {key:crypto.randomUUID(),work,material:a.assignment.material,qty:'',measureId:M.measurementAt(s,a.assignment,t.date)?.id||'',confirmed:false,metals:['0','0','0'],touched:false}};
 const [expected]=useState(()=>previous.map(d=>({id:d.id,version:M.current(d).version})));
 const [lines,setLines]=useState<Draft[]>(()=>D.worksOrder.filter(w=>pending.includes(w)).flatMap(w=>{const docs=editing?previous.filter(d=>d.assignment.work===w&&M.current(d).mode==='work'&&M.current(d).qty>0):[];return docs.length?docs.map(d=>{const v=M.current(d);return {...make(w,d.assignment.material),qty:String(v.qty),measureId:v.measure?.id||'',metals:(v.metals||[0,0,0]).map(String),touched:true}}):[make(w)]}));
 const [mode,setMode]=useState<'work'|'off'|'idle'>('work'),[reason,setReason]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const [crew,setCrew]=useState<M.Crew[]>(()=>editing&&previous.some(d=>d.assignment.work==='strip'&&M.current(d).crew.length)?structuredClone(M.current(previous.find(d=>d.assignment.work==='strip'&&M.current(d).crew.length)!).crew):((M.crewTemplates(s,t.warehouse).find(x=>x.active!==false)?.members)||[]).filter(id=>s.employees.some(e=>e.id===id&&e.active)).map(employee=>({employee,ktu:1})));
 const standard=(l:Draft)=>{const doc=editing?previous.find(d=>d.assignment.work===l.work&&d.assignment.material===l.material):undefined;return doc?M.current(doc):M.standardAt(s,t.date,l.material)};
 const change=(key:string,patch:Partial<Draft>)=>setLines(old=>old.map(l=>l.key===key?{...l,...patch}:l));
 const total=M.round(lines.filter(l=>l.work==='strip').reduce((a,l)=>a+(M.n(l.qty)||0)*(standard(l)?.rate||0),0));
 const shares=crew.map((_,i)=>lines.filter(l=>l.work==='strip').reduce((sum,l)=>sum+(M.payout((M.n(l.qty)||0)*(standard(l)?.rate||0),crew)[i]||0),0));
 const save=async()=>{try{setSaving(true);await submit({id:t.id,...(editing?{edit:true,expected}:{}),mode,reason,crew,lines:mode==='work'?lines.map(l=>({work:l.work,material:l.material,qty:M.n(l.qty),...(l.measureId?{measureId:l.measureId}:{}),confirmed:l.confirmed,...(l.work==='strip'?{metals:l.metals.map(M.n)}:{})})):[]});setError('')}catch(e){setError((e as Error).message)}finally{setSaving(false)}};
 return <div className="c-form daily-form"><p className="c-help">Одно задание для {M.person(s,t.employee)} и доверенных лиц. Заполнение закрывает его у всех.</p>
 <div className="c-day-modes"><Button variant="outline" aria-pressed={mode==='off'} onClick={()=>setMode(mode==='off'?'work':'off')}>Выходной</Button><Button variant="outline" aria-pressed={mode==='idle'} onClick={()=>setMode(mode==='idle'?'work':'idle')}>Простой</Button></div>
 {mode==='work'&&D.worksOrder.filter(w=>pending.includes(w)).map(work=><section key={work} className="daily-function"><h3>{M.works[work].name}</h3>{lines.filter(l=>l.work===work).map(l=>{const norm=standard(l),q=M.n(l.qty)||0,task=D.taskForLine(t,l);return <div className="c-form c-inset" key={l.key}>
 {work!=='dig'&&<Choice label="Кабель" value={l.material} onChange={material=>change(l.key,{...make(work,material),key:l.key})} options={[["","Выберите кабель"],...available(work).map(m=>[m.id,m.name+(work==='strip'?' · доступно '+M.fmt(M.stock(s,t.warehouse,m.id,t.date))+' т':'')] as [string,string])]}/>}
 <Field label={M.works[work].name+', '+M.works[work].unit} value={l.qty} onChange={qty=>change(l.key,{qty,...(work==='strip'&&!l.touched?{metals:(norm?.norm||[0,0,0]).map(n=>String(M.round((M.n(qty)||0)*n/100)))}:{})})}/>
 {work!=='dig'&&lines.filter(x=>x.work===work).length>1&&<Button variant="ghost" onClick={()=>setLines(xs=>xs.filter(x=>x.key!==l.key))}>Убрать кабель</Button>}
 {work==='extract'&&l.material&&q>0&&<MeasurementField s={s} task={task} actor={employee} update={update} createMeasurement={m=>update(st=>({...st,measurements:[...st.measurements,m]}))} saved={editing?previous.find(d=>d.assignment.work===l.work&&d.assignment.material===l.material)?.versions.at(-1)?.measure:undefined} measureId={l.measureId} confirmed={l.confirmed} qty={q} onChange={(measureId,confirmed)=>change(l.key,{measureId,confirmed})}/>}
 {work==='strip'&&l.material&&<><p className="c-help">Тариф: {norm?M.fmt(norm.rate)+' ₽/т':'не задан'} · Оплата: {M.fmt(q*(norm?.rate||0),2)} ₽</p><div className="c-metal-input"><div className="c-mini-head"><span>Металлы, т</span><span>Норма</span><span>Факт</span></div>{['Медь','Свинец','Алюминий'].map((name,i)=><label className="c-mini-row" key={name}><b>{name}</b><span>{M.fmt(q*(norm?.norm[i]||0)/100)}</span><input aria-label={name+' факт, т'} inputMode="decimal" value={l.metals[i]} onChange={e=>change(l.key,{touched:true,metals:l.metals.map((x,k)=>k===i?e.target.value:x)})}/><small>Отклонение {M.fmt((M.n(l.metals[i])||0)-q*(norm?.norm[i]||0)/100)} т</small></label>)}</div></>}
 </div>})}{work!=='dig'&&available(work).some(m=>!lines.some(l=>l.work===work&&l.material===m.id))&&<Button variant="outline" onClick={()=>setLines(xs=>[...xs,make(work,available(work).find(m=>!xs.some(l=>l.work===work&&l.material===m.id))!.id)])}>Добавить кабель · {M.works[work].name.toLowerCase()}</Button>}
 {work==='strip'&&!available(work).length&&<p className="c-help">На дату задания кабеля на складе нет. Укажите 0 и причину либо закройте задание как простой / выходной.</p>}
 </section>)}
 {mode==='work'&&pending.includes('strip')&&<section className="c-form c-crew"><h3>Бригада за смену</h3><div className="c-pay"><span>Фонд оплаты по всем разделанным кабелям</span><b>{M.fmt(total,2)} ₽</b></div><Choice label="Заполнить бригаду по шаблону" value="" onChange={id=>{const tpl=s.templates.find(x=>x.id===id);if(tpl)setCrew(tpl.members.filter(id=>s.employees.some(e=>e.id===id&&e.active)).map(employee=>({employee,ktu:1})))}} options={[["","Выберите шаблон"],...M.crewTemplates(s,t.warehouse).filter(x=>x.active!==false).map(x=>[x.id,x.name] as [string,string])]}/>
 {crew.map((c,i)=><div className="c-person-row" key={c.employee}><span>{M.person(s,c.employee)}</span><label className="c-field">КТУ<input aria-label={'КТУ '+M.person(s,c.employee)} inputMode="decimal" value={String(c.ktu)} onChange={e=>setCrew(cs=>cs.map(x=>x.employee===c.employee?{...x,ktu:M.n(e.target.value)}:x))}/></label><b>{M.fmt(shares[i]||0,2)} ₽</b><button aria-label={'Убрать '+M.person(s,c.employee)} onClick={()=>setCrew(cs=>cs.filter(x=>x.employee!==c.employee))}>×</button></div>)}
 <Choice label="Добавить участника" value="" onChange={employee=>employee&&setCrew(cs=>[...cs,{employee,ktu:1}])} options={[["","Выберите сотрудника"],...s.employees.filter(e=>e.active&&!crew.some(c=>c.employee===e.id)).map(e=>[e.id,e.name] as [string,string])]}/></section>}
 <Field label={editing?'Причина исправления':mode==='work'?'Комментарий (обязателен при нулевом объёме или отклонении)':'Причина '+(mode==='off'?'выходного':'простоя')} value={reason} onChange={setReason}/>
 {error&&<p role="alert" className="c-error">{error}</p>}<Button disabled={saving} onClick={save}>{saving?'Сохраняем…':editing?'Сохранить исправление':mode==='work'?'Подтвердить задание':'Закрыть с пояснением'}</Button></div>;
}

export function DailyWorkPanel({s,employee,admin,update,submit,onDocument,onTransfer,onExclusion}:{s:M.State;employee:string;admin:boolean;update:Update;submit:Submit;onDocument:(id:string)=>void;onTransfer:(id?:string)=>void;onExclusion:()=>void}){
 const [scope,setScope]=useState<'mine'|'all'>('mine'),[owner,setOwner]=useState(''),[pid,setPid]=useState(''),[status,setStatus]=useState('open'),[work,setWork]=useState(''),[limit,setLimit]=useState(20);
 const mine=scope==='mine'||!admin,base=(s.dailyTasks||[]).filter(t=>mine?D.canFill(s,t,employee):true);
 const rows=base.filter(t=>(!owner||t.employee===owner)&&(!pid||(pid==='none'?!t.pid:t.pid===pid))&&(!work||t.functions.includes(work as M.Work))&&(status==='done'?D.completed(s,t):status==='late'?D.overdue(s,t):status==='today'?!D.completed(s,t)&&t.date===s.today:!D.completed(s,t))).sort((a,b)=>a.date.localeCompare(b.date)||M.person(s,a.employee).localeCompare(M.person(s,b.employee),'ru')||a.warehouse.localeCompare(b.warehouse));
 const manageable=(id:string)=>M.canManageWarehouse(s,id,employee),incoming=s.documents.filter((d):d is M.Transfer=>d.kind==='transfer'&&d.items.every(i=>i.received===null)&&manageable(d.to)),outgoing=s.documents.filter((d):d is M.Transfer=>d.kind==='transfer'&&d.items.every(i=>i.received===null)&&manageable(d.from));
 return <><h1>Моя работа</h1>{admin&&<div className="c-segments" aria-label="Область заданий"><button aria-pressed={mine} onClick={()=>{setScope('mine');setOwner('');setPid('')}}>Мои задания</button><button aria-pressed={!mine} onClick={()=>setScope('all')}>Все задания</button></div>}
 <details className="daily-filters" open={!mine}><summary>Отбор заданий{owner||pid||work||status!=='open'?' · применён':''}</summary><div className="settings-toolbar">{!mine&&<Choice label="Ответственный" value={owner} onChange={setOwner} options={[["","Все сотрудники"],...s.employees.filter(e=>base.some(t=>t.employee===e.id)).map(e=>[e.id,e.name] as [string,string])]}/>}<Choice label="ПИД заданий" value={pid} onChange={setPid} options={[["","Все области"],["none","Без ПИД"],...s.pids.filter(p=>base.some(t=>t.pid===p.id)).map(p=>[p.id,'ПИД'+p.id] as [string,string])]}/><Choice label="Состояние заданий" value={status} onChange={setStatus} options={[["open","Все незакрытые"],["late","Просроченные"],["today","На сегодня"],["done","Заполненные"]]}/><Choice label="Функция задания" value={work} onChange={setWork} options={[["","Все функции"],...Object.entries(M.works).map(([id,w])=>[id,w.name] as [string,string])]}/><Button variant="ghost" onClick={()=>{setOwner('');setPid('');setWork('');setStatus('open')}}>Сбросить отборы</Button></div></details>
 <p className="c-help">Найдено заданий: {rows.length}. {status==='done'?'Заполненные задания и документы.':'Сначала ранние незакрытые задания.'}</p>
 {!rows.length&&<p className="c-empty">{!base.length&&mine?'Назначенных вам заданий нет.':'По выбранным условиям заданий нет.'}</p>}
 <div className="c-days">{rows.slice(0,limit).map(t=><details className="c-task-fold daily-task" key={t.id}><summary><b>{M.taskDateLabel(t.date)} · {M.person(s,t.employee)}</b><span>{t.pid?'ПИД'+t.pid:'Без ПИД'} · {t.functions.map(w=>M.works[w].name).join(', ')} · {D.completed(s,t)?'Заполнено':D.overdue(s,t)?'Просрочено':'К заполнению'}</span></summary><div className="c-inset">{D.completed(s,t)?D.documents(s,t).map(d=><button className="c-done-line" key={d.id} onClick={()=>onDocument(d.id)}><span>{M.works[d.assignment.work].name} · {d.assignment.material&&M.material(s,d.assignment.material)}<small>Ввёл {M.person(s,M.current(d).actor)}</small></span><b>{M.fmt(M.current(d).qty)} {M.works[d.assignment.work].unit} ›</b></button>):<DailyForm s={s} t={t} employee={employee} update={update} submit={submit}/>}</div></details>)}</div>
 {rows.length>limit&&<Button variant="outline" onClick={()=>setLimit(n=>n+20)}>Ещё задания</Button>}
 {mine&&<>{s.warehouses.some(w=>manageable(w.id))&&<section className="c-occasional"><h2>По необходимости</h2><Button onClick={()=>onTransfer()}>Добавить перемещение</Button>{s.warehouses.some(w=>w.pid&&manageable(w.id))&&<Button variant="outline" onClick={onExclusion}>Неизвлекаемый участок ПИД</Button>}</section>}{!!(incoming.length||outgoing.length)&&<section><h2>Перемещения</h2>{incoming.map(d=><button className="c-arrival" key={d.id} onClick={()=>onTransfer(d.id)}>Принять · {M.warehouse(s,d.from)} → {M.warehouse(s,d.to)} · {M.fmt(d.items.reduce((a,i)=>a+i.sent,0))} т</button>)}{outgoing.map(d=><button className="c-done-line" key={d.id} onClick={()=>onDocument(d.id)}>Ожидаю приёмку · {M.warehouse(s,d.to)} · {d.date}</button>)}</section>}</>}
 </>;
}
